### ISSUE TITLE
Show inferred type at point constantly

### ISSUE THREAD

**Issue by ghost** [SublimeHaskell/SublimeHaskell#134]
At all times the user sees currently inferred type
as a comment above point.

### Implementation ideas
- Can be toggled from SublimeHaskell User settings.
- The line uses a comment so ModuleInspector or hsdev can still work when saving.
- Inferred type is shown in reverse order to current `SublimeHaskell: Show Type` command _(1)_
- Cursor offset from line's beginning is added to the added comment, with adjustments so it lines with cursor _(2)_

### Example
Cursor is represented by a `◪`.

```Haskell
     -- scotty 3333 :: ScottyM () -> IO ()
     -- scotty :: Port -> ScottyM () -> IO ()
main = ◪scotty 3333 $ do

    get "/" $ do
        html . renderHtml $ do
            H.h1 "STUPID EXAMPLE"
```

```Haskell
               -- scotty 3000 :: ScottyM () -> IO ()
               -- 3000 :: Int
main = scotty 333◪3 $ do

    get "/" $ do
        html . renderHtml $ do
            H.h1 "STUPID EXAMPLE"
```

```Haskell
main = scotty 3333 $ do

       -- get "/" :: ActionM () -> ScottyM ()
       -- "/" :: RoutePattern
    get "◪/" $ do
        html . renderHtml $ do
            H.h1 "STUPID EXAMPLE"
```

```Haskell
main = scotty 3333 $ do

    get "/" $ do
                  -- html . renderHtml :: Html -> ActionM ()
                  -- renderHtml :: Html -> Text
        html . rende◪rHtml $ do
            H.h1 "STUPID EXAMPLE"
```
### Notes
_1_ Since it will be read bottom-up the order of results should be inversed.
_2_ A better solution would line always with word at point as on first example, but deserves its own separate enhancement if/when this gets implemented ; )

**Comment by mvoidex** [comment]
There's `show/hide all types` command
![img](https://raw.githubusercontent.com/SublimeHaskell/SublimeHaskell/master/Commands/Types.gif)
