### ISSUE TITLE
Compile error when using language extensions 

### ISSUE THREAD

**Issue by mfoda** [SublimeHaskell/SublimeHaskell#135]
This is a minor issue:
<pre>{-# LANGUAGE LambdaCase #-}
...
main = getLine >>= \case 
...
</pre>On save gives the following error:<pre>
Build FAILED
...
Warning: Parse error: case
</pre>
But the file actually compiles fine and can be run/loaded into GHCI.

**Comment by mvoidex** [comment]
Reopen if it still fails
