### ISSUE TITLE
view.window() can be None

### ISSUE THREAD

**Issue by nh2** [SublimeHaskell/SublimeHaskell#140]
I just got

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 190, in on_post_save
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 189, in <lambda>
  File "./autobuild.py", line 22, in on_post_save
    view.window().run_command('sublime_haskell_build_auto')
AttributeError: 'NoneType' object has no attribute 'run_command'
```

That happens when you open the same file in 2 tabs (e.g. with `File -> New view into file`). In that case `view.window()` returns `None`. I guess it means "this buffer is not currently visible". Of course that's not documented in the API reference...

In the case with the 2 tabs, `on_post_save()` will then be called twice for the same file.

We should guard against that in all places where we use `view.window()`.

**Comment by bscottm** [comment]
Closing old issue. Re-open as a new issue if necessary.
