### ISSUE TITLE
Error when using haskell-src-exts-1.16.0:  Failed to compile ModuleInspector

### ISSUE THREAD

**Issue by doubleloop** [SublimeHaskell/SublimeHaskell#169]
```
SublimeHaskell: Failed to compile ModuleInspector

/home/doubleloop/.config/sublime-text-3/Packages/SublimeHaskell/ModuleInspector.hs:141:12:
    Not in scope: data constructor `H.PNeg'
    Perhaps you meant `H.PRec' (imported from Language.Haskell.Exts)
```
Caused probably by:
https://github.com/haskell-suite/haskell-src-exts/issues/13

**Comment by JaviSoto** [comment]
Any news on this issue?

**Comment by JaviSoto** [comment]
In case it helps anybody, I fixed this by doing:

```bash
cabal install happy --global
```

**Comment by dwarduk** [comment]
In response to jonasc's comment

> I just removed the PNeg pattern match and was confronted with H.PatBind being given 5 parameters but only expecting 4.
> [...]
> I commented the line, yielding the error, out as a workaround as I got stuck and couldn't figure out easily what to change. I didn't crash with a missing pattern match so I might work for you as a workaround too.

This will work unless you use a qualified pun in a record.

**Comment by dwarduk** [comment]
In response to jonasc's comment

> I just removed the PNeg pattern match and was confronted with H.PatBind being given 5 parameters but only expecting 4.
> [...]
> I commented the line, yielding the error, out as a workaround as I got stuck and couldn't figure out easily what to change. I didn't crash with a missing pattern match so I might work for you as a workaround too.

This will work unless you use a qualified pun in a record: [example in my gists](https://gist.github.com/dwarduk/43f4c0a1789b70e0fe9a)

A pull request that survives that case too is soon incoming :)
