### ISSUE TITLE
Integrate ghcid

### ISSUE THREAD

**Issue by ndmitchell** [SublimeHaskell/SublimeHaskell#175]
It would be great if SublimeHaskell could integrate ghcid for faster rebuilds (or perhaps one of the features already has that? but I couldn't see it), see https://github.com/ndmitchell/ghcid

I'd be happy to modify ghcid to make it easily to integrate, as needed. Please feel free to close/ignore this suggestion if it doesn't seem the right direction for the project.

**Comment by bscottm** [comment]
@ndmitchell: Release 2.0.x uses `ghc-mod` in `legacy-interactive` mode, so I suspect that this could issue can be closed.

**Comment by ndmitchell** [comment]
Thanks, that should be sufficient.
