### ISSUE TITLE
Move to Cabal Sandbox instead of cabal_dev

### ISSUE THREAD

**Issue by crockeea** [SublimeHaskell/SublimeHaskell#183]
Apparently [cabal-dev is outdated](https://github.com/creswick/cabal-dev/issues/114), but it still appears in the settings for SublimeHaskell. cabal-dev cannot be used with the latest GHC. 
Is there support for the newer suggestion, and can the references to cabal-dev be removed?

**Comment by gasi** [comment]
:+1: to renaming `use_cabal_dev` to `use_cabal_sandbox` as I found it confusing :eyes:

**Comment by gasi** [comment]
Oh, I just noticed it’s already changed in `hsdev` branch. Is there documentation on what the plan is for `hsdev`? Will it become mainline? Thanks for all your great work on _SublimeHaskell_ :clap:

**Comment by mvoidex** [comment]
> Is there documentation on what the plan is for `hsdev`?

There's pull request #132. `hsdev` branch is still being tested, but I have not much time for it, any help appreciated

> Will it become mainline?

Yes, I hope :)

**Comment by gasi** [comment]
@mvoidex Thanks for the reply and all your work on _SublimeHaskell_. I have been successfully using `hsdev` recently. Re: time. I absolutely understand — open source is hard. You should reach out to Nadia if you are affected by lack of support in _SublimeHaskell_: https://medium.com/@nayafia/how-i-stumbled-upon-the-internet-s-biggest-blind-spot-b9aa23618c58#.u11dp5fvm

**Comment by mvoidex** [comment]
@gasi, I don't think thas SublimeHaskell is so important tool, but maybe i'm wrong. Anyway, thanks for information!

**Comment by gasi** [comment]
@mvoidex Ha, I’d disagree. You are selling yourself short :smile: I am a beginner Haskell programmer and having your tool at my disposal makes a huge difference in becoming productive and more familiar with the language. If you have a place to accept donations, I’d be happy to pitch in :moneybag:

**Comment by mvoidex** [comment]
Seems, that PayPal doesn't accept donations in Russia, so you can try [Yandex.Money](https://money.yandex.ru/to/410013880421840) (note that sum is in roubles)

**Comment by gasi** [comment]
@mvoidex Thanks, but it looks like my American bank doesn’t allow transfers via Yandex:

<img width="310" alt="yandex_money" src="https://cloud.githubusercontent.com/assets/49583/12526969/d3eb0100-c128-11e5-9417-746ce50af24e.png">

Any chance you could set up [Pledgie](https://pledgie.com/categories/open-source), [GitTip/Gratipay](https://gratipay.com/), or similar? Bummer that this doesn’t work easily.

**Comment by mvoidex** [comment]
Maybe that's because my account wasn't confirmed (i've got confirmation email only today)
Anyway, i'm trying to confirm paypal account, which may take 2-4 working days.

**Comment by mvoidex** [comment]
I've confirmed PayPal account, so you can try this:

[![PayPal][paypal-donate-image]][paypal-donate-link]

[paypal-donate-image]: https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif
[paypal-donate-link]: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=voidex%40live%2ecom&lc=US&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHostedGuest

**Comment by mvoidex** [comment]
@gasi, I've confirmed PayPal account, so you can try this:

[![PayPal][paypal-donate-image]][paypal-donate-link]

[paypal-donate-image]: https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif
[paypal-donate-link]: https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=voidex%40live%2ecom&lc=US&no_note=0&currency_code=USD&bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHostedGuest

**Comment by gasi** [comment]
@mvoidex Great, thanks! Sent you my donation :dollar:

**Comment by mvoidex** [comment]
@gasi, received, thanks
