### ISSUE TITLE
Can not get autocomplete on imported modules

### ISSUE THREAD

**Issue by shaurya0** [SublimeHaskell/SublimeHaskell#194]
I can't seem to get autocomplete to suggest functions from imported packages. E.g. If I write something like this

``` haskell
import Data.Aeson
```
I would expect to get a suggestion for for instance "decode" if i wrote something like "dec" and asked for autocomplete suggestions.

The setup:
* ST3 Build 3065 on Ubuntu 14.04 which is run in a VM from windows.
* Haskell platform which installed GHC 7.6.3
* cabal installed following packages(as well as others):
    * aeson-0.8.0.2
    * haddock-2.13.2.1
    * haskell-src-exts-1.16.0.1
    * hlint-1.9.14
    * ghc-mod-5.2.1.2
* ran into the issue: https://github.com/SublimeHaskell/SublimeHaskell/issues/182 commented by "MoreAxes" so I used the repository from https://github.com/SublimeHaskell/SublimeHaskell/tree/hsdev to install SublimeHaskell

My SublimeHaskell.sublime-settings file:
``` json
{
    "add_to_PATH":
    [
        "/home/shaurya/.cabal/bin",
    ],

    "enable_ghc_mod": true,
}
```

**Comment by mvoidex** [comment]
@shaurya0, if you're using `hsdev` branch, try to `cabal install hsdev` and set `enable_hsdev` to `true`.

**Comment by doubleloop** [comment]
It works but it crashes as hell with the msg:

```
```

**Comment by mvoidex** [comment]
Must be fixed
