### ISSUE TITLE
hsdevtools alternatives?

### ISSUE THREAD

**Issue by NobbZ** [SublimeHaskell/SublimeHaskell#196]
Hi there!

Since `hsdevtools` fails to build on GHC 7.10 (and there wasn't a single commit in the last 2 years) I'm wondering if there are other ways of getting code-completion in `SublimeHaskell`.

Spontaniously `ghc-mod` and `ghc-modi` came to my mind to achieve similar. Is there a way to use one of them? Or are there other alternatives I could use?

**Comment by mvoidex** [comment]
Hi! Until merged, you can use [hsdev branch](https://github.com/SublimeHaskell/SublimeHaskell/tree/hsdev). There are also many improvements and more smart completion. Take a look at [readme](https://github.com/SublimeHaskell/SublimeHaskell/blob/hsdev/README.md)

I'll copy here instruction of how to install branched version of `SublimeHaskell`:

> There's an easier way. Package Control has an "Add Repository" option. Use it to add  https://github.com/SublimeHaskell/SublimeHaskell/tree/hsdev , then install SublimeHaskell with Package Control normally (it probably should not be installed before you do this, so remove it first). Package Control will look in user defined repositories first, so it'll install the hsdev branch.

**Comment by NobbZ** [comment]
hsdev is also not available for GHC 7.10

**Comment by mvoidex** [comment]
What if you disable `hdevtools`? As i remember, `ghc-mod` will be used by default

**Comment by NobbZ** [comment]
Only completion I see is standard word completion by sublime. Not even
imports are completed...
Am 17.01.2015 22:41 schrieb "Alexandr Ruchkin" <notifications@github.com>:

**Comment by mvoidex** [comment]
hsdev merged
