### ISSUE TITLE
TypeError: __exit__() takes exactly 4 arguments (1 given) and other errors

### ISSUE THREAD

**Issue by mrkafk** [SublimeHaskell/SublimeHaskell#197]
Installing current hsdev branch with ST 2 and Python 2.7.8 results in following exceptions displayed in ST 2 console:

1. Lots of exceptions like in subject

2. This error:

	Reloading plugin /home/mark/.config/sublime-text-2/Packages/SublimeHaskell/hsdev.py
	Traceback (most recent call last):
	  File "./sublime_plugin.py", line 62, in reload_plugin
	  File "./hsdev.py", line 424
		def call_callback(fn, *args, name = None, **kwargs):
										^
	SyntaxError: invalid syntax

3. Also in file repl.py, line 45 there's non-ASCII char that makes Python report error on it too.

**Comment by mvoidex** [comment]
they were in utf-8 with bom, fixed

**Comment by mvoidex** [comment]
Please, reopen is not fixed
