### ISSUE TITLE
Right-click library symbol, select Go to declaration

### ISSUE THREAD

**Issue by mrkafk** [SublimeHaskell/SublimeHaskell#200]
Sublime Haskell: hsdev returns error: File '/home/mark/haskell/code_learn/hw.hs' not found, details: {}
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./autocomplete.py", line 1154, in run
TypeError: 'NoneType' object is not iterable

Haskell code:

    import System.Directory
    main = do
        getCurrentDirectory >>= print 
        getHomeDirectory >>= print
        getUserDocumentsDirectory >>= print

**Comment by mrkafk** [comment]
P.S. as usual, it's happening in ST2 with Python 2.7.8

**Comment by mvoidex** [comment]
Reopen if it still fails
