### ISSUE TITLE
hsdev: no autocompletion for type constructors

### ISSUE THREAD

**Issue by doubleloop** [SublimeHaskell/SublimeHaskell#202]
```haskell
data Test a = Foo a | Bar a a | Foobar
```
There is auto-completion on Test but no auto-completion on Foo Bar nor Foobar. Btw, auto-completion on built in like Just and Maybe works fine.

**Comment by mvoidex** [comment]
Fixed with https://github.com/mvoidex/hsdev/commit/0a18396cada84fd152253fc054824b45fa67d152
