### ISSUE TITLE
hsdev: some autocompletions lacking on imported modules

### ISSUE THREAD

**Issue by doubleloop** [SublimeHaskell/SublimeHaskell#205]
2 files (Test.hs, Main.hs), problem in Main.hs

Test.hs:
```haskell
module Test where

data Test = A { problemFun :: Int }

normalFun :: Int -> Int 
normalFun = (1+)

-- here both problemFun and normalFun are autocompleted correctly
```

Main.hs:
```haskell
import Test

-- here normalFun is autocompleted but problemFun is not
```

**Comment by mvoidex** [comment]
> but testFunction is not

Do you mean `problemFun`?

**Comment by doubleloop** [comment]
Yes

**Comment by mvoidex** [comment]
In my case neither `normalFun` nor `problemFun` are completed if `Main.hs` and `Test.hs` not in some cabal project. Thanks for report, I'll fix it soon.

**Comment by mvoidex** [comment]
Please check, must be fixed
