### ISSUE TITLE
Insert Type silently failing

### ISSUE THREAD

**Issue by djrenren** [SublimeHaskell/SublimeHaskell#217]
So I'm not sure exactly what state I'm supposed to be in when I execute the insert type command but I've tried with  the name of the function in the declaration highlighted, nothing selected on the line above the function, and with the "fname ::" part filled out. There is no feedback in the status bar. 

I'm using the hsdev branch with hsdev enabled. "Show Symbol Info" is working and the build is passing on my code. The build is even showing the inferred type as a warning on compile (which is running on save).

The sample function I'm using is:
```haskell
test a = a + 1
```
which has the signature: 
```haskell
forall a. Num a => a -> a
```

Info:
Windows 8.1
Haskell Platform  2014.2.0.0
Sublime Text 3

**Comment by mvoidex** [comment]
Must be fixed
