### ISSUE TITLE
Language pragma auto-completion not working

### ISSUE THREAD

**Issue by cmahon** [SublimeHaskell/SublimeHaskell#222]
I do not get auto-completion prompts for {-# LANGUAGE #-} pragmas by default, however if I enter the following commands in the console, auto-completion works perfectly:

import SublimeHaskell.autocomplete
SublimeHaskell.autocomplete.autocompletion.language_pragmas = SublimeHaskell.autocomplete.get_ghcmod_language_pragmas()

Both enable_ghc_mod and auto_complete_language_pragmas are set to true in my settings.

**Comment by mvoidex** [comment]
Are you using `hsdev` branch?

**Comment by cmahon** [comment]
I'm using the master branch.

**Comment by mvoidex** [comment]
hsdev is merged into master
Reopen issue, if there's still an error
