### ISSUE TITLE
SublimeHaskell: Failed to compile ModuleInspector

### ISSUE THREAD

**Issue by ghost** [SublimeHaskell/SublimeHaskell#224]
When I start up Sublime Text 3 with this plugin. I see this error message : 

SublimeHaskell: Failed to compile ModuleInspector

/home/roelof/.config/sublime-text-3/Packages/SublimeHaskell/ModuleInspector.hs:141:12:
    Not in scope: data constructor ‘H.PNeg’
    Perhaps you meant ‘H.PRec’ (imported from Language.Haskell.Exts)

Roelof

**Comment by FPtje** [comment]
Confirmed. 
http://i.imgur.com/qQPd9IG.png

Looks like it was removed or changed in an update of the module.

**Comment by 0a-** [comment]
The only fix for now seems to be to downgrade haskell-src-exts

**Comment by kolmodin** [comment]
Could we please merge #161? Then we could keep track of the dependencies (without polluting the global package database) and avoid situations like this. SublimeHaskell in its current state is very fragile and having problems like this going unfixed for a few months is a pretty high bar for new users.

**Comment by JGailor** [comment]
:+1:

**Comment by mdtusz** [comment]
Any updates on this? I'm still getting this error on ModuleInspector.

**Comment by Lemmih** [comment]
This is still a problem.

**Comment by ShaneDrury** [comment]
As an interim fix, you can use the `hsdev` branch. See https://github.com/SublimeHaskell/SublimeHaskell/issues/182#issuecomment-94176149

**Comment by mvoidex** [comment]
ModuleInspector removed
