### ISSUE TITLE
(hsdev branch, Windows) "SublimeHaskell: Lint" not working

### ISSUE THREAD

**Issue by tejon** [SublimeHaskell/SublimeHaskell#227]
It says it's linting the file in the status line, then a graphical X is added to the end of that line. No other info is displayed anywhere, and `Sublime Haskell: Auto fix` doesn't fix anything.

Running `hlint` from the commandline works fine, and there are lints in the files I've checked this with. Project building also seems to be fully functional, so I don't think there's a general issue with my installation.

**Comment by mvoidex** [comment]
Are you using hsdev from hackage or from github?

Does your file belong to some project?
If not, try to run `hsdev ghc-mod lint File.hs` in directory of `File.hs`
If yes, run `hsdev ghc-mod lint pathto/File.hs` in directory of `project.cabal`

**Comment by tejon** [comment]
Sorry for slow response... yeah okay, the problem is that hsdev is looking
for hlint in the `bin` of the sandbox where I built it, rather than on the
path.

**Comment by mvoidex** [comment]
> hsdev is looking for hlint in the `bin` of the sandbox where I built it

What do you mean? hsdev uses `ghd-mod`'s `lint` command as library

**Comment by tejon** [comment]
Well then `ghc-mod` is looking for it in the sandbox where I built it. :)

**Comment by mvoidex** [comment]
I thought, that ghc-mod uses as library too :)

**Comment by mvoidex** [comment]
I've updated ](https://github.com/mvoidex/hsdev) to use `hlint` as library. It's not on hackage now, but you can clone it.

**Comment by mvoidex** [comment]
Must be fixed with `hsdev-0.1.4.0`

**Comment by mvoidex** [comment]
Reopen, if it won't work for you

**Comment by tejon** [comment]
Running `hsdev-0.1.4.1` and everything's perfect! :)

**Comment by mvoidex** [comment]
@tejon, can you test if calling `ghc-mod lint pathto/File.hs` also fails?

**Comment by tejon** [comment]
It works, but I did a global install of `ghc-mod` from github, so I'm probably not the best test case anymore.
