### ISSUE TITLE
No autocompletion for packages installed in sandbox

### ISSUE THREAD

**Issue by zakyggaps** [SublimeHaskell/SublimeHaskell#228]
On loading of this plugin, it runs a "ghc-mod list" command to inspect all the visible modules, then do "ghc-mod browse -d" to all of them, parse the results and put them into a database for further usage, e.g. auto completions.

From ghc-mod 3.0.0.0, if "ghc-mod list/browse" commands are run in a cabal project directory, they will show all the visible modules and declarations in the sandbox as well.

However in my situation, the "ghc-mod list/browse" seems to be run with a wrong cwd. I add this line to the funcion "call_ghcmod_and_wait" in file "sublime_haskell_common.py":

        log("{0}, {1}".format(ghc_mod_current_dir, command))

and the log shows that all the "ghc-mod list/browse" commands are executed under user's home directory, not the  project directory:

Sublime Haskell: C:\Users\ZAKY, ['ghc-mod', 'list']
Sublime Haskell: C:\Users\ZAKY, ['ghc-mod', 'browse', '-d', 'Data.Graph.Inductive.Example']
Sublime Haskell: C:\Users\ZAKY, ['ghc-mod', 'browse', '-d', 'Network.HTTP.Cookie']
Sublime Haskell: C:\Users\ZAKY, ['ghc-mod', 'browse', '-d', 'Encoding']
...

After hard coding my project directory into the "call_ghcmod_and_wait" function, I got all the auto completions for modules in the sandbox, so the other parts worked properly.

**Comment by mvoidex** [comment]
I'll close it, because we don't use ghc-mod browse anymore.
