### ISSUE TITLE
add_to_PATH doesn't work on Windows

### ISSUE THREAD

**Issue by danald** [SublimeHaskell/SublimeHaskell#232]
On Windows, `subprocess.Popen` doesn't use doesn't use the PATH in the provided environment to find the executable.

Adding `shell=True` to the `subprocess.Popen` calls in `sublime_haskell_common.py` seems to fix this by having the shell process do the lookup.

**Comment by bscottm** [comment]
@danald: Fixed in current plugin, but not be using `shell=True`.
