### ISSUE TITLE
dont select stack automatically

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#246]
please expose this as a flag, some colleagues of mine use stack, but i dont, this breaks my environment

**Comment by cartazio** [comment]
for the near term I've just hand patched my local install of sublime haskell, but if you'd be open to a PR for this, i'm happy to put some time in next weekend if thats easiest

**Comment by nh2** [comment]
Hey Carter, in general we're happy to accept PRs to turn features off.

**Comment by mvoidex** [comment]
What if someone wants use stack for some projects and not to use for other projects?

We can add flag `"use_stack"`, but if you turn it on, you won't be able to build with stack any projects. How about placing `.no-stack` near `stack.yaml`? We can't detect it and use cabal for such projects.

**Comment by nh2** [comment]
> What if someone wants use stack for some projects and not to use for other projects?

This seems to overlap with the idea of #64, being able to override SublimeHaskell settings per-project using Sublimes `.sublime-project` files.

**Comment by mvoidex** [comment]
I agree, we can support per-project settings

**Comment by cartazio** [comment]
i dont really care about per project personally, i just never use stack and i want that working :)

**Comment by mvoidex** [comment]
@cartazio, do you have `.stack-work` directory in this project? We can also check if it exist in order to use stack
