### ISSUE TITLE
Latest update as of March 04 2015 doesn't show warnings after build runs

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#248]
It looks like the warnings from running a cabal build to completion no longer show up at the end the build. So I have to do a command line cabal build to get them!  

Looks like this change happened pretty recently, though I've not yet dug into teasing apart what's changed. 

This is problematic, because certain ghc code warnings require the full compiler pipeline to trip, rather than Running the type check no code path that's triggered by the the warnings config. 

Either way, this breaks a lot of useful feedback loop for me 😭 :''(

**Comment by cartazio** [comment]
please let me know if theres any additional information i can provide, and thanks for being responsive

**Comment by mvoidex** [comment]
Thanks, i forgot about this case: exit code is 0 and there are some warning in stderr
