### ISSUE TITLE
suport hindent

### ISSUE THREAD

**Issue by leiserfg** [SublimeHaskell/SublimeHaskell#252]
Add support to https://github.com/chrisdone/hindent for auto indent.

**Comment by mvoidex** [comment]
Good idea, thanks

**Comment by bscottm** [comment]
@leiserfg: `hindent` support was merged today. Update your plugin and you should find a `SublimeHaskell: HIndent` command.

**Comment by bscottm** [comment]
@leiserfg: Did the new version of the plugin solve this problem for you?
