### ISSUE TITLE
Completions blow up with TypeError.

### ISSUE THREAD

**Issue by seanparsons** [SublimeHaskell/SublimeHaskell#253]
I've got a recently installed setup and I just get this error when the completions are triggered.

```
Traceback (most recent call last):
  File "/nix/store/pqnskwdlillw2xvd2g5cfcir32v2lw2n-sublimetext3-3083-bin/sublime_plugin.py", line 359, in on_query_completions
    res = callback.on_query_completions(v, prefix, locations)
  File "/home/sean/.config/sublime-text-3/Packages/SublimeHaskell/autocomplete.py", line 1949, in on_query_completions
    autocompletion.get_special_completions(view, prefix, locations))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

**Comment by mvoidex** [comment]
Everytime?
Do you have `hsdev` installed and enabled?

**Comment by seanparsons** [comment]
Yup, no and no. :)

**Comment by mvoidex** [comment]
You have to install it :)
I'll fix readme, hsdev is now used even for completions

**Comment by seanparsons** [comment]
Aha, would it make sense for the plugin to catch that it isn't installed, even if it's to the point of that particular bit of code giving more detail.

**Comment by mvoidex** [comment]
We are already catching it. I've tried to remove `hsdev` and after starting sublime i've got error panel:

    hsdev executable couldn't be found
    check if it's installed and in PATH
    
    hsdev will be disabled, enable it by setting 'enable_hsdev' to true

Will it be better not to set `enable_hsdev` to false automatically, so that sublime will check this everytime (on startup) until user decides to set `enable_hsdev` to false himself?

**Comment by seanparsons** [comment]
What's odd though is that I have

```
"enable_hsdev": false
```

already set in my user config.

**Comment by mvoidex** [comment]
Maybe it was set long time ago?

> Will it be better not to set enable_hsdev to false automatically, so that sublime will check this everytime (on startup) until user decides to set enable_hsdev to false himself?

What do you think? Or maybe you have any suggestions how could we handle it better?

**Comment by seanparsons** [comment]
This laptop was blank about 5 days ago, so it's not likely!

**Comment by mvoidex** [comment]
Functions which need `hsdev` now returns some default value instead of None. This will fix your case.
`enable_hsdev` will no longer be set to false automatically, popup with detailed info will be shown each time on startup if hsdev it not found
