### ISSUE TITLE
SublimeHaskell Keybindings Seem to Interfere with Sublime Defaults

### ISSUE THREAD

**Issue by EarthCitizen** [SublimeHaskell/SublimeHaskell#257]
In default keybindings in Sublime, outside of SublimeHaskell, I can to `ctrl+shift+k` to delete a line then `super+s` to save the change to the file.

With SublimeHaskell, to delete a line I have to hit `ctrl+shift+k` twice before the line deletes, then when I type `super+s` to save, it deletes another line before saving.

**Comment by mvoidex** [comment]
Ok, removed it.
