### ISSUE TITLE
hsdev 0.1.8.2 support

### ISSUE THREAD

**Issue by AlexKovalevych** [SublimeHaskell/SublimeHaskell#261]
Currently it doesnt work with the latest version of hsdev. Tried to install 0.1.7.3 - got error:

```
Could not find module ‘Prelude’\nIt is a member of the hidden package ‘base-4.8.2.0’.\nUse -v to see a list of the files searched for.\n",
```

**Comment by hlawacz** [comment]
SublimeHaskell: hsdev version is incorrect: 0.1.8.2
Required version: >= 0.1.7.0 and < 0.1.8.0
Update it by running 'cabal update' and 'cabal install hsdev'

To supress this message and disable hsdev set 'enable_hsdev' to false

**Comment by AlexKovalevych** [comment]
Did you try it with 0.1.8.2? It doesnt start the server, so i manually increased allowed version

**Comment by hlawacz** [comment]
Yes I did that as well. Seems to work for now, but didnt do any deep testing.

For those that want to try too, I went into Packages/Browse packages, folder SublimeHaskell and edited 
autocomplete.py line 1735 to max_ver = [0,1,9,0] insted of max_ver = [0,1,8,0]

**Comment by AlexKovalevych** [comment]
How can it work if it wont start the server in case version check failed? https://github.com/SublimeHaskell/SublimeHaskell/blob/master/autocomplete.py#L1747

**Comment by hlawacz** [comment]
I hacked [this](https://github.com/SublimeHaskell/SublimeHaskell/blob/master/autocomplete.py#L1735) to make the version allowed and it starts it.

**Comment by hlawacz** [comment]
The real question is why is there upper limit to hsdev < 0.1.8.0 there.
Is it because it is known not to work?
Or just because nobody knows if it works?

**Comment by AlexKovalevych** [comment]
Well, it seems to work on 0.1.8.2, so maybe its a good idea to allow it - so the package will work with a clean install without manipulations.

**Comment by hlawacz** [comment]
Created a pull request :)

**Comment by mvoidex** [comment]
Thanks, fixed in https://github.com/SublimeHaskell/SublimeHaskell/commit/402e7cb043566647da1eb7a0ce5182e1d2395abf

There are minor changes in error format between `1.7.*` and `1.8.*`; I also waited for 1.8.0 to be published on stackage before updating version constraints.
