### ISSUE TITLE
CPU/Energy Impact 100% via plugin_host -> hsdev with 0.2.0.0

### ISSUE THREAD

**Issue by jgornick** [SublimeHaskell/SublimeHaskell#267]
I noticed that after I installed the latest version of SublimeHaskell (2016.05.23) with hsdev 0.2.0.0, it constantly sounded like my MacBook was going to take off due to the fan noise.

I finally found that the `plugin_host -> hsdev` binding was using 100% CPU hence causing the 100% "energy impact".

Any thoughts to why this started happening after the introduction of hsdev 0.2.0.0?

Thanks!

**Comment by mvoidex** [comment]
Do you get 100% everytime and on any project?

Try to delete cache (`Preferences → Browse packages`, remove `SublimeHaskell/hsdev` folder)
Check if `hsdev` itself works well, type this in terminal (close Sublime and ensure hsdev is not running):

    hsdev start
    hsdev scan --cabal
    hsdev scan --path <path-to-haskell-project>
    hsdev stop

**Comment by jgornick** [comment]
@mvoidex Thanks for the tips!

When I run `hsdev scan --path /path/to/project` I get the following error: 
```
{"error":"other error","msg":"<socket: 27>: Data.ByteString.hGetLine: end of file"}
```

Thoughts and again thanks!

**Comment by mvoidex** [comment]
Does this error appear in this case (with no cabal scan)?

    hsdev start
    hsdev scan --path <path-to-project>
    hsdev stop

**Comment by mvoidex** [comment]
@jgornick, i'm not sure, but try setting `enable_hdocs` to `false` in settings (and ensure you've got changes from this commit: https://github.com/SublimeHaskell/SublimeHaskell/commit/c8ef93558e892f458b137a49f854b6efdf515b80)

Does it fix cpu usage?

**Comment by bscottm** [comment]
@jgornick: Closing this old issue. Hopefully solved. If necessary, open a new issue.
