### ISSUE TITLE
Use different `stack.yaml` from default

### ISSUE THREAD

**Issue by mtolly** [SublimeHaskell/SublimeHaskell#269]
I have a multi-package repo, that also has 2 `stack.yaml`s, set up like so:

```
/stack.yaml
/stack-other.yaml
/pkg1/pkg1.cabal
/pkg2/pkg2.cabal
/pkg3/pkg3.cabal
```

When I load up the root directory into Sublime (the one where the `yaml`s are), and save a Haskell file, I get:

```
Sublime Haskell: hsdev check returns error: file not found, file: /Users/mtolly/git/onyxite-customs/haskell/build/stack.yaml, id: 27
```

(the `yaml`s are in `haskell/`, and `build` is the package folder where the `.cabal` file is)

So, I need to tell SublimeHaskell that the `stack.yaml` file is one directory up. Is there a way to do this?

Also, I'd like to be able to switch to build with the other `yaml` file, for the equivalent of `stack build --stack-yaml=stack-other.yaml`.

**Comment by mtolly** [comment]
Huh. Never mind, I just tried again (after installing `ghc-mod` I think?) and it now somehow works and finds the `stack.yaml` okay. So, my only request is for the other feature, using a `stack.yaml` other than the default.

**Comment by mvoidex** [comment]
> after installing `ghc-mod` I think?

Do you have `hsdev` enabled? If yes, then `ghc-mod` is not used

> So, my only request is for the other feature, using a stack.yaml other than the default.

Any suggestions how to implement it?

**Comment by mtolly** [comment]
> Do you have `hsdev` enabled? If yes, then `ghc-mod` is not used

You'd think, but something seems to be very broken in my configuration. I had everything working yesterday (not everything, but it did give me a lint output on save), but then I disabled and reenabled SublimeHaskell, and today, even though this is my user settings:

```
{
  "add_to_PATH": ["/Users/mtolly/.local/bin"],
  "enable_ghc_mod": false,
}
```

and I do have `hsdev` installed and running, it is still trying to run `ghc-mod`. I uninstalled `ghc-mod` and now I get:

```
SublimeHaskell: ghc-mod was not found!
It is used for LANGUAGE and import autocompletions and type inference.
Try adjusting the 'add_to_PATH' setting.
You can also turn this off using the 'enable_ghc_mod' setting.
```

I'm also experiencing #267; `plugin_host` at 100% CPU, even if I open Sublime with no folders open. No idea what it is doing. I'll keep futzing around with it and see if I can come up with a more useful question to ask, since I would really like to get this all working!

> Any suggestions how to implement it?

Hmm, that's tricky. Perhaps you open the alternate yaml file, and then there's a command "SublimeHaskell > Use this stack.yaml" which changes it for that...session? window? Not sure.

It's not a huge deal though, since I could also just move the yaml files around for development (rename the one I want to `stack.yaml`) and then move them back.

**Comment by bscottm** [comment]
@mtolly: Turning this into an enhancement. @xldenis will be responsible for implementation. We'll use Sublime project-specific preferences to specify which `stack.yaml` to use. It's not just your particular use case, but also when developers have multiple `stack.yaml`-es for different resolvers.

**Comment by xldenis** [comment]
> Also, I'd like to be able to switch to build with the other yaml file, for the equivalent of stack build --stack-yaml=stack-other.yaml.

What's your usecase for that? Testing out different GHC versions? Different stack resolvers?

**Comment by mtolly** [comment]
I have a public open-source program, and a private closed-source library that it can optionally use. [I asked the `stack` people](https://github.com/commercialhaskell/stack/issues/2246) if they had advice on how to set this up but eventually hit upon having 2 `stack.yaml` files for the 2 configurations.

[Here](https://github.com/mtolly/onyxite-customs/tree/b5560a2d2d/haskell) is my project folder, with `stack.yaml` (does not use private lib) and `stack-mogg.yaml` (uses private lib). So at the command line I use `stack install --stack-yaml=stack-mogg.yaml` to build on my local machine that has the extra library.

(Also, thanks for pinging this issue again -- it prompted me to try reinstalling SublimeHaskell and seeing if the weird problems I was having were fixed, and indeed they are!)

**Comment by xldenis** [comment]
Cool, I have a commit adding support for custom `stack.yaml`s on a per-project basis, I'll add support for switching between them within the project. It seems like that would fit your usecase 😄

**Comment by JoeShanahanT** [comment]
This sounds like a very useful feature. Is there any movement on this?

**Comment by bscottm** [comment]
@JoeShanahanT: @xldenis did a great job on the initial implementation. I haven't enabled it yet -- been a bit engaged with backend lazy-loading.

**Comment by xldenis** [comment]
👋 I'm back and will start work building on top of this later this week.

**Comment by JoeShanahanT** [comment]
Will there be support our situation?

In our repo we have lots of folders, some of them contain Haskell projects. At the root, we also have a `builds` folder with contains a super-yaml that builds all of our Haskell projects for CI purposes. Our yaml looks like this:

`$REPO_ROOT/builds/product_name.yaml`:

    ...        
    
    packages:
    - ../project-a/
    - ../project-b/
    - ../project-c/
    - ../project-d/
    - ../project-e/
    - ../project-f/
    - ../project-g/
    
    ...

**Comment by xldenis** [comment]
The current implementation allows for a custom yaml path. Future modifications would allow for users to _switch_ the active yaml in sublime. I think that what you need is the ability to specify YAMLs, correct?

**Comment by JoeShanahanT** [comment]
I usually have my sublime set to have the root of the repository open, so I need to be able to set my custom yaml as `./builds/product_name.yaml` and it have it obey locations from the yaml's location. So e.g., SublimeHaskell would find `project-a` with `./builds/../project-a/` (equivalent to just `./project-a/`). Did that make sense?

**Comment by xldenis** [comment]
👍

**Comment by JoeShanahanT** [comment]
Anything I can do to help? :)

**Comment by xldenis** [comment]
I'm sure you can find other issues to debug 😄

**Comment by bscottm** [comment]
@JoeShanahanT, @xldenis: I somewhat wish there were a Wiki where I could keep people updated on SublimeHaskell progress (and I'm sure GH has that functionality somewhere...)

I'm currently putting a few final touches on backend refactoring (aka 'backend lazy-loading') before releasing SublimeHaskell 2.0.0. It's a major change to the code base and will probably cause users some annoying breakage. Once that's done, we (Xavier, mostly) will be in a good place to finally release this long awaited feature.

**Comment by xldenis** [comment]
You can create wikis on github! check in the settings pane.

**Comment by bscottm** [comment]
@xldenis, @mtolly: Xavier's latest patch is integrated into 2.0.0.
