### ISSUE TITLE
hsdev returns error: Could not find module

### ISSUE THREAD

**Issue by rogergl** [SublimeHaskell/SublimeHaskell#270]
My Main.hs  imports the ReservedWords module, both Main.hs and ReservedWords.hs are in the src folder. Working with  ReservedWords.hs causes no problems but working with Main.hs (e.,g. show type) gives:

```
TypeError: 'NoneType' object is not iterable
Sublime Haskell: hsdev types returns error: ghc error, id: 29, msg: Could not find module ‘ReservedWords’
Use -v to see a list of the files searched for.
```

cabal run and test work as expected/

**Comment by bscottm** [comment]
@rogergl: Update `hsdev` and the SublimeHaskell plugin, and retest. This issue should be solved.

**Comment by bscottm** [comment]
Silence is tacit consent. Closing issue. :-)
