### ISSUE TITLE
popUp when mouseOver doesn't work

### ISSUE THREAD

**Issue by ilyakooo0** [SublimeHaskell/SublimeHaskell#273]
it doesn't work on build 3114
should work on everything after 3070. Or am i missing something?

**Comment by mvoidex** [comment]
It should. Make sure other features works, especially 'show symbol info'.
Unfortunately, I won't be able to get to the bottom until 6th august.

**Comment by mvoidex** [comment]
@ilyakooo0, does other features work?

**Comment by jkeuhlen** [comment]
@mvoidex  I'm having the same issue, on build 3114. Everything else seems to work (symbol info, auto complete with type information, etc) but no pop up on hover text. I am on the stable build not dev build, does that matter?

**Comment by mvoidex** [comment]
@ilyakooo0, @jkeuhlen, my bad; as I've found, it will work after 3116 according to https://forum.sublimetext.com/t/dev-build-3116/21148

**Comment by mvoidex** [comment]
Updated in readme: https://github.com/SublimeHaskell/SublimeHaskell/commit/2ec2dd5c7dbfa433f8f1b361d8edd98b0b343423

**Comment by jkeuhlen** [comment]
@mvoidex Great, thanks for the update! Awesome work on this tool by the way.

**Comment by mvoidex** [comment]
@jkeuhlen, thanks :)
