### ISSUE TITLE
Having trouble getting SublimeHaskell to work.

### ISSUE THREAD

**Issue by Kasceh** [SublimeHaskell/SublimeHaskell#275]
I'm trying to use SublimeHaskell but can't seem to get it to work.

My setup is as follows:

Developing on Windows 10 with Sublime 3
Source files are stored on a network drive (really my Ubuntu VM)
I build/test on the VM

I have `hsdev` installed. When I open Sublime with .hs files already open I get this:

```
Sublime Haskell: Starting hsdev server
Sublime Haskell: hsdev ping: no pong
Sublime Haskell: hsdev server started at port 4567
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: connecting to hsdev server (0)...
Sublime Haskell: connected to hsdev server
Sublime Haskell: connected to hsdev server
Package Control: Skipping automatic upgrade, last run at 2016-08-03 10:27:51, next run at 2016-08-03 11:27:51 or after
Exception in thread Thread-36:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\worker.py", line 19, in run
    fn(*args, **kwargs)
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev.py", line 1136, in wrapped
    return fn(*args, **kwargs)
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\autocomplete.py", line 170, in get_completions_async
    current_module = head_of(hsdev.client_back.module(file = file_name))
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\sublime_haskell_common.py", line 137, in head_of
    if len(l) > 0:
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\worker.py", line 21, in run
    log('worker: job {0} fails with {1}'.format(name, e), log_debug)
NameError: global name 'log' is not defined
```

None of the shortcuts that are supposed to work do anything (Control + kh opens Find and Replace). If I right click on a symbol and attempt to show the symbol's info, I get the following:

```
Sublime Haskell: hsdev whois returns error: tool error, msg: can't get paths, tool: stack, id: 9
Sublime Haskell: hsdev lookup returns error: tool error, msg: can't get paths, tool: stack, id: 10
```

Occasionally I also see 

```
Sublime Haskell: hsdev module returns error: module not inspected, module: {'project': None, 'file': 'Z:\\project\\location\\to\\file.hs'}, id: 2
```

How do I go about even diagnosing my issue? A colleague was able to set up it up fine using the same setup.

**Comment by nh2** [comment]
> NameError: global name 'log' is not defined

@mvoidex I think this is a bug: In https://github.com/SublimeHaskell/SublimeHaskell/blob/d4c37e0dc396d096e3ed66a0f2f619120c1e1069/worker.py#L21 `log` is not in scope (it's in `sublime_haskell_common` which is not imported).

> How do I go about even diagnosing my issue?

@Kasceh Once the above is fixed the log will contain more info that can be used to further investigate your problem.

**Comment by Kasceh** [comment]
@nh2 Thanks for the reply!

I've imported that module successfully however I am still experiencing some issues. The Python plug erros have gone, but I'm still getting these printing to the console:
```
Sublime Haskell: hsdev whois returns error: tool error, tool: stack, id: 6, msg: can't get paths
Sublime Haskell: hsdev lookup returns error: tool error, tool: stack, id: 7, msg: can't get paths
Sublime Haskell: hsdev module returns error: module not inspected, id: 2, module: {'file': 'Z:\\project\\master\\haskell-service\\src\\File1.hs', 'project': None}
Sublime Haskell: hsdev module returns error: module not inspected, id: 3, module: {'file': 'Z:\\project\\master\\haskell-service\\src\\File2.hs', 'project': None}
Sublime Haskell: hsdev module returns error: module not inspected, id: 4, module: {'file': 'Z:\\project\\master\\haskell-service\\src\\File2.hs', 'project': None}
```
This happens when I `Right Click -> Show Symbol Info`. Auto-complete is the normal Sublime file based auto-complete too. The code highlighting of the page is changing, but I can't seem to use any features of SublimeHaskell.

**Comment by mvoidex** [comment]
@Kasceh, i'll try to look into it this weekend.

**Comment by Kasceh** [comment]
Thank you, @mvoidex

**Comment by mvoidex** [comment]
sorry, still have no time :(
I believe I could find some this week or next weekend

**Comment by mvoidex** [comment]
@Kasceh, are you using stack?

`hsdev whois returns error: tool error, tool: stack, id: 6, msg: can't get paths`

`hsdev` says, that it can't get stack paths, i.e. fails with `stack path` command for active module

**Comment by Kasceh** [comment]
@mvoidex Apologies for the delay. I do have `stack` on the Window's user and admin/system path, is that what you mean?

**Comment by mvoidex** [comment]
@Kasceh, yes. Try scan file manually and get some info:

    hsdev start
    hsdev scan -f your-file
    hsdev whois some-name-in-file -f your-file

**Comment by Kasceh** [comment]
@mvoidex 

```Z:\project\master\haskell-service\src\Handler\Leave>hsdev scan -f Helper.hs
{"notify":[{"status":"working","progress":null,"name":"Z:\\project\\master\\haskell-service\\project.cabal","task":"scanning","type":"path"}]}
{"notify":[{"status":"ok","progress":null,"name":"Z:\\project\\master\\haskell-service\\project.cabal","task":"scanning","type":"path"}]}
{"notify":[{"status":"working","progress":null,"name":"Z:\\project\\master\\haskell-service\\src\\Handler\\Leave\\Helper.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"ok","progress":null,"name":"Z:\\project\\master\\haskell-service\\src\\Handler\\Leave\\Helper.hs","task":"scanning","type":"module"}]}
[]

Z:\project\master\haskell-service\src\Handler\Leave>hsdev whois requestToJSON -f Helper.hs
{"tool":"stack","error":"tool error","msg":"can't get paths"}```

**Comment by Kasceh** [comment]
I believe the issue is that our project does not keep our `stack.yaml` (it's not even called that) in a standard place. In our dev build environment we use the `STACK_YAML` environment variable to redirect `stack` to use the correct yaml. I attempted to do a symlink to that file to where `hsdev` expects to find it however this leads to the relative paths being incorrect.

**Comment by Kasceh** [comment]
Perhaps this is an issue for https://github.com/mvoidex/hsdev instead?

**Comment by mvoidex** [comment]
@Kasceh, thanks for investigation. Yes, it's hsdev issue

**Comment by bscottm** [comment]
@Kasceh: Most of these problems should be fixed once the latest master is tagged and released. If you're bold enough, I'll get up a branch for you to test on my clone so that you can retest the ST plugin. Let me know.

**Comment by bscottm** [comment]
Silence is tacit consent. Assuming bug is fixed. Closing.
