### ISSUE TITLE
Split Errors, warnings, and hints into individual tabs.

### ISSUE THREAD

**Issue by jkeuhlen** [SublimeHaskell/SublimeHaskell#278]
I'm not sure if this already exists and I'm missing it, but if it doesn't and is within the abilities of Sublime, consider this a feature request! 

I'd like to split the error pane into three tabs: errors, warnings, and hints. This way, I can separate what I want to look at individually. Currently, I may have a large number of warnings that I don't particularly care about or hints that I want to get to later. Sorting these into tabs cleans up the linting and makes it easier to use. 

Alternatively, sorting the error messages according to the way they are listed would make it easier to find error messages. For example, 

![image](https://cloud.githubusercontent.com/assets/10284802/18138155/a2731876-6f68-11e6-9570-9f3a1934d357.png)

I have one error and 27 warnings here. I don't care about the warnings right now, and just want to see the error, but I still have to scroll through all of the warning messages to find the error. If I have hints as well, the order these items show up in the pane is Warnings -> Errors -> Hints so you have to find errors in the middle of the stack of notices which seems less than ideal. 

Is this a bug or a configuration error on my end?

**Comment by mvoidex** [comment]
> Is this a bug or a configuration error on my end? 

No, it's not

Thanks for idea. I agree, mixed errors/warnings/hints are annoying sometimes.

First of all, listing warnings first is definitely a bug, messages must go in this order: errors, warnings, hints.
I could update syntax for output panel to allow folding (like you can fold function body in some lang) errors/warnings/hints, so you can just fold/unfold what you want to see. What do you think?

**Comment by jkeuhlen** [comment]
Folding would be a great option as well. I had the idea for tabs since a coworker uses atom which has that functionality. If sublime doesn't allow tabs there, I think being able to collapse the different sections would be an excellent alternative.

**Comment by mvoidex** [comment]
There are now sections, which can be folded
