### ISSUE TITLE
hsdev version incorrect

### ISSUE THREAD

**Issue by iamrecursion** [SublimeHaskell/SublimeHaskell#279]
Having just installed `SublimeHaskell` via package control, and installed `hsdev` from cabal, I'm seeing the following error when I start sublime:
```
hsdev version is incorrect: 0.2.0.0
required >= 0.1.6.0 and < 0.1.7.0
```
If this is correct, a note should probably be put in the requirements documentation making mention of the constraint.

**Comment by mvoidex** [comment]
Something strange. `SublimeHaskell` [requires `0.2.0.0`](https://github.com/SublimeHaskell/SublimeHaskell/blob/b032ac20cad0d86385bb54ea8365207d0cfda5e7/hsdev.py#L1148).  Compare code in `hsdev.py` file in `SublimeHaskell` with code at link above.

**Comment by iamrecursion** [comment]
Ah, this was very much my bad. Turns out I still had a user channel from ages ago pulling from the hsdev branch on the repo from when that was an option.
