### ISSUE TITLE
Command for stack exec needed to show output.

### ISSUE THREAD

**Issue by karan-ta** [SublimeHaskell/SublimeHaskell#281]
Hi Guys,

Thanks for great plugin.

i use the command SublimeHaskell:Build 
and stack build runs for me.
great.

which command should i use so that 
stack exec "projectname"-exe runs for me and i can see the output in the console ?

Is there a command for stack exec in sublimehaskell ?
If no -please point to documentation or steps to make it.
(I havent read any docs so far.)

**Comment by karan-ta** [comment]
i want to see output in console of sublime text. 
when i do ctrl + B on a haskell file (runghc command is executed )- the output is shown in sublime text console.

but when i do sublime haskell build - i cannot see the output in sublime text console as there is no way to do stack exec from within sublime text through sublime haskell plugin.

**Comment by bscottm** [comment]
@karan-ta: Update the plugin and look for a "SublimeHaskell: Stack Exec" command. Verify that this works for you. My simple test: 'cabal --help'.

Also, there is support for shell-like quoting, if you need to put quotes around arguments.

If this works the way you want it to work, please close the issue.

**Comment by bscottm** [comment]
@karan-ta: I should add -- getting "live" build result output is on my To-Do list. It's a bit more complicated than `stack exec`.

**Comment by bscottm** [comment]
Silence is tacit consent. Closing.
