### ISSUE TITLE
hsdev version

### ISSUE THREAD

**Issue by nitingupta910** [SublimeHaskell/SublimeHaskell#283]
Just installed SublimeHaskell and it complains:

> 
> SublimeHaskell: hsdev version is incorrect: 0.2.1.0
> Required version: >= 0.2.0.0 and < 0.2.1.0
> Update it by running 'cabal update' and 'cabal install hsdev'
> 
> To supress this message and disable hsdev set 'enable_hsdev' to false
> 

The latest hsdev is 0.2.1.0 but not sure how much work is needed for supporting this newer version.

**Comment by mvoidex** [comment]
Fixed
