### ISSUE TITLE
No auto completion of import Yampa

### ISSUE THREAD

**Issue by Jan129** [SublimeHaskell/SublimeHaskell#285]
I use macosx and when I try to import a module e.g. Yampa (which I installed with "stack install Yampa" ) sublimeHaskell can't find it. What do I have to do for importing module FRP.Yampa ?

Thx,
Jan

**Comment by bscottm** [comment]
@Jan129: Can you verify that this is still a problem for you?

**Comment by Jan129** [comment]
@bscottm I use now fedora 25 but I have the same problem. I did install Yampa with "stack install Yampa"
I don't get autocompletion when I type "import Y"

**Comment by bscottm** [comment]
@Jan129: I'll have a look.

**Comment by bscottm** [comment]
@Jan129: Should be fixed in current 2.0.x release (although, don't forget that all of the `Yampa` packages start with `FRP`.) If necessary, open a new issue.
