### ISSUE TITLE
SublimeHaskell: hsdev executable couldn't be found

### ISSUE THREAD

**Issue by scowan1995** [SublimeHaskell/SublimeHaskell#287]
I have installed hsdev using the cabal install command but Sublime doesnt seem to be able to find it. I can run 
```bash
cabal list --installed | grep hsdev
``` 
and see that hsdev is installed with cabal but for some reason SublimeHaskell can't find it. The full error message from Sublimehaskell is

SublimeHaskell: hsdev executable couldn't be found!
It's used in most features of SublimeHaskell
Check if it's installed and in PATH
If it's not installed, run 'cabal install hsdev' to install hsdev
You may also want to adjust 'add_to_PATH' setting

I'm on OS EL Capitan, macbook pro early 2015.

**Comment by Lustres** [comment]
I tried those but still doesn't work
1. Go to `Preferences >> Package Settings >> SublimeHaskell >> Settings - Users`
2. Add my `hsdev` path to `add_to_PATH`

I'm on macOS Sierra, Air early 2014.

**Comment by bscottm** [comment]
Pull the latest commits to `master`, unless a new sub-version of the plugin has been released in the last day (13 FEB). Make sure that you have updated `add_to_PATH` in your user preferences, if necessary. For example, on Mac OS X:

    add_to_PATH = ["$HOME/.local/bin", "$HOME/.cabal/bin"]

Bug should be fixed.

**Comment by bscottm** [comment]
You will have to restart ST if you update your user preferences.

**Comment by bscottm** [comment]
@Lustres, @scowan1995: Can you retest using the latest SublimeHaskell? This bug should be fixed (because I'm also a Mac OS X user, preferentially, and I did actually fix this bug. :-)

**Comment by Lustres** [comment]
Thx, It works. But I did a little change.
Add cabal installed package path to `add_to_PATH` 
you can get the path in file  `~/.cabal/config`
It's `~/Library/Haskell/bin` on my Mac

**Comment by scowan1995** [comment]
Thanks bscottm. It works for me.

**Comment by bscottm** [comment]
@Lustres: I think it might be better if there were a setting to add "well known paths", such as `~/.local/bin` and `~/.cabal/bin` (or whatever happens to be set in `~/.cabal/config`. Would that work for you?

**Comment by bscottm** [comment]
@Lustres, @scowan1995: New option called "add_standard_dirs" added to SublimeHaskell options, pushed onto master branch. Please test and ensure that this is what you expected from the enhancement. Thanks!

**Comment by csumanth98** [comment]
@Lustres 
what should I add to add_to_PATH = [#################]
I'm on Sierra 10.12.4.

**Comment by bscottm** [comment]
@csumanth98: Technically, you shouldn't have to add anything if `add_standard_dirs` is `true` and you installed `hsdev` in `$HOME/.cabal/bin` or `$HOME/.local/bin`.
