### ISSUE TITLE
Syntax highlighting with single-line {-multi--line-} comment

### ISSUE THREAD

**Issue by metaleap** [SublimeHaskell/SublimeHaskell#291]
_Everything_ in a .hs file after a multi-line comment gets color-wise "outcommented" (across all color schemes), using Syntax / SublimeHaskell / Haskell, when the last line of that multi-line comment also contains a `--` anywhere.

This is in ST3 build 3126

Easy to work around but reporting because a bug is a bug  ;)  who knows, maybe it resides in a core function reused by SublimeHaskell in other places etc..

**Comment by bscottm** [comment]
@metaleap: I think I've fixed this issue on my fork's `comment_fix` branch. If you can clone/checkout my fork, would you mind verifying before I issue a pull request?

**Comment by metaleap** [comment]
@bscottm just so you don't sit & wait around uselessly for me --- regrettably i can't right now! hope the maintainer will give your pull-request a try :)

**Comment by mvoidex** [comment]
@metaleap, he is maintainer now :)

**Comment by bscottm** [comment]
@metaleap: Should be fixed in latest push onto master.
