### ISSUE TITLE
Syntax highlighting: not all functions are recognized

### ISSUE THREAD

**Issue by metaleap** [SublimeHaskell/SublimeHaskell#292]
See 2nd one in this screenshot:

![image](https://cloud.githubusercontent.com/assets/22109/21742260/4f7cadd8-d4eb-11e6-9abf-fd6af08e746f.png)

Source located at https://github.com/metaleap/HaXtatic/blob/master/__tmp_nu_/Bloks.hs

The issue isn't helped by adding a full signature-with-types declaration, but it **is** resolved by removing the apparently somehow offending line just above it:

`in (sortedmatches ,  (null sortedmatches) |? Util.dateTime0 |! pagedate $sortedmatches#0 )`

Specifically by replacing the custom operators `|?` and `|!` with a proper `if-then-else` expression.

**More specifically**, only the first operator here causes this and only if this starts with (or simply is) a `|`. Possibly this is wrongly interpreted as a guard pattern starting.

It's syntactically valid and compiles, so looks a parsing issue? This is for Syntax / SublimeHaskell / Haskell. (ST3's built-in Haskell syntax of course doesn't recognize function definitions at all, so still a step up! ;)

**Comment by bscottm** [comment]
@metaleap: ST syntax highlighting is all done via regexps. ST3 is more stateful and flexible. For the time being, SH needs to maintain compatibility with ST2, which limits options.

**Comment by bscottm** [comment]
@metaleap: Might be fixed with my latest push onto master.

**Comment by bscottm** [comment]
@metaleap: I cloned your repo because the link was bad. It does look like this issue is fixed. Although I'm dreading the new issue reports as the result of hacking the syntax regexps.
