### ISSUE TITLE
Disabling SH's built-in Syntaxes

### ISSUE THREAD

**Issue by metaleap** [SublimeHaskell/SublimeHaskell#294]
At the simplest, I suggest SH should respect when a user switches .hs files to a non-SH Syntax. It seems to routinely, autonomously switch back my .hs files to SH's own Haskell syntax and to switch back to my non-SH choice I'd have to manually go to View/Syntax/..

Specifically whatever I choose under "Open all with current extension as..." gets overridden by SH at my end with ST3

**Comment by bscottm** [comment]
@metaleap: Update your plugin. Should have a new setting, `use_improved_syntax`. Set this to `false` in your user settings and SH will no longer impose its shipped syntax on all of your files.
