### ISSUE TITLE
Seeing '?' instead of '::' in type/symbol info 

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#299]
I've installed SublimeHaskell through Package Control and set it to work with hsdev. Everything works fine except that I see a strange `?` instead of `::` when hovering on a type/symbol.
<img width="594" alt="screen shot 2017-02-14 at 8 17 12 am" src="https://cloud.githubusercontent.com/assets/287532/22917645/ac811f9e-f28e-11e6-9e7f-c266a1c9c201.png">

I'd appreciate any ides on how to fix this.

**Comment by mvoidex** [comment]
Set "unicode_symbol_info" to false in settings (maybe this should be default).
You can also try setting "font_options": ["directwrite"] instead (this is not sublimehaskell option, it's common one), if you are on Windows, to enable font substitution

**Comment by moodmosaic** [comment]
Wow. Thank you very much for the prompt reply. Setting `unicode_symbol_info` to `false` in SublimeHaskell settings fixed it!

<img width="595" alt="screen shot 2017-02-14 at 8 55 10 am" src="https://cloud.githubusercontent.com/assets/287532/22918583/9ad82152-f293-11e6-88c9-ebcf91cb3e92.png">

**Comment by moodmosaic** [comment]
Turns out I needed also the `"font_options": ["directwrite"]` one.

**Comment by mvoidex** [comment]
Sry, don't understand, what do you mean? Setting `"font_options": ["directwrite"]` shouldn't be necessary if you disabled unicode. If you still have strange symbols somewhere, then it's a bug

**Comment by moodmosaic** [comment]
`"unicode_symbol_info": false` in SublimeHaskell settings fixes the issue shown in the screenshots above.

---

But then, when you type, you still see this:

<img width="570" alt="screen shot 2017-02-14 at 12 32 12 pm" src="https://cloud.githubusercontent.com/assets/287532/22926690/67b6da8e-f2b6-11e6-9eb1-edd9f28caf39.png">

And to fix that one, you also need `"font_options": ["directwrite"]` in the *User* of Sublime Text.

**Comment by mvoidex** [comment]
Oh, I see. When you have "directwrite" enabled, you won't see broken symbols in popup and symbol info panel, so you can enable "unicode_symbol_info" if you like nice arrows instead `->`.

Disabling "unicode_symbol_info" haven't affected on autocompletion popup since it's cached. It's bug. But sublime restart (or even closing/opening file or updating it, i.e. smth that will drop completion cache) should help.

**Comment by moodmosaic** [comment]
Thank you. Actually, the combination `"font_options": ["directwrite"]` with `"unicode_symbol_info": false` is all I need since I prefer the 'built-in' arrows.

(There might be some small hidden in the combination of these settings though, yeah. [This](https://github.com/SublimeHaskell/SublimeHaskell/issues/299#issuecomment-279678367) is all I tried.)

**Comment by moodmosaic** [comment]
FWIW, the problem still persists. Setting `"font_options": ["directwrite"]` fixes it, but the then the text looks crappy 😕
