### ISSUE TITLE
ST2: SublimeHaskell is hideously broken

### ISSUE THREAD

**Issue by bscottm** [SublimeHaskell/SublimeHaskell#300]
Tried testing SublimeHaskell on ST2 just to ensure that it still works. It doesn't. Among things, the 'html' module is not pre-installed.

I'm willing to go in and attempt to fix. But the better path is probably to drop ST2 support altogether. After all, ST2's Python is a version of 2.6 dated 2010.

**Comment by mvoidex** [comment]
Since there's no issue about broken ST2, i support dropping its support.
@nh2, what do you think?

**Comment by bscottm** [comment]
@nh2, @mvoidex: Trying to fix SublimeHaskell to work with ST2 is pointless. There are so many calls to ST3-specific `sublime` module functions that cannot be fixed.

**Comment by mvoidex** [comment]
As long as we preparing PR to package control to drop ST2 support ([sublime-haskell/drop-st2](https://github.com/SublimeHaskell/package_control_channel/tree/sublime-haskell/drop-st2)), we can also change releasing strategy - https://packagecontrol.io/docs/submitting_a_package#Step_4
Should we?

We can also add labels. I've added only "haskell" for now.

**Comment by bscottm** [comment]
@mvoidex: Totally concur.

**Comment by bscottm** [comment]
@mvoidex: Although, thinking about it, ST2 has been broken ever since you (or @nh2) decided to call  `sublime.cache_path` or use `Phantom`s to highlight text areas. I generally use branches to do development before merging back to `master`. In this instance, might not be entirely necessary.

I do agree that releases should be more disciplined (using tags).

**Comment by jkeuhlen** [comment]
@bscottm This issue should probably be closed since ST2 support was dropped in v1.2.0.

**Comment by bscottm** [comment]
Yeah. I know.
