### ISSUE TITLE
Highlighting Issue with Indented Guards

### ISSUE THREAD

**Issue by dylanmann** [SublimeHaskell/SublimeHaskell#303]
In a function such as the one below, the starred line is not highlighted properly (`insert` is not recognized as a function)

    insert :: (Ord e) => e ->BST e -> BST e
    **insert v t@(N l x r)**
      | v < x     = N (insert v l) x r
      | v > x     = N l x (insert v r)
      | otherwise = t 
    insert v E = N E v E

**Comment by iamrecursion** [comment]
This is likely to be the same issue as #292. As @bscottm mentions there, the current highlighter is regex based due to SublimeHaskell still providing ST2 support (though #300 discusses dropping that requirement).

**Comment by bscottm** [comment]
@dylanmann, @iamrecursion: This one is likely fixable.

**Comment by bscottm** [comment]
@dylanmann, @iamrecursion: Yes, fixed, but the Almighty only knows what I might have just broken by accident.

**Comment by bscottm** [comment]
@dylanmann, @iamrecursion: Should be fixed by latest push onto master.
