### ISSUE TITLE
Support for Unicode filenames?

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#304]
It looks like SublimeHaksell (or rather `hsdev`?) isn't working with filenames like *MaîtreD*, *MaîtreDTests*, etc. At least, [this](https://github.com/ploeh/dependency-rejection-samples/tree/master/Haskell) project doesn't work, but it *does* work in Atom/ide-haskell (which uses `ghc-mod`).

**Comment by mvoidex** [comment]
There's at least ont issue with hsdev I've noticed. I've created standalone file 'Foo∀.hs' and then scanned it with hsdev:

    hsdev start
    hsdev scan --file Foo∀.hs
    hsdev module -f Foo∀.hs  # returns scanned module
    hsdev module -m Foo∀  # same, but select module by its name
    hsdev check -f Foo∀.hs  # checks file, ok

But `hsdev symbol foo` (`foo` defined in `Foo∀.hs`) returns symbol without location set, which is an error.

**Comment by bscottm** [comment]
@moodmosaic: Can you test this with the updated plugin?

**Comment by moodmosaic** [comment]
@bscottm, sure! From which branch should I pull from?

**Comment by bscottm** [comment]
@moodmosaic: Just update your plugin or pull from `master`.

**Comment by moodmosaic** [comment]
Unfortunately, no 😕 This one doesn't work. I'm getting the exact same behavior.

I've just installed SublimeHaskell from Package Control. Here's the output I'm getting:

```
...
plugins loaded
std_places = ['C:\\Users\\Nikos\\AppData\\Roaming\\local\\bin', 'C:\\Users\\Nikos\\AppData\\Roaming\\cabal\\bin']
add_to_PATH = []
Package Control: Skipping automatic upgrade, last run at 2017-03-24 08:35:35, next run at 2017-03-24 09:35:35 or after
Switched syntax to SublimeHaskell's fixed Haskell syntax: C:\Users\Nikos\Documents\dependency-rejection-samples\Haskell\MaîtreDTests.hs
Sublime Haskell: hsdev module returns error: module not inspected, module: {'project': None, 'file': 'C:\\Users\\Nikos\\Documents\\dependency-rejection-samples\\Haskell\\MaîtreDTests.hs'}, id: 3
Sublime Haskell: hsdev check returns error: module not inspected, module: {'project': None, 'file': 'C:\\Users\\Nikos\\Documents\\dependency-rejection-samples\\Haskell\\MaîtreDTests.hs'}, id: 4
Sublime Haskell: hsdev module returns error: module not inspected, module: {'project': None, 'file': 'C:\\Users\\Nikos\\Documents\\dependency-rejection-samples\\Haskell\\MaîtreDTests.hs'}, id: 4
Sublime Haskell: hsdev types returns error: module not inspected, module: {'project': None, 'file': 'C:\\Users\\Nikos\\Documents\\dependency-rejection-samples\\Haskell\\MaîtreDTests.hs'}, id: 6
```

**Comment by bscottm** [comment]
@moodmosaic: The problem lies with `hsdev`, not `SublimeHaskell`'s UTF-8 I/O.

**Comment by moodmosaic** [comment]
Oh, OK, I'll open an issue there then. Thank you.

/cc @mvoidex
