### ISSUE TITLE
build on save no longer works with current release

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#314]
likely fallout of a change included with the fix for https://github.com/SublimeHaskell/SublimeHaskell/issues/308 ?

**Comment by bscottm** [comment]
@cartazio: Yes, probably.

**Comment by bscottm** [comment]
@cartazio: Update, test, repeat. (found something I missed from a previous refactoring effort.)

**Comment by cartazio** [comment]
ok, seems to work now, just have to make a micro twiddle so that sublime thinks theres something to save :)
