### ISSUE TITLE
remote hsdev?

### ISSUE THREAD

**Issue by dabro** [SublimeHaskell/SublimeHaskell#315]
How does one connect to an hsdev running in a container?  eg, if I run `hsdev start --port 8000` in the container, how can I connect from Sublime Text running on host?  The closest config option I see is `"hdevtools_socket"`, but the documentation says hdevtools isn't used if hsdev is.

Second, can I run different hsdev builds in container and host?  eg ghc 8 on host, 7.10.1 on container?

**Comment by bscottm** [comment]
@dabro: There isn't a way today. Marking as an enhancement to be worked off in the near future. 

We'd have to add a couple of new preferences to specify "local" vs. "remote" (local == SublimeHaskell starts `hsdev` vs. remote == SublimeHaskell connect to a remote `hsdev`), and the `hostname:port` where the remote `hsdev` lives.

**Comment by dabro** [comment]
I'm not great with Python, but I could give it a try if you'd point me in the right places in the code.
Obviously can see
```
def start_hsdev(self, start_server=True):

class HsDevAgent(threading.Thread):
...
self.hsdev_process = HsDevProcess(cache=os.path.join(Common.sublime_haskell_cache_path(), 'hsdev'),
                                          log_file=os.path.join(Common.sublime_haskell_cache_path(), 'hsdev', 'hsdev.log'),
log_config=Settings.get_setting_async('hsdev_log_config'))

class HsDevProcess(threading.Thread):
...
self.process = HsDev.create_server(port=self.port,
                                                   cache=self.cache,
                                                   log_file=self.log_file,
log_config=self.log_config)

def create_server(port=4567, cache=None, log_file=None, log_config=None):
```

**Comment by bscottm** [comment]
@dabro: That is the general vicinity of the code needs to be changed. Problems to be solved: (a) user option for local vice remote hsdev [need host + port option as well], (b) use that option to bypass `create_server` and connect to the remote (create the sockets, connect.)

I'm a little behind where I'd like to be -- threw pylint at the codebase and now it's turned into more of a code audit.

**Comment by dabro** [comment]
Right, thanks.  Actually, it was the config mapping from user options to code arguments that I was the most unsure of.  Will see if I can find some time to figure out.

**Comment by bscottm** [comment]
@dabro: Probably best if you clone and work off my `bscottm/SublimeHaskell` repo, in particular, my `master` branch. I haven't merged it with `SublimeHaskell/SublimeHaskell` because it's a big change -- the results of `pylint` code auditing. I'm reasonably confident that the audit result is stable, but testing is needed.

Also, it's in a better state so that either you or I can add this feature. My goal is to separate out how the backends interact and eliminate the `enable_*` options and replace them with a single `backend=<foo>` option, where `foo` is `ghc-mod`, `hsdev`, `hsdev-remote`. It's a larger project milestone that probably doesn't fit with your timeline, but I'll see if I can hack an interim solution.

**Comment by bscottm** [comment]
@dabro: Hacked in remote server support -- you will need to adjust your user settings, in particular `hsdev_host` (hostname), `hsdev_port` (port) and `hsdev_local_process` (set to false).

I haven't merged this into `SublimeHaskell/SublimeHaskell` yet. I need to (a) update the Package Control metadata so that updates happen when the release tag changes, (b) set release tags on `SublimeHaskell/SublimeHaskell`.

That said, the code will appear on my `bscottm/SublimeHaskell` master branch later this evening (Pacific TZ).

**Comment by bscottm** [comment]
@dabro: Also, `hsdev` appears to exit when the last client disconnects. (This is correct, @mvoidex?)

**Comment by mvoidex** [comment]
@bscottm, no. This is true only for client that sent command 'link' and then disconnected.

**Comment by bscottm** [comment]
@mvoidex: So, don't `link` for `hsdev` that wasn't started by SublimeHaskell. Got it.

**Comment by bscottm** [comment]
@dabro: Once PackageControl detects the version number change to 1.2.0, update and test. Close if fixed.

**Comment by dabro** [comment]
Am I doing something wrong?
```
plugins loaded
<hsdev stdout> 09/04/17 16:46:05 -0500	INFO	127.0.0.1:55588> connected
<hsdev stdout> 09/04/17 16:46:05 -0500	INFO	127.0.0.1:55590> connected
<hsdev stderr> hsdev: hsdev: can't find a package database at /home/dev/api/.cabal-sandbox/x86_64-osx-ghc-8.0.2-packages.conf.d<hsdev stdout> 09/04/17 16:46:05 -0500	ERROR	127.0.0.1:55590/req/1/update/task/project> Scope leaves with exception: hsdev: can't find a package database at /home/dev/api/.cabal-sandbox/x86_64-osx-ghc-8.0.2-packages.conf.d
<hsdev stdout> 09/04/17 16:46:05 -0500	ERROR	127.0.0.1:55590/req/1/update/task> Scope leaves with exception: hsdev: can't find a package database at /home/dev/api/.cabal-sandbox/x86_64-osx-ghc-8.0.2-packages.conf.d
```
and so on.

`SublimeHaskell.sublime-settings--User`
```
{
  "add_to_PATH": ["$HOME/.local/bin"],
	"enable_hdevtools": false,
   // Remote hsdev is on the "my_hsdev_host.domain.net" machine
  "hsdev_host": "localhost",
  // Remote hsdev listens to port 4096 for connections (default: 4567)
  "hsdev_port": 4096,
  // SublimeHaskell will not start or manage its own hsdev backend process
  "hsdev_local_process": false
}
```

**Comment by dabro** [comment]
OK, I overrode the settings in the default SublimeHaskell.sublime-settings (didn't know you could do that):
```
 // ~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=
  // Backend selection:
  // ~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=~=

	// Enable hsdev: This is the preferred backend
	"enable_hsdev": true,

	// Default host and port to which SublimeHaskell connects, where the hsdev server operates:
	"hsdev_host": "localhost",
	"hsdev_port": 4096,

	// Start a local hsdev server process?
	"hsdev_local_process": false,

	// Enables hdevtools (it must be installed, cabal install hdevtools)
	// See the add_to_PATH settings to specify a custom location.
	"enable_hdevtools": true,

	// hdevtools socket name or default
	"hdevtools_socket": "",
```
Seem to be having trouble connecting to hsdev server, which might be an issue with my docker setup.  I'll troubleshoot
```
Sublime Haskell: listen: connection to hsdev lost: [Errno 54] Connection reset by peer
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/Users/browneej/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/client.py", line 220, in listen
    resp = json.loads(self.get_response())
  File "/Users/browneej/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/client.py", line 244, in get_response
    self.part = self.part + self.socket.recv(65536).decode('utf-8')
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/browneej/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/client.py", line 239, in listen
    self.connection_lost('listen', sys.exc_info()[1])
  File "/Users/browneej/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/client.py", line 151, in connection_lost
    HsCallback.call_callback(self.on_disconnected, name='HsDev.on_disconnected')
  File "/Users/browneej/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/callback.py", line 11, in call_callback
    callback_fn(*args, **kwargs)
TypeError: null_func() missing 1 required positional argument: 'self'

Package Control: No updated packages
```

**Comment by bscottm** [comment]
@dabro: You should change your SublimeHaskell user settings (you can change the default settings, but they'll get overwritten on the next plugin upgrade.) But, yes, you can override settings and you're supposed to override them.

The `null_func` error is an error. Will fix and push an update to 1.2.1.

BTW: `hsdev start --port 4096` is how I test. So, the problem may be with your Docker config.

**Comment by bscottm** [comment]
@dabro: Can I close this issue?

**Comment by dabro** [comment]
Yes.
