### ISSUE TITLE
Add import broken

### ISSUE THREAD

**Issue by tobia** [SublimeHaskell/SublimeHaskell#321]
I just tried "Add import" but it failed with this error:
```
  ...
  File "/home/tobia/.config/sublime-text-3/Packages/SublimeHaskell/commands.py", line 636, in add_import
    contents_part = contents[0: list(re.finditer('^import.*$', contents, re.MULTILINE))[-1].end()]
NameError: global name 're' is not defined
```
So I added `import re` on top of that file and then it failed with this:
```
  ...
  File "/home/tobia/.config/sublime-text-3/Packages/SublimeHaskell/internals/proc_helper.py", line 281, in invoke_tool
    return mk_result(io.TextIOWrapper(stdout, encoding='utf-8'))
AttributeError: 'str' object has no attribute 'readable'
```
It seems `stdout` is a string, so I changed both occurrences of `io.TextIOWrapper(stdout, encoding='utf-8')` at lines 278 and 281 into `io.StringIO(stdout)` and finally it worked.

*(Damn duck-typing languages! What if it's **not** a duck? What then!?)*

I'm not submitting a PR because I haven't read all the code in this plugin and I wouldn't want to submit a partial fix, or worse, break code for other Python versions.

I'm using Sublime Text 3126 on Linux Mint 18 x64, with hsdev 0.2.2.1 on resolver lts-8.6. My Sublime has this builtin Python:
```
>>> sys.version
'3.3.6 (default, Sep 22 2016, 23:41:32) \n[GCC 4.6.3]'
```

**Comment by bscottm** [comment]
@tobia: Thanks for reporting this. I'll look into it.

**Comment by bscottm** [comment]
@tobia: SBF when PackageControl detects the version number change to 1.2.0. When it does change, please update and close if fixed.

**Comment by bscottm** [comment]
@tobia: Good, bad, ugly or indifferent? Fixed?

**Comment by bscottm** [comment]
@tobia: Closing. Feel free to reopen if needed.
