### ISSUE TITLE
Show type works seldomly

### ISSUE THREAD

**Issue by JonathanGallagher** [SublimeHaskell/SublimeHaskell#323]
I have a simple file 
With the contents 
`module Main where

import TestImport -- the symbol fg x = x + 1 is imported

main :: IO ()
main = do
    let x = 5
    a <- f x
    print a

f :: Int -> IO Int
f 0 = return 1
f n = do
    m <- f (n-1)
    return $ n * (fg m)
`
In Sublime Haskell, hover shows types, and I can do Ctrl+T,s and get a pop-up with type information.
So all is great.  Then I tried opening a slightly more complicated file, though, still not in a Cabal nor Stack project.  Hovering still works, half the time, though sometimes, I get :: ? coming up. 

So I opened the Sublime console, and tried to get the type in this file, and what I got is:
    

>  Traceback (most recent call last):
>   File "/opt/sublime_text_3/sublime_plugin.py", line 818, in run_
>     return self.run(edit)
>   File "/home/jdgallag/.config/sublime-text-3/Packages/SublimeHaskell/types.py", line 220, in run
>     result = self.get_types(filename, int(line) if line else None, int(column) if column else None)
>   File "/home/jdgallag/.config/sublime-text-3/Packages/SublimeHaskell/types.py", line 237, in get_types
>     return get_type(self.view, filename, module_name, line, column)
>   File "/home/jdgallag/.config/sublime-text-3/Packages/SublimeHaskell/types.py", line 170, in get_type
>     list(filter(lambda t: t.region(view).contains(pt), ts)),
> TypeError: 'NoneType' object is not iterable
> Sublime Haskell: hsdev types returns error: ghc error, id: 29, msg: attempting to use module ‘ErrM’ (./ErrM.hs) which is not loaded
> attempting to use module ‘PrintCartesian’ (./PrintCartesian.hs) which is not loaded
> attempting to use module ‘ParCartesian’ (./ParCartesian.hs) which is not loaded
> attempting to use module ‘AbsToSyntax’ (./AbsToSyntax.hs) which is not loaded
> attempting to use module ‘Printer’ (./Printer.hs) which is not loaded
> 

So it seems that some modules are not being loaded.  But in my basic test above, imports are handled fine.  Any ideas of what I could look for?

**Comment by bscottm** [comment]
@JonathanGallagher: Do you have multiple GHC-es installed? If so, which version compiled `hsdev` and which version compiled `ErrM.hs`?

Admittedly, `SublimeHaskell` should not generate that traceback, so I can fix that.

**Comment by bscottm** [comment]
@JonathanGallagher: The traceback is fixed in the current version, 1.2.0. The `hsdev` types error is admittedly a `hsdev` issue.

**Comment by bscottm** [comment]
@JonathanGallagher: Can you test with the latest on Package Control (1.2.1)?

**Comment by JonathanGallagher** [comment]
Sure, thank you! I will update tomorrow, and let you know how it goes.

**Comment by JonathanGallagher** [comment]
Okay.  I updated everything.  I'm not exactly sure what is going on, but
the show type now works, provided every top-level symbol has its type
explicitly declared.  hsdev, seems to be reporting "None" for the type of
top-level symbols without explicit type declarations.  Is this expected
behaviour?

**Comment by JonathanGallagher** [comment]
Another strange thing, that is happening:

I have command line options to the a program:

case args of
   [] -> printBackTerm
   ["unify"] -> unifyInteractive
   ... etc

There is also a library function, named unify, elsewhere in the package.
When I hover over that string "unify", I get the type of the function unify.
Is this potentially an hsdev bug?

**Comment by mvoidex** [comment]
@JonathanGallagher, yes, it's known bug
anyway, you can create issue on hsdev

**Comment by bscottm** [comment]
@JonathanGallagher: This should be fixed in the 2.0.x release. Can you confirm?

**Comment by bscottm** [comment]
@JonathanGallagher: Closing this issue. If necessary, open a new issue.
