### ISSUE TITLE
Fails to load interface for packages included in cabal file

### ISSUE THREAD

**Issue by jkeuhlen** [SublimeHaskell/SublimeHaskell#324]
When I manually run `SublimeHaskell: Check`, this is the output I receive: 

> Errors: 1, Warnings: 0, Hints: 0
> 
> Errors: 1
> 
>   C:\Users\Jake\workspace\helloworld\src\Lib.hs: line 6, column 1:
>     Error: Failed to load interface for `Data.Text'
>   Perhaps you meant
>     Data.Set (needs flag -package-key containers-0.5.7.1)
>   Use -v to see a list of the files searched for.

And the relevant message on the console: 

> Sublime Haskell: hsdev types returns error: ghc error, msg: Failed to load interface for `Data.Text'
> Perhaps you meant
>   Data.Set (needs flag -package-key containers-0.5.7.1)
> Use -v to see a list of the files searched for.
> , id: 95

I do have `text` included in my cabal file: 

```
library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4.7 && < 5
                     , text
  default-language:    Haskell2010
```

And my code is incredibly simple to reproduce: 
```
module Lib
    ( someFunc
    , myFunction
    , myFunctionT
    ) where

import Data.Text(Text)

someFunc :: IO ()
someFunc = putStrLn "someFunc"

-- | My function takes a string and gives it back to you 
myFunction :: String -> String 
myFunction = id

-- | My function T takes a Text and gives it back to you 
myFunctionT :: Text -> Text
myFunctionT = id
```
I'm running the most recent version of SublimeHaskell and hsdev: 

```
$ hsdev version
0.2.2.2
```

**Comment by bscottm** [comment]
@jkeuhlen: Just to ask the obvious question, but did you 'configure'?

**Comment by jkeuhlen** [comment]
@bscottm Yup, I've tried multiple things. Can't get SublimeHaskell to work on any of my projects unfortunately. I'm happy to try any suggestions you may have.

**Comment by jkeuhlen** [comment]
@bscottm I can build with stack inside the project, but when I run `hsdev` from the command line to try and find out something about a file the following happens:

> $ hsdev whois myFunction -f src/Lib.hs
> {"error":"other error","msg":"File 'C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs' not found"}

But that file definitely exists. Could I be having some kind of permissions problem?

**Comment by mvoidex** [comment]
@jkeuhlen it means that file is not scanned, i should make error message more clear

**Comment by mvoidex** [comment]
close `SublimeHaskell` and ensure there's no `hsdev` process
try this from `C:\Users\Jake\workspace\helloworld`

    hsdev start
    hsdev scan --project .
    hsdev modules --src

Is there any errors during `scan`?

**Comment by jkeuhlen** [comment]
@mvoidex  Here's what I did: 

- All Sublime windows closed 
- Kill hsdev 
- Run the commands you gave me:
```
$ hsdev start
Server started at port 4567

$ hsdev scan --project .
{"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"}]}
{"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\","task":"scanning","type":"path"}]}
{"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\","task":"scanning","type":"path"}]}
{"notify":[{"status":"working","progress":{"current":1,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","task":"scanning","type":"path"}]}
{"notify":[{"status":"working","progress":{"current":1,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","task":"scanning","type":"path"}]}
{"notify":[{"status":"working","progress":{"current":2,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"working","progress":{"current":2,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"working","progress":{"current":3,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"working","progress":{"current":3,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"working","progress":{"current":4,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\test\\Spec.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"working","progress":{"current":4,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\test\\Spec.hs","task":"scanning","type":"module"}]}
{"notify":[{"status":"ok","progress":null,"name":"helloworld","task":"scanning","type":"project"}]}
[]

$ hsdev modules --src
[{"location":{"project":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","file":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs"},"name":"Main"},{"location":{"project":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","file":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs"},"name":"Lib"}]
```
- opened up Sublime
- Ran SublimeHaskell: Check 
- Got the same error output:
```
  C:\Users\Jake\workspace\helloworld\src\Lib.hs: line 7, column 1:
    Error: Failed to load interface for `Data.Text'
  Perhaps you meant
    Data.Set (needs flag -package-key containers-0.5.7.1)
  Use -v to see a list of the files searched for.
```


When I looked back through the `hsdev` log I did find the following exception: 
```
Sublime Haskell: connecting to hsdev server (attempt 0)...
Sublime Haskell: drop prepared completions
Exception in thread Thread-5:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "C:\Users\Jake\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev\agent.py", line 323, in run
    if Settings.PLUGIN.enable_hsdev and not self.client.ping():
  File "C:\Users\Jake\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev\decorators.py", line 99, in wrapped
    , timeout=timeout_arg)
  File "C:\Users\Jake\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev\client.py", line 170, in call
    if not self.verify_connected():
  File "C:\Users\Jake\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev\client.py", line 143, in verify_connected
    self.connection_lost('verify_connected', 'no connection')
  File "C:\Users\Jake\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev\client.py", line 149, in connection_lost
    self.close()
  File "C:\Users\Jake\AppData\Roaming\Sublime Text 3\Packages\SublimeHaskell\hsdev\client.py", line 107, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

If there's anything I can do to help debug this problem, please let me know. I've had several other problems as well that I can enumerate if it helps with debugging.

**Comment by bscottm** [comment]
@jkeuhlen: You shouldn't get that traceback -- not sure how you got that code (because that's been fixed for a while.) What version of SublimeHaskell does PackageControl say you have installed? If it's 1.2.0, would you mind uninstalling it, restarting Sublime, and then reinstall SublimeHaskell?

**Comment by jkeuhlen** [comment]
@bscottm, I am on v1.2.0 and I actually did an uninstall-reinstall earlier today before I posted that message.

**Comment by bscottm** [comment]
@jkeuhlen: Sounds like 1.2.1 needs to be released soon. I'll look into the traceback.

**Comment by bscottm** [comment]
@jkeuhlen: Pushed out out 1.2.1, waiting for PackageControl to detect the version change.

**Comment by jkeuhlen** [comment]
@bscottm @mvoidex : I just updated to SublimeHaskell v1.2.1 and `hsdev` v0.2.3.1 and followed the same procedure I outlined earlier. I'm still getting the same "Failed to load interface for `Data.Text`..." error message.  Here is the full output from Sublime startup to the check failure: 

> Sublime Haskell: starting agent
> Sublime Haskell: std_places = ['C:\\Users\\Jake\\AppData\\Roaming\\local\\bin', 'C:\\Users\\Jake\\AppData\\Roaming\\cabal\\bin']
> Sublime Haskell: add_to_PATH = []
> Sublime Haskell: hsdev command: ['hsdev', 'run', '--port', '4567', '--cache', 'C:\\Users\\Jake\\AppData\\Local\\Sublime Text 3\\Cache\\SublimeHaskell\\hsdev', '--log', 'C:\\Users\\Jake\\AppData\\Local\\Sublime Text 3\\Cache\\SublimeHaskell\\hsdev\\hsdev.log', '--log-config', 'use default']Sublime Haskell: hsdev ping: no pong
> 
> Sublime Haskell: Starting hsdev server
> Sublime Haskell: hsdev initial output: 13/04/17 09:49:47 -0600	INFO	> Log politics: low = Info, high = Warning
> Sublime Haskell: hsdev initial output: 13/04/17 09:49:47 -0600	INFO	hsdev> Server started at port 4567
> Sublime Haskell: hsdev server started at port 4567
> Sublime Haskell: hsdev process started
> Sublime Haskell: connecting to hsdev server (attempt 0)...
> Sublime Haskell: connected to hsdev server
> Sublime Haskell: hsdev agent: primary connection to hsdev established
> Sublime Haskell: hsdev link with {'hold': False}
> Sublime Haskell: hsdev link: 0.0007828413127474372 seconds
> Sublime Haskell: connecting to hsdev server (attempt 0)...
> Package Control: Skipping automatic upgrade, last run at 2017-04-13 09:00:03, next run at 2017-04-13 10:00:03 or after
> Sublime Haskell: connected to hsdev server
> Sublime Haskell: hsdev agent: async connection to hsdev established
> Sublime Haskell: hsdev ping with {}
> Sublime Haskell: hsdev ping: 0.0007063300044694021 seconds
> Sublime Haskell: hsdev scan with {'cabal': False, 'ghc-opts': [], 'docs': True, 'sandboxes': [], 'projects': ['C:\\Users\\Jake\\workspace\\helloworld'], 'infer': False, 'paths': ['C:\\Users\\Jake\\workspace\\helloworld'], 'files': []}
> Sublime Haskell: preparing completions for C:\Users\Jake\workspace\helloworld\src\Lib.hs
> Sublime Haskell: hsdev module with {'filters': [{'file': 'C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs'}], 'query': {'type': 'prefix', 'input': ''}}
> Sublime Haskell: hsdev module: 0.0011136127613404767 seconds
> Sublime Haskell: hsdev complete with {'file': 'C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs', 'prefix': '', 'wide': False}
> Sublime Haskell: hsdev complete: 0.4390568768270562 seconds
> Sublime Haskell: completions: 6
> Sublime Haskell: hsdev scan: 15.208274977909692 seconds
> Sublime Haskell: hsdev docs with {'projects': [], 'modules': [], 'files': ['C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs']}
> Sublime Haskell: hsdev scan with {'cabal': True, 'ghc-opts': [], 'docs': True, 'sandboxes': [], 'projects': [], 'infer': False, 'paths': [], 'files': []}
> Sublime Haskell: Invoking 'check' command via hsdev
> Sublime Haskell: hsdev check with {'ghc-opts': [], 'files': [{'file': 'C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs', 'contents': None}]}
> Sublime Haskell: hsdev check: 0.8297320144774325 seconds
> Sublime Haskell: hsdev autofix show with {'messages': [{'level': 'error', 'region': {'from': {'line': 7, 'column': 1}, 'to': {'line': 7, 'column': 24}}, 'source': {'file': 'C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs', 'project': None}, 'note': {'suggestion': None, 'message': "Failed to load interface for `Data.Text'\nPerhaps you meant\n  Data.Set (needs flag -package-key containers-0.5.7.1)\nUse -v to see a list of the files searched for."}}]}
> Sublime Haskell: hsdev autofix show: 0.9999836713671364 seconds
> Sublime Haskell: total time to mark 1 diagnostics: 0.0005108529424653341 seconds


I'm not sure if it's related or not, but the advanced syntax highlighting also hasn't been working. Nor has the Haddock functionality shown in the README for getting function descriptions from hover-over types:

![image](https://cloud.githubusercontent.com/assets/10284802/25013048/810a5596-202f-11e7-8c3d-54bdb2fea256.png)


If I startup SublimeHaskell without first starting `hsdev` on the command line, I get the following error messages in the console: 

> Sublime Haskell: hsdev scan with {'cabal': False, 'sandboxes': [], 'projects': ['C:\\Users\\Jake\\workspace\\helloworld'], 'infer': False, 'paths': ['C:\\Users\\Jake\\workspace\\helloworld'], 'files': [], 'docs': True, 'ghc-opts': []}
> <hsdev stdout> 13/04/17 09:57:46 -0600	ERROR	<socket: 536>/<socket: 536>/1/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from C:\Users\Jake\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev\cabal\C.Users.Jake.workspace.helloworld.stackwork.install.644d4c9a.pkgdb.json
> <hsdev stdout> 13/04/17 09:57:47 -0600	ERROR	<socket: 536>/<socket: 536>/1/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from C:\Users\Jake\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev\cabal\C.Users.Jake.AppData.Roaming.stack.snapshots.7dea0ad6.pkgdb.json
> <hsdev stdout> 13/04/17 09:57:49 -0600	ERROR	<socket: 536>/<socket: 536>/1/update/task/directory/task/package-db/scan> Error reading cache: Error in $: not enough input
> <hsdev stdout> 13/04/17 09:58:01 -0600	INFO	<socket: 536>/<socket: 536>/1/update> writing cache to C:\Users\Jake\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev
> <hsdev stdout> 13/04/17 09:58:05 -0600	INFO	<socket: 536>/<socket: 536>/1/update> cache saved to C:\Users\Jake\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev
> Sublime Haskell: hsdev scan: 20.698539380463675 seconds
> Sublime Haskell: hsdev scan with {'cabal': True, 'sandboxes': [], 'projects': [], 'infer': False, 'paths': [], 'files': [], 'docs': True, 'ghc-opts': []}Sublime Haskell: hsdev docs with {'modules': [], 'files': ['C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs'], 'projects': []}
> 
> <hsdev stdout> 13/04/17 09:58:05 -0600	TRACE	<socket: 536>/<socket: 536>/2/update/task/docs> Scanning docs for C:\Users\Jake\workspace\helloworld\src\Lib.hs
> <hsdev stdout> 13/04/17 09:58:06 -0600	ERROR	<socket: 536>/<socket: 536>/2/update/task/docs> Scope leaves with exception: <command line>: cannot satisfy -package helloworld
> <hsdev stdout>     (use -v for more information)
> <hsdev stdout> 13/04/17 09:58:06 -0600	ERROR	<socket: 536>/<socket: 536>/2/update/task> Scope leaves with exception: <command line>: cannot satisfy -package helloworld
> <hsdev stdout>     (use -v for more information)
> <hsdev stdout> 13/04/17 09:58:06 -0600	ERROR	<socket: 536>/<socket: 536>/2/update> Scope leaves with exception: <command line>: cannot satisfy -package helloworld
> <hsdev stdout>     (use -v for more information)
> <hsdev stdout> 13/04/17 09:58:05 -0600	TRACE	<socket: 536>/<socket: 536>/2> <socket: 536> >> {"command":"docs","modules":[],"files":["C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs"],"projects":[]}
> <hsdev stdout> 13/04/17 09:58:06 -0600	ERROR	<socket: 536>/<socket: 536>/2> Scope leaves with exception: <command line>: cannot satisfy -package helloworld
> <hsdev stdout>     (use -v for more information)
> <hsdev stdout> 13/04/17 09:57:44 -0600	TRACE	<socket: 536>/<socket: 536>>  => {"cabal":false,"sandboxes":[],"id":"1","projects":["C:\\Users\\Jake\\workspace\\helloworld"],"infer":false,"no-file":true,"paths":["C:\\Users\\Jake\\workspace\\helloworld"],"command":"scan","files":[],"docs":true,"ghc-opts":[]}
> <hsdev stdout> 13/04/17 09:58:05 -0600	TRACE	<socket: 536>/<socket: 536>>  => {"command":"docs","files":["C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs"],"modules":[],"projects":[],"id":"2","no-file":true}
> <hsdev stdout> 13/04/17 09:58:06 -0600	ERROR	<socket: 536>/<socket: 536>> Scope leaves with exception: <command line>: cannot satisfy -package helloworld
> Sublime Haskell: listen: connection to hsdev lost: [WinError 10054] An existing connection was forcibly closed by the remote host
> <hsdev stdout>     (use -v for more information)
> <hsdev stdout> 13/04/17 09:58:06 -0600	INFO	<socket: 536>> <socket: 536> disconnected
> <hsdev stdout> 13/04/17 09:58:06 -0600	ERROR	<socket: 536>> Scope leaves with exception: <command line>: cannot satisfy -package helloworld
> <hsdev stdout>     (use -v for more information)

**Comment by bscottm** [comment]
@jkeuhlen: At this point, SublimeHaskell appears to operate as intended -- no tracebacks, talks to `hsdev` properly. I would have to defer to @mvoidex to interpret the `hsdev` log.

**Comment by bscottm** [comment]
@jkeuhlen: Just for clarity, does "advanced syntax highlighting" mean "doesn't show my Haddock documentation when I hover over a symbol"? Or is there something broken with syntax highlighting?

If the former, that's a `hsdev` issue -- SublimeHaskell avoids parsing buffers because it really is difficult to parse the buffer because Haskell's layout makes it difficult.

If the latter, syntax highlighting is a known issue -- I'd really like to get the backend management unified first before trying to slay the ST3 syntax highlighting issue.

**Comment by jkeuhlen** [comment]
@bscottm Both of those things are true, I wasn't sure if they could be related issues so I wanted to throw them out here if it helped for debugging. In the example image above, I would have expected to have the line "My function T takes a Text..." as an explanation under the hover-over-type.  

For syntax highlighting, I'm using the SublimeHaskell-> Haskell syntax choice in Sublime and I expected it be something like the images in the readme (it used to be, but broke a few months back). Instead, my syntax highlighting looks like the following: 

![image](https://cloud.githubusercontent.com/assets/10284802/25048828/d0780426-20fb-11e7-91d0-0a0f15a444e9.png)

This is a rather simple example, but it get's worse in more complex code. There were other open issues for syntax highlighting so I never reported it. 

@mvoidex : Would you like me to open this issue over on `hsdev` if you think it's an issue over there instead?

**Comment by mvoidex** [comment]
@jkeuhlen i'm not sure it's hsdev's issue
could you try a bit more (as before, ensure no hsdev is running):

    hsdev start
    hsdev scan --project .
    hsdev check -f .\src\Lib.hs
    hsdev types -f .\src\Lib.hs
    hsdev whois myFunction -f .\src\Lib.hs

**Comment by bscottm** [comment]
@jkeuhlen: If I were to prioritize things, I'd really like to get the backend work done first before attacking syntax highlighting. That said, though, syntax highlighting would close out more issues... See what I can do.

**Comment by jkeuhlen** [comment]
@mvoidex : Here is the full output from running those commands. 
> $ hsdev start
> Server started at port 4567
> 
> $ hsdev scan --project .
> {"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"}]}
> {"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":{"current":1,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":{"current":1,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":{"current":2,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":2,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":3,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":3,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":4,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\test\\Spec.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":4,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\test\\Spec.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"ok","progress":null,"name":"helloworld","task":"scanning","type":"project"}]}
> []
> 
> $ hsdev check -f .\\src\\Lib.hs
> [{"note":{"suggestion":null,"message":"Failed to load interface for `Data.Text'\nPerhaps you meant\n  Data.Set (needs flag -package-key containers-0.5.7.1)\nUse -v to see a list of the files searched for."},"source":{"project":null,"file":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs"},"region":{"to":{"line":7,"column":24},"from":{"line":7,"column":1}},"level":"error"}]
> 
> $ hsdev types -f .\\src\\Lib.hs
> {"error":"ghc error","msg":"Failed to load interface for `Data.Text'\nPerhaps you meant\n  Data.Set (needs flag -package-key containers-0.5.7.1)\nUse -v to see a list of the files searched for.\n"}
> 
> $ hsdev whois myFunction -f .\\src\\Lib.hs
> [{"imported":[{"qualified":false,"name":"Lib"}],"pos":{"line":13,"column":1},"name":"myFunction","decl":{"what":"function","type":"String -> String"},"defined":{"location":{"project":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","file":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs"},"name":"Lib"}}]
> 
> $ hsdev stop
> []
> 
> $ hsdev start
> Server started at port 4567
> 
> $ hsdev scan --project . --docs
> {"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"}]}
> {"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":null,"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":{"current":1,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":{"current":1,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\helloworld.cabal","task":"scanning","type":"path"}]}
> {"notify":[{"status":"working","progress":{"current":2,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":2,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\app\\Main.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":3,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":3,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\src\\Lib.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":4,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"working","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\test\\Spec.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"working","progress":{"current":4,"total":4},"name":"helloworld","task":"scanning","type":"project"},{"status":"ok","progress":null,"name":"C:\\Users\\Jake\\workspace\\helloworld\\test\\Spec.hs","task":"scanning","type":"module"}]}
> {"notify":[{"status":"ok","progress":null,"name":"helloworld","task":"scanning","type":"project"}]}
> []
> 
> $ hsdev stop
> []

**Comment by jkeuhlen** [comment]
@bscottm Thank you! I appreciate the work you and @mvoidex  do on this project. If I can find the time someday soon I'll try to dig into the code and see what I can do to help contribute rather than just reporting issues.

**Comment by mvoidex** [comment]
@jkeuhlen check produces same error
could you create issue on [hsdev](https://github.com/mvoidex/hsdev/issues) with your project attached?

**Comment by bscottm** [comment]
@jkeuhlen: Can I close this issue?

**Comment by jkeuhlen** [comment]
Transferring issue to `hsdev`:https://github.com/mvoidex/hsdev/issues/59
