### ISSUE TITLE
"SublimeHaskell: Can't infer type [error]" when trying to show type; Is there a log I can check to see more details what the error is about?

### ISSUE THREAD

**Issue by Wizek** [SublimeHaskell/SublimeHaskell#326]
I've just recently installed Sublime Text 3, SublimeHaskell and hsdev (0.2.3.1), the latest version of each IIRC.

Is there a log of SublimeHaskell I can check to see more details what the error is about?

**Comment by bscottm** [comment]
@Wizek: Open the command palette (&lt;ctrl&gt;-&lt;backquote&gt; [&lt;ctrl&gt;-`]), and look for a Python error traceback.

Also, you can change the debugging output level of `hsdev` in your SublimeHaskell user settings. Add these lines:

```
{
	"log": 4,
	"hsdev_log_config": "use default"
}
```

**Comment by bscottm** [comment]
@Wizek: Any new info?

**Comment by Wizek** [comment]
Yes: When I tried to set the above, all sublime windows froze.
After force killing and relaunching it froze again.
I had to reset the config from a different editor.

**Comment by Wizek** [comment]
IIRC up until `"log": 3` it worked, which didn't seem to produce any useful logs. Is there a secondary log I can check to see what causes the freeze/infinite loop? :D

**Comment by bscottm** [comment]
@Wizek: Hate to have to ask you to do this. Can you update to 1.2.2 and also update `hsdev` to 0.2.3.2?

**Comment by codyhan94** [comment]
I've noticed that if the file you're working in can't be loaded into `ghci` (which probably implies that it can't be compiled either because of syntax errors), then the `Show type` functionality of SublimeHaskell breaks as described.

**Comment by bscottm** [comment]
@codyhan94: `hsdev` (and `ghc`) has to be able to correctly parse your source code in order to infer types. You are correct that your source can't be compile because of syntax errors -- that's what the console error message is telling you.

**Comment by bscottm** [comment]
@Wizek, @codyhan94: This issue should be fixed in the 2.0.x release. Can you confirm?

**Comment by bscottm** [comment]
@Wizek, @codyhan94: Closing this issue. If necessary, re-open a new issue if this is still not working.
