### ISSUE TITLE
hsdev version is incorrect: 0.2.3.1

### ISSUE THREAD

**Issue by jrodriguesnum1** [SublimeHaskell/SublimeHaskell#327]
Hi,

I accidentally installed the wrong version of hsdev by running `cabal install hsdev` without specifying a supported version. When I opened sublime text the following message appeared:

```
SublimeHaskell: hsdev version is incorrect: 0.2.3.1
Required version: >= 0.2.0.0 and < 0.2.3.0
Update it by running 'cabal update' and 'cabal install hsdev

To suppress this message and disable hsdev set 'enable_hsdev' to false
```

To attempt to solve this I've run:

```
ghc-pkg unregister hsdev-0.2.3.1
cabal install hsdev-0.2.2.2
```

The same error message still appears when I open sublime text. I've tried to remove and install SublimeHaskell again but it didn't solve the problem.

I think I have the correct version installed:

```
$ ghc-pkg list | grep hsdev
hsdev-0.2.2.2
```

The `cabal list --installed` also says I have the correct version:
```
* hsdev
    Synopsis: Haskell development library
    Default available version: 0.2.3.1
    Installed versions: 0.2.2.2
    Homepage: https://github.com/mvoidex/hsdev
    License:  BSD3
```

Thanks in advance.

**Comment by mvoidex** [comment]
What does `hsdev version` says?

**Comment by jrodriguesnum1** [comment]
"""
$ ~/.cabal/bin/hsdev version
0.2.2.2
"""

**Comment by mvoidex** [comment]
Don't you have `add_to_PATH` sublimehaskell setting set to smth where can be another `hsdev`?

**Comment by bscottm** [comment]
@mvoidex: I can always bump the version range in the plugin, if requested. :-)

**Comment by xeoneux** [comment]
@bscottm please do! It took me 1 hour to build the current 0.2.3.1 version. 😜

**Comment by jrodriguesnum1** [comment]
Before I added the directory `~/.cabal/bin/` to the path I had no `hsdev` executable on it. In which directories does SublimeHaskell search for executables?

**Comment by jrodriguesnum1** [comment]
Sorry, my bad. I found another `hsdev` on `~/.local/bin` which is version `0.2.3.1`. I've no idea how it got there. Removed it and now the error message does not appear.
