### ISSUE TITLE
sublime haskell depends on some environment variable thing not exposed in sublime haskell settings file

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#331]
as per usual, i'm invoking sublime haskell with my cabal newbuild change for dev

with https://github.com/cartazio/resin/tree/5eff5b766b5f7516719420c7f7d084baed13a038
(resin at that commit), i'm getting that sublime haskell is barfing but `cabal build` or `cabal new-build` both work fine ... :(

**Comment by cartazio** [comment]
hrm... even though I have my full path replicated in the sublime haskell settings, if i launch sublime from shell instead of via gui builds work...

was the a recent change that depends on some environment variable lookup thats not exposed via the sublime haskell settings file

**Comment by cartazio** [comment]
@bscottm  ... something else is weird because on build failures its not parsing the output of stdout anymore too ..

**Comment by bscottm** [comment]
@cartazio: That's interesting. There hasn't been an update in over a week and I'll assume that you've been using this over the course of the last week, no? (Anything in the ST console window that can provide insight?)

**Comment by cartazio** [comment]
it was sometime in the past two weeks...

looking at the ctr+backtick panel... i'm seeing an error in an *unrelated* haskell project in all the windows


```
ileNotFoundError: [Errno 2] No such file or directory: '/Users/carter/WorkSpace/projects/active/exp-fam/src/Math/ExponentialFam'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 479, in on_activated
    self.set_cabal_status(view)
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/autocomplete.py", line 445, in set_cabal_status
    (_, project_name) = Common.get_cabal_project_dir_and_name_of_file(filename)
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 101, in get_cabal_project_dir_and_name_of_file
    cabal_file_path = find_file_in_parent_dir(directory_of_file, '*.cabal')
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/sublime_haskell_common.py", line 131, in find_file_in_parent_dir
    for name in os.listdir(current_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/carter/WorkSpace/projects/active/exp-fam/src/Math/ExponentialFam'
```

(could it be confused/stale state from a directory movement in my exp-fam folder?)

**Comment by cartazio** [comment]
nope... not the culprit .. :( 

also on build success its not doing the summary of warnings any more either :(

**Comment by cartazio** [comment]
(to clarify: i tend to keep sublime open for a week or two, with different project windows living for quite a while, and only restart when plugins ... stuff)

**Comment by cartazio** [comment]
point being, the popup/window that shows the errors/warnings never appears, though some source highlighting thing seems to happen sometimes?

**Comment by cartazio** [comment]
how can i help debug this? :)

**Comment by bscottm** [comment]
@cartazio: Found it. Fixed. Will push out in next update. Have to also bump hsdev version number (and command line argument updates that go along with that. Alexandr changed the command line interface to simple-log.)

**Comment by cartazio** [comment]
cool, let me know when theres a release out :)

**Comment by bscottm** [comment]
@cartazio: Out. Actually, waiting for packagecontrol to detect the change.

**Comment by cartazio** [comment]
ok, the build window thing now works, but there definitely an env variable issue, because I think your code is now ignoring 
`	"add_to_PATH":`

**Comment by cartazio** [comment]
and then sublime works if i launch it from shell...and i definitely have my ghc bin in my path and add_to_path :)

**Comment by bscottm** [comment]
@cartazio: Yes, I came across that problem yesterday when I was testing a project similar to your configuration. Will push in 1.2.4 -- should I push just that fix or do you also want me to track down the issue with clicking on lines in the error window?

**Comment by cartazio** [comment]
I'll survive either way, , but whatever is easy for you. Though having that
work again would be nice :)

**Comment by bscottm** [comment]
@cartazio: Another update (because it just bit me in a sensitive area). I was caching the entire environment in the `ProcHelper` class. Then I needed to set `os.environ['http_proxy']`. `ProcHelper` no longer caches the entire `os.environ` environment -- it just copies it and updates `PATH`.

**Comment by cartazio** [comment]
the add to path fix hasn't been released yet right? 'cause I'm still seeing that issue if i dont launch sublime initially via my CLI/Shell, so something's wrong still even with a freshly relaunched sublime. also the HSDEv warning is def still firing

```
{
	"add_to_PATH":
	[ "/Users/carter/.cabal/bin "
    ,"/Users/carter/.install-ghc/ghc-8.0.2/bin "
    ,"/Users/carter/bin /Users/carter/.scripts "
    ,"/Users/carter/docTemplates "
    ,"/Library/TeX/texbin "
    ,"/usr/local/bin "
    ,"/usr/bin "
    ,"/bin "
    ,"/usr/sbin "
    ,"/sbin"

	],
	"auto_build_mode": "normal",
  // "auto_build_mode": "normal-then-warnings",
	"enable_auto_build": true,
    // Show output window on clean/configure/build/install:
  "show_output_window": true,

  // Show error window on build/check/lint:
  "show_error_window": true,

  "auto_run_tests": false,
	"enable_auto_lint": false,
  "enable_auto_check": false,
	"enable_ghc_mod": false,
	"enable_hdevtools": false,
	"enable_hsdev": false,
	"inspect_modules": false,
  "haskell_build_tool": "cabal-new-build"
}


```

**Comment by bscottm** [comment]
@cartazio: Which backend are you using? Because all three are turned off. 1.2.4 and 1.2.5 have the `add_to_PATH` fix -- if you could look in the console window, look for `add_to_PATH` -- if it is `[]`, then you still have an old version.

I have `add_to_PATH` set to `/usr/local/bin` for testing purposes (it's where the Haskell Platform stashes `cabal` and `ghc`) and IWFM (it works for me) when I do build-on-save with `cabal` for testing.

Also, you can use `~` and environment variables in your paths.

**Comment by cartazio** [comment]
... i'm just using the results of building (sublimehaskell does nice inline cabal invocation and error reporting .. )

```
Package Control: Skipping automatic upgrade, last run at 2017-05-04 16:11:00, next run at 2017-05-04 17:11:00 or after
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 361, in on_selection_modified_async
    view = self.get_focused_view_id(view)
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 349, in get_focused_view_id
    active_view = view.window().active_view()
AttributeError: 'NoneType' object has no attribute 'active_view'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 513, in on_selection_modified_async
    callback.on_selection_modified_async(v)
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 361, in on_selection_modified_async
    view = self.get_focused_view_id(view)
  File "/Users/carter/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 349, in get_focused_view_id
    active_view = view.window().active_view()
AttributeError: 'NoneType' object has no attribute 'active_view'
```

looks like i'm not tripping some linter related thing too .. 

how do i pull up the add_to_PATH?
which settings file  do i set the logging level in?

**Comment by cartazio** [comment]
derp ... there were trailing whitespace and other things in that add_to_path settings stuff. working now. It was silently accepting bad paths being added etc :) 

i'm not sure if that was biting me or what :)

**Comment by cartazio** [comment]
(i guess i had a different bug than the reported one, a PEBKAC)

**Comment by bscottm** [comment]
@cartazio: NP. Would you prefer that I not silently discard invalid paths (code ensures that `add_to_PATH` paths are directories)? The code can be noisy, if that would prevent future user frustration.

**Comment by bscottm** [comment]
@cartazio: The sublimelinter traceback seems fairly benign. I get them too without ill effects.

**Comment by cartazio** [comment]
That might be a good idea. At least by default.  I can imagine some folks
hypothetically replicate their configs across machines which may have
different directories etc, so some folks might want to be able to toggle
that.  Or maybe I'm over thinking that one

**Comment by bscottm** [comment]
@cartazio: That's along the lines of what I was noodling while walking Elvis last night. Someday, I'll get back to backend refactoring... :-)
