### ISSUE TITLE
Not Finding hsdev in PATH

### ISSUE THREAD

**Issue by AndoBando** [SublimeHaskell/SublimeHaskell#335]
#On starting SumblimeText, I get:

`hsdev executable couldn't be found
check if it's installed and in PATH

hsdev will be disabled, enable it by setting 'enable_hsdev' to true`

I am pretty confident that I have hsdev installed. I used cabal to install it, and I see it in my %APPDATA%/cabal/packages/hackage.haskell.org folder.

All installs were in the default paths, but I did :`"add_to_PATH":["%APPDATA%//cabal//bin"]` anyway.

I am on windows.

**Comment by bscottm** [comment]
@AndoBando: Try a path without double slashes, e.g., `%APPDATA%/cabal/bin` or `%APPDATA%\\cabal\\bin` (you do have to double the backslashes.)

What was in the `%APPDATA%/cabal/pacakges/hackage.haskell.org` folder? Was `hsdev.exe` there? And was it in `%APPDATA%/cabal/bin`?

**Comment by AndoBando** [comment]
Added both slashes and double backslashes, unfortunately that didn't help. 
All that's in ``%APPDATA%/cabal/pacakges/hackage.haskell.org`,` are a tar.gz that seems to contain the hsdev src but not any binaries. `
%APPDATA%/cabal/bin` has a few `.exe`'s but not  `hsdev.exe`. The only `hsdev.exe` I can find is in a `.cabal-sandbox/bin` in my user, I've tried adding that to path but it seems not to be working. 

Just to make sure I'm doing things properly, I'll Paste my User settings below:
`{
	"add_to_PATH":
	[
		"%APPDATA%\\cabal\\bin",
		"%APPDATA%/cabal/bin",
		"C:\\Users\\Andy\\.cabal-sandbox\\bin",
		"C:/Users/Andy/.cabal-sandbox/bin"
	],
}`
Also, on a restart of sublime text I get a pop-up window letting me know that hdevtools is not installed or in path. Was that enabled by default, or did I muck around with something? Should I install that do or disable it.

Many Thanks!

**Comment by bscottm** [comment]
@AndoBando: If you can't find a `hsdev.exe`, then it really isn't on your `PATH` anywhere. If you `cabal install`, `hsdev.exe` should get installed in `%APPDATA%/cabal/bin` (and no funky path settings are required.)

**Comment by AndoBando** [comment]
Okay, does it matter where I am when I `cabal install hsdev`? Because when I do it, it installs it to a cabal sandbox instead of to my cabal. For now I just copied the `.exe`'s from my cabal sandbox to my real cabal. And sublime Haskell is finding them now.

However... it wants an hsdev between 1.6.0 and 1.7.0 and mine is 2.3.2, is there a way to downgrade my hsdev, or make sublime haskell use my newer hsdev? Many Thanks!

**Comment by bscottm** [comment]
@AndoBando: How current is your SublimeHaskell? The current (version 1.2.5) expects 0.2.2.0 or greater.

**Comment by bscottm** [comment]
@AndoBando: `%APPDATA%/cabal/bin` or `%APPDATA%/local/bin` are the two places where SublimeHaskell will look for `hsdev.exe` (actually, it locally augments the `PATH` environment variable, if you really like implementation details.)

Have you used PackageManager to update all packages recently?

**Comment by AndoBando** [comment]
Forgive my for my ignorance, but It seems I cant update my sublime text packages. I assume the way to update the package is to go to the sublime text package manager `(Ctrl+Shift+P)` and go to Upgrade (Update?) Packages. Is that True? When I do that I get told that there are no packages available for upgrade. I've tried uninstalling and reinstalling sublime Haskell. And I have even reinstalled sublime text 3. Is there something I am doing wrong. Can I force an update. Many Thanks!

**Comment by bscottm** [comment]
@AndoBando: Definitely an old version. Release 1.2.5 is about two weeks old. You're doing the correct thing -- Package Manager: Upgrade Package (or) Package Control: Upgrade/Overwrite All Packages. When you reinstall ST3, you should also wipe out all of your settings (actually, the ST3 authors recommend that you wipe out your settings instead of uninstalling). Where your settings are stored varies by platform and the sublimetext web site is down -- the answer is one of their FAQs.

**Comment by bscottm** [comment]
@AndoBando: Can I close this issue?

**Comment by AndoBando** [comment]
Sure! I got it to work back in may.
Thanks
Andy Badea
