### ISSUE TITLE
on first sublime text (re)launch, complains about hsdev not available despite hsdev disabled

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#336]
![screen shot 2017-05-08 at 3 23 32 pm](https://cloud.githubusercontent.com/assets/4290/25821273/6f916b06-3402-11e7-8827-45873dfa4913.png)

i even tried adding a dummy hsdev shell script that does `exit 255 ` as the entire thing and that still seems to not work even though its in my path ...

**Comment by cartazio** [comment]
to recap: i have all the smart tools disabled because they dont seem to add much over just reading the docs and running ghc every once in a while (especially on a laptop :) )

**Comment by bscottm** [comment]
@cartazio: Can you hold out until I finish refactoring backend interaction, or is this urgent today? Because the cure is worse than the disease, due to the way that backends are handled in the current SH plugin.

**Comment by cartazio** [comment]
Not urgent. Just annoying.  I installed the Hsdev binaries that I'm not
even sure I'll ever use to suppress the warnings on my primary machine :)

**Comment by bscottm** [comment]
@cartazio: <groan> I'll figure out something q&d. At least with the refactored backend management, you'll have the option to have no backend.

**Comment by Pastafarianist** [comment]
Still an issue. I have `"enable_hsdev": false` in my config, yet the warning persists.

**Comment by ikbenlike** [comment]
I am having this issue too, and my cabal doesn't seem to want to install `hsdev` - fixing this isn't urgent for me, though, but the default Haskell highlighting in Sublime Text doesn't work correctly

**Comment by timhwang21** [comment]
Hi, any updates on this? I am also having the same issue. Thanks!

**Comment by bscottm** [comment]
@timhwang21, @cartazio: `enable_hsdev` no longer exists. :-)
