### ISSUE TITLE
feature request/idea: finish migrating from tmlanguage -> YAML syntax?

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#339]
may or may not make tweaking etc of those pieces easier?

**Comment by bscottm** [comment]
@cartazio: Actually, the YAML-based syntax file is what's used to generate the tmLanguage file, at least, the last time I tweaked it. SH has tools that do this automagically.

I just haven't been able to get back to working on syntax highlighting issues in a while.

**Comment by cartazio** [comment]
oh, so the tmlanguage ones are being kept to keep support with slower to
update users of ST3 or perhaps even st2?

**Comment by bscottm** [comment]
Converted the "improved" syntax to ST3 YAML. Had a few false starts with converting up to ST3. It's not perfect, it's not complete, it's only a first step, etc. But should give me a reasonable place to start fixing the syntax highlighting backlog.
