### ISSUE TITLE
[Feature request] Stylish on save

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#345]
It would be convenient if `Ctrl+S` also triggered `Stylish`, like Atom's `ide-haskell` and Emacs's `stylish-haskell-on-save` do.

Could be added as a pre-save or a post-save hook. The latter is probably preferable (so that the changes introduced by `stylish-haskell` could be reviewed before applying them; that's also what `ide-haskell` does), but the former is easier to implement.

**Comment by bscottm** [comment]
Hmmm. Even as a post_save hook and no changes (and string comparisons to detect changes), ST3 thinks the buffer has changes.

**Comment by bscottm** [comment]
In 2.0.0, slated for release later this week.
