### ISSUE TITLE
Feature request: add option to set custom sublime-haskell config

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#352]
Currently I have to resort to patching `indenters.py` by replacing `indenter=['stylish-haskell']` with `indenter=['stylish-haskell', '--config', '/path/to/.stylish-haskell.yaml']`. It would be nice if this could be set in an option (preferably with `os.path.expanduser` applied to it, so that mnemonics like `~` could be used).

**Comment by bscottm** [comment]
@Pastafarianist: As a project setting or a user setting?

BTW: `os.path.expanduser` and `os.path.expandvars` is used on every path in the settings. :-)

**Comment by Pastafarianist** [comment]
Probably as a user setting, unless there can be a default value for a project setting, although I'm not entirely sure.

My motivation is that more people are acquainted with user settings, and not many people work on several projects with different code styles, so making this a user setting will make more people happier. But all of this is just a wild guess.

**Comment by bscottm** [comment]
@Pastafarianist: Project settings can be set per-directory or per-Haskell-project (co-located with the `cabal`.) It might not make much of a difference, but there's a little extra logic involved.

**Comment by bscottm** [comment]
Release imminent. :-)

**Comment by bscottm** [comment]
@Pastafarianist: Grab the update yet? Does it do what you need it to do?

**Comment by Pastafarianist** [comment]
Yep, works for me. Thanks!
