### ISSUE TITLE
Error is reported if stylish-haskell makes no changes

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#353]
Steps to reproduce:

1. Open any Haskell file and break some formatting.
2. Hit `Ctrl+S`. The file will be saved, then `stylish-haskell` will be applied. Then file will be shown as modified.
3. Hit `Ctrl+S` a second time. You will see:
```
stylish-haskell failed, stderr contents:
----------------------------------------
```

This is because the test in `indenters.py` which checks whether `out == sel_str` (via `out in [selection, sel_str]`) is triggered.
The test `out == selection` is even weirder since `selection` is apparently a tuple of numbers, like `(0, 16293)`.

Possible solution: rewrite the code like so:

```python
if (err is None or len(err) == 0):
    if out not in [selection, sel_str]:
        self.view.replace(edit, selection, out)
else:
    indent_err = ' '.join(self.indenter)
    stderr_out = '\n'.join(["{0} failed, stderr contents:".format(indent_err), "-" * 40, ""]) + err
    self.report_error(stderr_out)
```

**Comment by bscottm** [comment]
@Pastafarianist: Oddly, it worked for me without reporting an error... the adjusted code makes better sense. Will push in 2.0.1.

**Comment by bscottm** [comment]
@Pastafarianist: Pushed into 2.0.1.
