### ISSUE TITLE
Version 2 doesn't work on Windows

### ISSUE THREAD

**Issue by trha** [SublimeHaskell/SublimeHaskell#354]
Today I got an upgrade to Sublime Haskell 2. Nothing works anymore. 
I keep getting this error when using local hsdev
```<hsdev stderr> 2017-09-26 21:40:48 +0800	ERROR	:update> cache writing exception: C:\Users\tr\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev\standalone.json: openBinaryFile: resource busy (file is locked)```
My settings: 
```json
{
 "backends": {
        "Local hsdev": {
            "default": true,
            "backend": "hsdev",
            "options": {
              "local": true,
              "port": 4567,
              "install-dir": "C:\\Users\\tr\\AppData\\Roaming\\local\\bin"
            }
      }, 
    }
}
```
Deleting the cache doesn't help. 

I also tried switching to remote hsdev using this settings:
```json
  "backends": {
    "Remote hsdev@localhost:2704": {
      "default": true,
      "backend": "hsdev",
      "options": {
          "local": false,
          "host": "localhost",
          "port": 2704
      }
    }
  }
```
then execute hsdev with
``` C:\Users\tr\AppData\Roaming\local\bin\hsdev run --port 2704 --cache "C:\Users\tr\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev" --log "C:\Users\tr\AppData\Local\Sublime Text 3\Cache\SublimeHaskell\hsdev\hsdev.log"```
This time Sublime Haskell can communicate with hsdev just fine (I can see the messages by setting `component_debug": ["all_messages"]`). But still, I can see  nothing from SublimeHaskell.

My OS version: Windows 10.0.15063.632
Any ideas?

**Comment by bscottm** [comment]
@trha: The `standalone.json: openBinaryFile: resource busy (file is locked)` message happens on all platforms. It is harmless.

Can you give me more details on "Nothing works anymore?" Because I tested on Windows and OS X before I released it.

**Comment by trha** [comment]
I created an empty project with `stack new` then go to `app/Main.hs`, add some imports then save the file. Normally I should get:
- Linting messages complaining that the imported modules is not used
- Auto complete for functions in the imported modules.
However, when updated to SublimeHaskell 2, all I get after saving the file is just `cabal: <project name> [hsdev], Inspecting <project name> [OK]` in the status bar. No error messages from console. It's like Sublime Haskell wasn't activated.

**Comment by bscottm** [comment]
@trha: Thanks for the test case. Will diagnose and hopefully shoot out 2.0.1 with a fix for this.

**Comment by dten** [comment]
What version of `hsdev` do you have installed? I notice a max of `2.4.0.0` but on windows I have `2.5.1`
https://github.com/SublimeHaskell/SublimeHaskell/blob/master/hsdev/backend.py#L43

I tried changing the max and it was working for me with local hsdev now

**Comment by bscottm** [comment]
@dten's patches have been merged and pushed into version 2.0.1. Hopefully this fixes your immediate problem.

**Comment by bscottm** [comment]
@trha: Release 2.0.1 will accept and work with any `hsdev` version less than 0.3.0.0, so 0.2.5.1 should work (it works for me. :-)

**HOWEVER**, I've noticed that `hsdev` should be compiled with GHC 8.0.1 (which means your projects need to compile with 8.0.1 also.) My guess is that either `hsdev` does not flush its network buffers at the completion of each request or something changed in the GHC 8.0.2 runtime that doesn't flush network buffers. Either way, ST3 receives incomplete responses -- the recent "Browse declarations locks up SublimeHaskell" issue tends to confirm this.

I'll do some testing with your settings to see if I can further diagnose

**Comment by bscottm** [comment]
@trha: Ok, maybe GHC 8.0.2 isn't as much of a problem as I thought -- although I'm still a bit leery of it at the moment.

2.0.3: Autocompletions should work a lot better.

**Comment by bscottm** [comment]
@trha: Can I close the issue?

**Comment by trha** [comment]
2.0.3 works now 👍 Thank you so much for the hard work!

**Comment by bscottm** [comment]
@trha: You and the community are very welcome! Without your feedback, SublimeHaskell wouldn't be what it has become.
