### ISSUE TITLE
sublime add to path doesn't work in recent versions of  sublime Haskell

### ISSUE THREAD

**Issue by cj285** [SublimeHaskell/SublimeHaskell#360]
I have to launch sublime Haskell from my terminal to have the paths work for finding cabal etc. 

because @cartazio set me up with the backend refactor branch mid /september it must be one of the handful of commits after fd45b10337f22f6eb5b37063c8ec2dc861361325

something is failing to use those paths somewhere 

<img width="505" alt="screen shot 2017-09-27 at 1 46 38 pm" src="https://user-images.githubusercontent.com/6643496/30928717-53d35706-a38a-11e7-9a8e-ef1fd0f6afa2.png">

**Comment by cj285** [comment]
if I install the newest release of sublime Haskell from package control and enable add_standard_dirs the error becomes 
```
Build FAILED

Collected output:

cabal: The program 'ghc' version >=6.11 is required but it could not be found.
```

:(

**Comment by cj285** [comment]
the issue was my config had "add_to_path" rather than "add_to_PATH", which sublime silently ignored. fix now! 

but that does suggest the config linter / checker should catch this :)

**Comment by bscottm** [comment]
We have a config linter?

**Comment by bscottm** [comment]
We have a config linter?

`add_standard_paths` has been a configuration option for more than a year, for what it's worth. I could put a check to see if `add_standard_paths` exists and yell at you if it is present.

**Comment by cartazio** [comment]
i get errors about old config fields, misconfigured/imaginary fields should
yell at me too :)

**Comment by bscottm** [comment]
@cartazio: I put a quick check into the settings loader to look for old options that are no longer supported. I wouldn't call it a fully featured linter.

Added a check for `add_to_path`. You will get yelled at. And woe betide you if you misspell `stylish-haskell`. :-)
