### ISSUE TITLE
Missing functionality, errors on saving haskell source files

### ISSUE THREAD

**Issue by HardRock** [SublimeHaskell/SublimeHaskell#363]
After setting up everything for SublimeHaskell according to the official guide here on GitHub I've still run into a few issues I couldn't resolve.

- I get no hints from Hlint. Tested via eta reducable funtion definition: foo f x = f x
- The SublimeHaskell build commands (Install, Configure, etc) don't do anything for me. I ran cabal init already for my project and that didn't help.
- Hsdev scan gives me an error in the ST console when saving a haskell source (the file I was editing is actually D:\Projects\main.hs):
```
Sublime Haskell: hsdev scan returns error: file not found
id: 6, file: D:\Projects
```
- When saving a source file I also often get this error in the console:
```
Traceback (most recent call last):
  File "C:\Util\SublimeText\sublime_plugin.py", line 797, in run_
    return self.run()
  File "C:\Util\SublimeText\Data\Packages\SublimeHaskell\build.py", line 366, in run
    run_build(self.window.active_view(), current_project_name, current_project_dir, config)
  File "C:\Util\SublimeText\Data\Packages\SublimeHaskell\build.py", line 226, in run_build
    override_config = Settings.get_project_setting(view, 'active_stack_config')
  File "C:\Util\SublimeText\Data\Packages\SublimeHaskell\internals\settings.py", line 205, in get_project_setting
    return view.window().project_data().get(key, default)
AttributeError: 'NoneType' object has no attribute 'get'
```
- This is likely not related to SublimeHaskell, since it happens with the standard ST Haskell build command in Sublime, but it may hint at where the other issues are coming from I guess. In case of compilation errors I get correctly inlined error messages in my source, but the actual error messages are only listed in the console.

I'm on Windows 10, using the as of now latest Haskell Platform with every install directory left on defaults. A few version numbers that may be relevant:

Sublime Text: 3.0 build 3143
GHC: 8.2.1
Cabal-install: 2.0.0.0 (built with lib 2.0.0.2)
Hsdev: 0.2.5.1

My user settings for SublimeHaskell:
```
{
    "add_to_PATH": [
        "%APPDATA%/cabal/bin"],
    "auto_completion_popup": true,
    "haskell_build_tool": "cabal",
    "lint_check_fly": true,
    "prettify_on_save": true,
    "enable_auto_build": true,
    "enable_auto_check": true,
    "enable_auto_lint": true
}
```

I'd be happy to provide more information if needed, as I'd really like to get SublimeHaskell fully working. It really is an awesome tool for working with Haskell. As someone who is just learning it it has been invaluable to me already.

**Comment by bscottm** [comment]
@HardRock: How do you run HLint? Expecting output from the build or via `SublimeHaskell: Check and Lint`/`SublimeHaskell: Lint`?

I suspect that the traceback is related to your problem.

**Comment by bscottm** [comment]
@HardRock: Pushed version 2.0.7 to fix the traceback.

**Comment by HardRock** [comment]
@bscottm Thanks for the quick response!

I was expecting the output from the build. Just tried it with the `SublimeHaskell: Check and Lint` command and it works as expected that way, autofix as well where applicable.

The underlying cause seems to be that the auto build on save option I enabled is not working. Will check the new version when a bit later. Thanks again!

**Comment by bscottm** [comment]
@HardRock: Tracebacks are a high priority issue that requires as quick a fix as reasonable. Nothing kills open source's reputation than unresponsiveness to broken software.

You triggered this traceback because you don't have any ST-project-specific settings. Seems like everyone else does, which is why it wasn't reported before.

**Comment by HardRock** [comment]
@bscottm Awesome, the new version fixed the traceback indeed. The build commands, auto build on save and inline errors appear correctly now.

The one thing that doesn't seem to work still is Hlint, not with the `enable_auto_lint` nor the `lint_check_fly` settings at least. the command `SublimeHaskell: Check and Lint` still works.

The hsdev scan error also remains.

Even like this, now I can use all features SublimeHaskell provides, just some minimal automation is missing, so I'm already pretty happy.

**Comment by HardRock** [comment]
A bit more information.

`enable_auto_lint` works, provided that `enable_auto_build` is false. If I set it to true I get no code hints on save. This is the case regardless if I set the `haskell_build_tool` to Stack or Cabal (using the latter for now).

`lint_check_fly` however just doesn't seem to work for me, even with default settings.

**Comment by bscottm** [comment]
@HardRock: If you have `enable_auto_build` set, then none of the actions associated with `enable_auto_check` or `enable_auto_lint` will ever execute. SH can't intuit what flags are set in your `cabal` configuration. Hopefully, something that generates lots of warnings. :-)

Let me see what I can do with the code, if it's feasible to auto-build and lint. Normally, build is expensive and done less frequently than check-and-lint (I think that's the logic that I inherited in this code.)

**Comment by HardRock** [comment]
@bscottm That does make sense. I will very likely disable auto-build for now, so I will get code hints on save and any compilation errors on a manual build.

I'm still very new to SublimeHaskell, Cabal and Haskell in general, I assumed that since Hlint can already run on the source, with auto-build it could be run before the build, and would provide hints just the same afterwards.

How does `lint_check_fly` factor into this? Based on its short description in the SH settings file I assume it should provide the same hints and highlights that `enable_auto_lint` does after saving a file, only after leaving the ST idle for the set amount of seconds (5 by default). However for me it seems to do nothing as far as I can tell.

**Comment by bscottm** [comment]
@HardRock: If SH were to build and lint, then users would have to accept the fact that both processes will produce duplicate warnings. Probably not that hard to detect and eliminate, but annoying.

`lint_check_fly` belongs to the on-the-fly checking/linting functionality. It desperately needs love. It wasn't high on my priority list while refactoring the backends recently. It gets turned off when you build. And remains off. Something I need to think about (you really don't want fly checking going on while building or linting/checking-after-saving.)

**Comment by HardRock** [comment]
Got it. It looks like that for now every feature on my end works as it should then, given the limitations you mentioned. Thank you for the explanations and the help on the Python side of things. :)

**Comment by bscottm** [comment]
Closing. Feel free to create new issues as they arise.
