### ISSUE TITLE
Question :  Can I do stack test so the tests of my code are running

### ISSUE THREAD

**Issue by rwobben** [SublimeHaskell/SublimeHaskell#364]
Hello, 

I have some hspec tests in the test directory.
Can I somehow do stack test so I can run all the tests.

I tried SublimeHaskell test but then I see output that the build is successfull but no output of the test is seen. 

Roelof

**Comment by bscottm** [comment]
I'll look into it in the near future.

**Comment by bscottm** [comment]
@rwobben: Found the problem. I'm not sure how it happened, but the the "SublimeHaskell: Test" menu item invoked the `install` tasks, not `test`. I'll push an update later today (Sunday, 29 OCT, Pacific timezone, for the category theory people.)

**Comment by bscottm** [comment]
@rwobben: 2.1.1 release should fix this for you.

**Comment by bscottm** [comment]
@rwobben: Is this issue fixed?

**Comment by rwobben** [comment]
I think so
