### ISSUE TITLE
Error message after updating to 2.1.0

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#365]
![image](https://user-images.githubusercontent.com/1315874/31824377-7bd56b1a-b5b7-11e7-8769-b5f18708f82a.png)

I got this after I launched Sublime and PackageControl updated all packages to their most recent versions, including SublimeHaskell. Note that I was using a slightly-patched version of `indenters.py` to allow for a custom config for `stylish-haskell`.

**Comment by bscottm** [comment]
Huh. Will look into it. Although, if you could revert your `indenters.py` back to the `master` branch, that'd eliminate that as a possible source of the issue.

**Comment by bscottm** [comment]
@Pastafarianist: Out of curiousity, but what did you set `prettify_executable` to in your settings? Is it a path to a file?

**Comment by Pastafarianist** [comment]
@bscottm I did not change `prettify_executable` in the settings. My modification in `indenters.py` was the following. I changed

```python
class SublimeHaskellStylish(SublimeHaskellFilterCommand):
    def __init__(self, view):
        super().__init__(view, indenter=['stylish-haskell'], indenter_options=Settings.PLUGIN.stylish_options)
```

to

```python
class SublimeHaskellStylish(SublimeHaskellFilterCommand):
    def __init__(self, view):
        super().__init__(view, indenter=['stylish-haskell', "--config", "/path/to/.sublime-haskell.yaml"], indenter_options=Settings.PLUGIN.stylish_options)
```

**Comment by bscottm** [comment]
@Pastafarianist: 2.1.1 updates the error message so that `{0}` at least tells you (and me) what's wrong with the `prettify-executable` setting.

**Comment by Pastafarianist** [comment]
Uhh.
![image](https://user-images.githubusercontent.com/1315874/32250948-b8570b84-be9f-11e7-901b-cd8a0cee8a70.png)

**Comment by bscottm** [comment]
@Pastafarianist: Huh. Really.

**Comment by bscottm** [comment]
@Pastafarianist: Do me a favor and check your `prettify_executable` setting. Let's make sure that it is not set to `{0}` (I know, but it's checking the obvious -- I set mine to `wombat` and I get a sensible error message.)

**Comment by Pastafarianist** [comment]
![image](https://user-images.githubusercontent.com/1315874/32303311-cd09b868-bf78-11e7-9370-27f17d246bbc.png)
If I do the same, after a restart I get a sensible error message.

I also checked the code in `settings.py` and I have no idea either how `{0}` could have  been not converted to `settings.get('prettify_executable')`.

**Comment by bscottm** [comment]
@Pastafarianist: This should be in your default settings:

    // The prettifier to use when indenting/prettifying on save. Valid options are "stylish-haskell" or "hindent"
    "prettify_executable": "stylish-haskell",

**Comment by Pastafarianist** [comment]
@bscottm I do have precisely that in my `SublimeHaskell.sublime-settings`.

**Comment by Pastafarianist** [comment]
An update!

![image](https://user-images.githubusercontent.com/1315874/33153491-0a62a71c-cff3-11e7-9627-27a96b48f842.png)

**Comment by bscottm** [comment]
@Pastafarianist: Huh. Not sure what the deal is... will check into it.

**Comment by bscottm** [comment]
@Pastafarianist: Can you post your default and user preferences?

**Comment by Pastafarianist** [comment]
@bscottm here you go:
https://gist.github.com/Pastafarianist/0604b7e3466b7018fa5e38e376b984ac

The only thing I've edited out is the path to `.stylish-haskell.yaml`. This file can be found [here](https://github.com/input-output-hk/cardano-sl/blob/master/.stylish-haskell.yaml).

**Comment by bscottm** [comment]
@Pastafarianist: I think I may have finally fixed this by rethinking how `SettingsContainer` stores preferences -- the code uses Python properties, which is probably what I should have done in the first place. Hopefully, you can close the issue.

**Comment by Pastafarianist** [comment]
Did not get this error after latest update. We should probably consider this issue resolved. Thank you!

**Comment by bscottm** [comment]
@Pastafarianist: NP. Happy to have closed this issue!
