### ISSUE TITLE
Autocompletion doesn't work in explicit import lists

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#366]
Steps to reproduce:

1. Open some file with explicit imports (like [this one](https://github.com/input-output-hk/cardano-sl/blob/master/wallet/src/Pos/Wallet/Web/Methods/Misc.hs))
2. Place the cursor in some explicit import list (like `Pos.Update.Poll.Types`)
3. Start typing some identifier that is present somewhere in the file (like `getUserProfile`)
4. The list of suggestions will not appear below the cursor.

**Comment by bscottm** [comment]
Will look into it.

**Comment by bscottm** [comment]
@Pastafarianist: I tried something similar using import qualified/unqualified for Data.ByteString:

    module Main where

    import Data.ByteString (ByteString)
    import qualified Data.ByteString as B

If I go into the closing parenthesis just after "ByteString", insert a comma and hit &lt;Ctrl&gt;-&lt;Space&gt;, I get a lot of completions.

Alternatively, if I insert `, e` just after "ByteString", I get a lot of completions starting with "e".

Can you construct a test case based on your code that I can use to diagnose?

**Comment by bscottm** [comment]
@Pastafarianist: I'm using `hsdev` as the backend.

**Comment by Pastafarianist** [comment]
@bscottm I'm not using any backends because all the ones that I tried are horribly slow for developing Cardano SL. By autocompletion, I mean autocompletion of identifiers from the same file, which is a standard Sublime feature.

Here is my `SublimeHaskell.sublime-settings`:

```json
{
    "use_improved_syntax": true,

    "backends": {
        "No backend": {
            "default": true,
            "backend": "none"
        }
    },

    "prettify_on_save": true,
    "stylish_options": [
        "--config",
        "/path/to/.stylish-haskell.yaml",
    ],
}
```

Also, I don't hit <kbd>Ctrl</kbd>+<kbd>Space</kbd> at all, as the default autocompletion works without it.

So the test case should be something like this. Copy the following code into `test.hs`:

```haskell
{-# LANGUAGE OverloadedStrings #-}

import           Data.ByteString.Char8 (ByteString)

bstr = "Hello world" :: ByteString

main = do
    putStrLn $ unpack bstr
```

Open this file in Sublime and move your cursor to before the closing parenthesis in the `import` statement. Start typing `, un` and hit <kbd>Tab</kbd>. Instead of getting autocompletion to `unpack`, a literal tab character will be inserted.

**Comment by bscottm** [comment]
@Pastafarianist: Now I understand what you're doing... the key was "no backend". Gives me a place to start looking.

**Comment by bscottm** [comment]
@Pastafarianist: There is the `inhibit_completions` setting, which you can set to `true`. **However**, that's a very unobviously named setting. 2.1.2 will replace this setting with two, `add_word_completions` and `add_default_completions`. `add_word_completions` will add completions from the source file from words that are 3 letters or more. `add_default_completions` will add completions from the SublimeHaskell.sublime-completions file (the default completions.)

**Comment by bscottm** [comment]
@Pastafarianist: In your case, you would probably want to set `add_word_completions` to `true`, probably leave `add_default_completions` as `false`.

**Comment by bscottm** [comment]
@Pastafarianist: 2.1.2 pushed. Use in good health and see if this fixes your issue.

**Comment by bscottm** [comment]
@Pastafarianist: Closing issue, assuming fixed due to lack of additional reports.
