### ISSUE TITLE
Problem with plugin on Windows7 x64

### ISSUE THREAD

**Issue by RinatValiullov** [SublimeHaskell/SublimeHaskell#367]
I installed Haskell Platform, installed hsdev, installed this plugin, but when i open *.hs files in my sublime i get this alert message: **No default backend found. Using the 'none' backend**
Please, tell me what i must write in settings file? Or other advice.

**Comment by bscottm** [comment]
@RinatValiullov: At your shell's prompt, if you type `which hsdev`, what does it tell you? How did you compile `hsdev`?

**Comment by RinatValiullov** [comment]
It tell me that __no hsdev__ in (all paths...). I didn't compile anything. I am newbie, sorry

**Comment by bscottm** [comment]
@RinatValiullov: Try `cabal install hsdev` to install the `hsdev` executable in a place that the SublimeText plugin will find it. I think that will fix your problem. Alternatively:

  $ cd
  $ git clone https://github.com/mvoidex/hsdev.git
  $ cd hsdev
  $ cabal install --only-dependencies
  $ cabal configure
  $ cabal build
  $ cabal install

You can change the first `cd` line to whatever directory better suits your needs.

**Comment by RinatValiullov** [comment]
I have latest version of Haskell Platform 8.2.1. Can this version be problem?
I installed hsdev second time, but console tells me:

![2017-11-07_10-59-42](https://user-images.githubusercontent.com/9755333/32479278-d9b91cee-c3aa-11e7-8265-6d648b08fc05.png)

And alert message in Sublime 3: **No default backend found. Using the 'none' backend**

**Comment by bscottm** [comment]
@RinatValiullov: Yes, that is a big problem to get `hsdev` to build correctly. Can you write out the steps you used? For example, did you `cabal install --only-dependencies`?

**Comment by RinatValiullov** [comment]
1. Installed __Haskell Platform__ (latest version)
2. Installed __hsdev__ with cabal
3. Installed SublimeHaskell

**Comment by bscottm** [comment]
@RinatValiullov:

Setting up `hsdev`:

    rem Go to your home directory
    cd %USERPROFILE%
    git clone https://github.com/mvoidex/hsdev.git
    cd hsdev
    stack build
    rem "Wait for a time with patience until your request is received and an answer"
    rem "returned," said the Worshipful Master in the East.

That should build `hsdev`. Then, update your SublimeHaskell backend settings:

    "backends": {
        "stack-built hsdev": {
            "default": true,
            "backend": "hsdev",
            "options": {
              "exec-with": "stack",
              "install-dir": "%USERPROFILE%/hsdev"
            }
        },
        "No backend": {
            "default": false,
            "backend": "none"
        }
    },

Keeping my fingers crossed that this works for you.

**Comment by RinatValiullov** [comment]
What should i do with installed `hsdev`?

**Comment by RinatValiullov** [comment]
Something wrong after __stack build__

![image](https://user-images.githubusercontent.com/9755333/32680713-c75bf90a-c68d-11e7-8f60-6f9a42f8f524.png)

**Comment by bscottm** [comment]
@RinatValiullov: Ugh. You probably have GHC 8.2.1 installed from the Haskell Platform. `stack` (for whatever reason) doesn't support 8.2.1.

 Here's a revised set of instructions.

    rem Go to your home directory
    cd %USERPROFILE%
    git clone https://github.com/mvoidex/hsdev.git
    cd hsdev
    stack setup
    stack solver
    stack build
    rem Then Warden in the South said, "Wait for a time with patience until your
    rem request is received and an answer returned."

**Comment by RinatValiullov** [comment]
![chrome_2017-11-14_15-27-12](https://user-images.githubusercontent.com/9755333/32775276-cf8caca8-c950-11e7-95dc-38108920fb69.png)

Thanks for supporting.
I reinstall my Haskell --> 8.0.2 several days ago. Make `stack build` and it became working.

**Comment by bscottm** [comment]
@RinatValiullov: Can I close the issue now?

**Comment by RinatValiullov** [comment]
Yeah, you can close!
I understood that stack make something like sandbox which doesn't interfere with the main version.
And magic is `stack solver`

**Comment by bscottm** [comment]
@RinatValiullov: You might try reading through "Learn You A Haskell For Great Good." Despite the title, it's a good introduction to Haskell and well written.

**Comment by RinatValiullov** [comment]
Yeah, already read! Thank you for supporting.
