### ISSUE TITLE
Still getting SublimeHaskell message after it's removed

### ISSUE THREAD

**Issue by amber-dao** [SublimeHaskell/SublimeHaskell#370]
Hi there, I tried installing this and then decided to remove it. It's not registering as an installed package, but I'm still getting `SublimeHaskell: Inspecting[ok]` in the bottom bar. Do you know how I can manually delete this?

**Comment by bscottm** [comment]
@amber-dao: It sounds like SublimeHaskell isn't completely removed, even though PackageControl claims it is. What platform are you on?

**Comment by amber-dao** [comment]
@bscottm  Sublime Text 3, Win.

**Comment by bscottm** [comment]
@amber-dao: Did you restart SublimeHaskell? If you remove a package, that doesn't mean that the package is completely unloaded from the Python interpreter; only the files are removed.

**Comment by amber-dao** [comment]
@bscottm That is a good point. As far as I'm concerned it's resolved. Thanks for replying.
