### ISSUE TITLE
Sublime freezes

### ISSUE THREAD

**Issue by Athrem** [SublimeHaskell/SublimeHaskell#371]
So when opening sublime it tries to load SublimeHaskell. However it freezes on the build.
When closing and reopening Sublime it gives the following error messages:

```
No usable backends (hsdev, ghc-mod) found on PATH or in the standard Haskell cabal and stack installation locations. 
Please check or update your SublimeHaskell user settings, or install hsdev or ghc-mod.
```

However other times it will build and work perfectly.  I'm running cabal 1.24.0.2 and hsdev 0.2.5.1. I also checked and cabal is added to the PATH. 
Can you help me fix this?

**Comment by ROpdebee** [comment]
I've got the same issue. I upgraded to GHC 8.2.2 yesterday, not sure if that's related. Either way, I'm getting an error in the log as well: [`wait_complete` error log](https://gist.github.com/ROpdebee/098bf52d248dad76427a5f9b94dfba3c)

Able to reproduce the freezing on very simple code, such as [this one](https://gist.github.com/ROpdebee/0485ed3b9c0f7f728f3ddbbae0aa20ff). Here's how I'm able to reproduce it:
1. Edit the file (doesn't matter if the edit breaks the code)
2. Save the file --> Error message appears
3. Edit again
4. Save again --> Freezes
5. Wait.............
6. Call to hsdev times out, go back to step 1.

Seems like that error is crashing the hsdev backend and Sublime is completely freezing during the timeout period.
