### ISSUE TITLE
Sublime crashes/freezes on save 

### ISSUE THREAD

**Issue by MiloBuwalda** [SublimeHaskell/SublimeHaskell#373]
Unfortunately, since the latest Windows 10 update (Version 1703), saving a .hs file with SublimeHaskell crashes Sublime Text 3. I have no idea how to provide error logs.

**Comment by bscottm** [comment]
@MiloBuwalda: Does Sublime crash for other reasons (do you use SublimeText for other projects or just for Haskell)? I'm not a Windows user, ordinarily, so my ability to diagnose this is limited. I'll see what I can do.

**Comment by MiloBuwalda** [comment]
Hey @bscottm, I use it for everything. I tested whether other plugins where responsible for the crash but as soon as I uninstalled SublimeHaskell, the problem went away. Installing it again made the crashing reappear as well. Unfortunately I had to uninstall sublimeHaskell because of this limitation. Which is so sad because it works awesome! (Up until now :p) Thanks for looking into it!

**Comment by ROpdebee** [comment]
You can view the log by hitting ``Ctrl+` ``. However, Sublime Text doesn't save its logs by default, they get purged after ST gets closed. You can use [SublimeLog](https://github.com/yrammos/SublimeLog) to permanently log the error messages to a file.

**Comment by bscottm** [comment]
@MiloBuwalda: Would you mind terribly if I asked you to install SublimeLog and upload the results to this issue? That'd save me some brain damage and give my dog, Elvis, his normally allotted walk time. :-)

**Comment by MiloBuwalda** [comment]
Not at all, it'll take some time unfortunately because of work. I will send it tonight hopefully.

**Comment by MiloBuwalda** [comment]
Dear friends, thanks for the quick assistance, the recent upgrade apparently fixed the problem! :P I apologize for any inconvenience, and if the problem pops up again I'll notify with a log!

**Comment by bscottm** [comment]
@MiloBuwalda: Huh.

**Comment by MiloBuwalda** [comment]
@bscottm, the SublimeHaskell upgrade apparently fixed it. I have no idea why.

**Comment by bscottm** [comment]
@MiloBuwalda: Neither do I. Glad it works for you. Will keep an eye out if it happens again.

**Comment by ROpdebee** [comment]
Maybe a dupe of #371?

**Comment by MiloBuwalda** [comment]
@ROpdebee, yes looks like it!

**Comment by bscottm** [comment]
@MiloBuwalda: Probably not. #371 is related to "stale" Python libraries that are still present after a PackageControl upgrade. Unless, of course, you didn't restart SublimeText after an update and this has nothing to do with a Windows 10 update.

**Comment by MiloBuwalda** [comment]
@bscottm, I did restart SublimeText, many times. I guess you're right then. I haven't the slightest idea what went wrong. 

I was wondering, I have an additional off topic HaskellNewbie question about why my SublimeREPL works fine, but the SublimeHaskell output console gives me an error about failing to load packages. Could I ask it to you, or could you direct me to somewhere I can ask this question?

For instance output shows the following but the dependency is installed: 
  H:\Documents\Dropbox\Study\E-Learning\Master Thesis\Project\jsonreader.hs: line 9, column 1:
    Error: Failed to load interface for `Data.ByteString.Lazy'
  It is a member of the hidden package `bytestring-0.10.8.1'.

  H:\Documents\Dropbox\Study\E-Learning\Master Thesis\Project\jsonreader.hs: line 10, column 1:
    Error: Failed to load interface for `Data.Aeson'
  Perhaps you meant Data.Version (from base-4.9.1.0)
  Use -v to see a list of the files searched for.

**Comment by bscottm** [comment]
@MiloBuwalda: The most likely cause is the lack of a `cabal` file. `hadev` looks in the `cabal` file for what packages should be enabled/searched for (as do other tools.)

**Comment by MiloBuwalda** [comment]
Thnx @bscottm, appreciate it!

**Comment by bscottm** [comment]
@MiloBuwalda: #377 gave me a traceback that I could diagnose the problem. 2.1.7 should fix both.
