### ISSUE TITLE
enable_auto_check without showing warnings?

### ISSUE THREAD

**Issue by coodoo** [SublimeHaskell/SublimeHaskell#374]
Is there a way to have `enable_auto_check` turned on but only report errors (without warnings and hints)?

**Comment by coodoo** [comment]
Had a quick look at the source and seemed [these lines](https://github.com/SublimeHaskell/SublimeHaskell/blob/master/parseoutput.py#L112-L117) is a great place to put in an option to decide which sections to show or hide?

Options could look like this:
```js
displayOptions = {
  errors: true,
  warnings: false,
  hints: false
}

**Comment by bscottm** [comment]
@coodoo: Sounds reasonable, will look into adding this enhancement.

**Comment by coodoo** [comment]
Thanks, very look forward to seeing it come true! 👍👍

**Comment by bscottm** [comment]
@coodoo: Probably will be a Christmas present. Still tweaking error marking functionality.

**Comment by coodoo** [comment]
Woohoo! that looks lovely, thanks! 😍

**Comment by coodoo** [comment]
knock knock, where's the Santa? :P

**Comment by bscottm** [comment]
@coodoo: He got tripped up by NORAD temporarily. NORK missile test generated a GPS NANU message, had to fly at a lower altitude and speed to get his job done. :-) :-)

All seriousness aside, 2.1.9 is now out.

**Comment by coodoo** [comment]
Haha, thanks! Just updated and the new `show_only` settings worked great.

However, more Santa magic needed for that following things seemed to be a regression? :P

1. `"enable_auto_check": true,` not working when saving the file, now I have to manually trigger `check` from the panel

2. `auto fix` seemed not working either, with following error messages:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/commands.py", line 1058, in run
    on_error=on_err)
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 519, in check_lint
    return action('check-lint', {'files': self.files_and_contents(files, contents),
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 253, in files_and_contents
    retval = [{'file': f, 'contents': contents.get(f)} for f in files] if files else []
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 253, in <listcomp>
    retval = [{'file': f, 'contents': contents.get(f)} for f in files] if files else []
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/commands.py", line 1058, in run
    on_error=on_err)
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 519, in check_lint
    return action('check-lint', {'files': self.files_and_contents(files, contents),
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 253, in files_and_contents
    retval = [{'file': f, 'contents': contents.get(f)} for f in files] if files else []
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/backend.py", line 253, in <listcomp>
    retval = [{'file': f, 'contents': contents.get(f)} for f in files] if files else []
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by bscottm** [comment]
@coodoo: Fixed the traceback. Not sure what's happening with the post save hook, will look at it later today.

**Comment by coodoo** [comment]
Thanks for working on this during the holiday season, please let me know if you need more debugging info :D

**Comment by bscottm** [comment]
@coodoo: Sooooo.... the ST3 API documentation includes some functions in the `sublime_plugin.ViewEventListener` API that don't exist for the current version, Build 3146. They do exist for the development version, but are not labeled as "Build 3155" or have any build number indication.

Had to back out some of my refactoring. Probably should have bumped my version number to 2.1.10. Just pushed out 2.1.9.2.

**Comment by bscottm** [comment]
@coodoo: Does the 2.1.9.2 update actually come through, or do I need to change the version number to 2.1.10?

**Comment by coodoo** [comment]
Well I just updated and got `2.1.10` and it worked like a charm, both `check post save` and `auto fix` are working.

As a side note, is it normal for `hsdev` to consume 100% cpu while running? I have a terminal window with `top` running to monitor the cpu usage and find it a bit high, nothing serious, just curious though.

```
*SublimeHaskell* 2.1.10
  =======================

  SublimeHaskell 2.1.x is a release tree for minor enhancements and fixes to newly identified (and resolved) issues.
```

**Comment by bscottm** [comment]
@coodoo: `hsdev` should be relatively low CPU unless its in use. BFOM.

**Comment by bscottm** [comment]
@coodoo: Closing issue as fixed. Feel free to reopen.
