### ISSUE TITLE
Editor crashes when saving

### ISSUE THREAD

**Issue by coodoo** [SublimeHaskell/SublimeHaskell#377]
When hitting save button the editor immediately hang and crash, with error message as below, seemed like a streaming decoding issue? For some reasons the response message coming back from hsdev server isn't correct and `client.py` doesn't know how to handle it safely?

Btw, this happened a couple of times before the latest update, hence should be an old issue.

```
Exception in thread hsdev recvr 0:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/jlu/Library/Application Support/Sublime Text 3/Packages/SublimeHaskell/hsdev/client.py", line 55, in hsconn_receiver
    streaminp = self.socket.recv(8192).decode('utf-8').replace('\r\n', '\n').replace('\r', '\n')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 8190-8191: unexpected end of data
```

**Comment by bscottm** [comment]
@coodoo: Thanks for finding this, it's a lot more clueful as a diagnostic. I'll try to get you a patch as quickly as I can.

**Comment by coodoo** [comment]
Appreciate, this issue is causing me disabling the plugin for now, very looking forward to re-enable it again, let me know if there's anything I could help with.

**Comment by bscottm** [comment]
@coodoo: I'm willing to put money on `decode` failing because there's more to read from the socket. If the remaining data coming from the socket were read, then `decode` would succeed.

I'll try to have a new version out soon with a reasonable workaround. Thanks again for the traceback.

**Comment by bscottm** [comment]
@coodoo: 2.1.7 pushed out for release from PackageControl. Hopefully this fixes the issue. :-)

**Comment by coodoo** [comment]
Just updated and everything looks fine so far, no crash, no hanging, just lovely warnings and error messages from ghc (as usual...), happy user again, great job! 👍👍

Btw, I installed [SublimeLog](https://github.com/yrammos/SublimeLog) to catch that error trace, might help other users reporting issues in the future to provide useful information :)

**Comment by bscottm** [comment]
@coodoo: Really appreciate the assist in finding the root cause. Thanks for helping make this better and more stable!
