### ISSUE TITLE
2.1.10 does not reload prettifier config unless restarted

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#380]
Steps to reproduce:

Put in SublimeHaskell config:
```
    "prettify_on_save": true,
    "stylish_options": [
        "--config",
        "/path/to/config1/.stylish-haskell.yaml",
        // "/path/to/config2/.stylish-haskell.yaml",
    ]
```

Save config and try saving some Haskell file. It should use `config1`.

Now update SublimeHaskell config by commenting `config1` and uncommenting `config2`. Save the config and try saving some Haskell file. `config1` will be used again.

Restarting Sublime fixes the issue.

**Comment by bscottm** [comment]
@Pastafarianist: I'm not seeing this problem. Here's a way to verify/diagnose -- enter the following into the console window (`Control-Backtick` or `Ctrl-\``):

    import SublimeHaskell.internals.settings as Settings
    Settings.PLUGIN.stylish_options
    # Change settings, save
    Settings.PLUGIN.stylish_options

What I did: I set `stlylish_options` to `[ "--config", "things" ]`:

    >>> Settings.PLUGIN.stylish_options
    ['--config', 'things']

Then changed them to `[ "--config", "whappy" ]` and saved:

    >>> Settings.PLUGIN.stylish_options
    ['--config', 'whappy']

**Comment by Pastafarianist** [comment]
I confirm that `Settings.PLUGIN.stylish_options` reflects the new settings. However, the issue is still there. Try using a nonexistent file as `config1` and a valid path as `config2`. After you make sure that SublimeHaskell has picked up `config1`, switch to `config2`, and when you hit `Ctrl+S`, you will see for a split second a pane at the bottom that will report an error. Since this pane closes almost instantaneously, I haven't been able to copy-paste it, but it is something like:

```
stylish-haskell --config /path/to/config1 failed, stderr contents:
stylish-haskell: /path/to/config1: openBinaryFile: does not exist (no such file or directory)
```

BTW I keep forgetting to file a bug report about this disappearing error pane, I'll do it now separately.

**Comment by bscottm** [comment]
@Pastafarianist: Can you verify in 2.1.14?

**Comment by Pastafarianist** [comment]
`prettify_on_save` doesn't seem to work with 2.1.14 at all :(

**Comment by bscottm** [comment]
@Pastafarianist:

Before Save:
![before save](https://user-images.githubusercontent.com/355395/34586103-77f9c8b6-f157-11e7-8c4d-cf12cf4e44f9.png)

After Save:
![after save](https://user-images.githubusercontent.com/355395/34586109-7fb9a792-f157-11e7-866c-9804169f490d.png)

Build 3156 on Mac OS X Sierra. And the error window stays put, no flash or premature closing.

**Comment by Pastafarianist** [comment]
Perhaps the difference is the presence of the `.cabal` file, as suggested by https://github.com/SublimeHaskell/SublimeHaskell/issues/384#issuecomment-355417559 ?

**Comment by bscottm** [comment]
@Pastafarianist: Yup. That's the problem, although, when you have `prettify_on_save` set, build/check/lint has to complete successfully before the indenter is run. However, `hsdev` requires that the file belong to a `cabal` project, which causes the build/check/lint to fail and the indenter doesn't run. I think one would really prefer the indenter to run on files that compile correctly.

So, really, it isn't the case that the indenter stopped running completely. It only runs if build/check/lint succeeds.

Not really sure what to do about the `hsdev` "I only check files in projects" requirement because there's not much I can do about it. Worse is that most commands to the `hsdev` backend complete with errors, so reporting the error would result in a blizzard of error windows.

**Comment by Pastafarianist** [comment]
If this is an issue with `hsdev`, perhaps indenters could be made to work with the `none` backend? And in the meantime, someone could file an issue against `hsdev` (I can't do it myself since I'm not using `hsdev` at all and I'm not sure how to formulate it precisely enough).

**Comment by bscottm** [comment]
@Pastafarianist: Lemme check that. I was going to say, "They do!" (or at least, "They oughta??!!"). Shouldn't be a big deal.

**Comment by bscottm** [comment]
@Pastafarianist: SBF 2.1.16. I hope.

**Comment by bscottm** [comment]
Closing because this is now the subject of issue #388.
