### ISSUE TITLE
Making scan paths minimal

### ISSUE THREAD

**Issue by coodoo** [SublimeHaskell/SublimeHaskell#381]
Seems whenever a file was saved, `sublimehaskll` will try to scan a couple of paths including `package-db`, `global-db` and even the `dropbox` folder (not sure why), I was wondering is all these paths necessary and for what purpose? Is it possible to manually configure which path to be scanned?

I'm hoping by making the scan paths minimal it could make check after saving faster.

**Comment by bscottm** [comment]
@coodoo: Duplicate of #382?

**Comment by coodoo** [comment]
Yup, originally I thought those two were the same thing, but after observing it works for a while I think they are two different issue, for that maybe some of those paths should not be scanned at all?

For example, I'm not sure why `package-db` and `global-db` needed to be scanned every time, instead of just once when `hsdev` was started, and only re-scan when there are changes made to those folders.

But sure, if `early bailout` is implemented, this issue should become irrelevant :)

**Comment by bscottm** [comment]
@coodoo: SBF in 2.1.14

**Comment by coodoo** [comment]
Now that #382 is implemented and everything worked great, hence rendering this one sort of irrelevant, closing it.
