### ISSUE TITLE
Early bailout of a scan

### ISSUE THREAD

**Issue by coodoo** [SublimeHaskell/SublimeHaskell#382]
Ideally whenever `hsdev` returns the first error, `sublimehaskell` should cancel the scan of the rest files (which normally includes all files under `pakcage-db` and `global-db` folders) so that users could make edit and save again to quickly start another checking round, this will make the writing experience more fluent and efficient.

The goal here is to make it as fast as `ghci`.

**Comment by bscottm** [comment]
@coodoo: That was something I was looking into recently while tracking down a @Pastafarianst issue. SBF shortly, I think.

**Comment by bscottm** [comment]
@coodoo: SBF in 2.1.14

**Comment by coodoo** [comment]
Just updated to `2.1.14` and everything worked like a charm! Thanks for the quick response and high quality of work as always 👍👍👍

**Comment by coodoo** [comment]
and a side note, with this update, it seemed to bring down cpu usage even when `hsdev` is running, I guess it's due to the avoidance of excessive scan of package files, which makes the poor battery lasts longer :)

**Comment by bscottm** [comment]
@coodoo: Are you using fly mode? If so, I did a couple of tweaks to bring that down to a relatively dull amount of CPU usage.

**Comment by coodoo** [comment]
I gave `fly mode` a try and it did work well,  but ended up going back to `check post save` mode because I'm more used to write a chunk of code then have it checked at one go.

**Comment by coodoo** [comment]
btw, with this new update, whenever `save` button was hit there will be a brief pause with a Spinning Rainbow Wheel showing up for like a second before the check start, during this one second sublime text editor is frozen, wondering what might be causing this?

**Comment by bscottm** [comment]
@coodoo: I made check/lint synchronous, which causes a UI main thread pause. I'm in the process of reconsidering that change...

**Comment by coodoo** [comment]
Ah right, that makes sense, but it’s rather  annoying because it blocked the coding flow (write/save/write), I guess for most people that auto checking is more important than linting, and used more often too, maybe you can make sync optional via config?

**Comment by coodoo** [comment]
@bscottm Just updated and the post-save dead lock is gone, thanks for brining the swiftness back 👍👍
