### ISSUE TITLE
"Prettify" no longer shows up in Command Palette with 2.1.12

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#384]
Sublime 3156, SublimeHaskell 2.1.12, fully updated Manjaro Linux:

![image](https://user-images.githubusercontent.com/1315874/34538949-8cd630b2-f0df-11e7-9211-157e20bf1981.png)

![image](https://user-images.githubusercontent.com/1315874/34538958-96df2db6-f0df-11e7-91ed-de5e30364159.png)

`prettify_on_save` doesn't work either, even though the option itself is still accessible via `SublimeHaskell.internals.settings`.

**Comment by bscottm** [comment]
@Pastafarianist: Can you reproduce in 2.1.14?

**Comment by Pastafarianist** [comment]
No longer an issue in 2.1.14.

**Comment by Pastafarianist** [comment]
Actually, still an issue, although now I'm not sure how to reproduce it. Can you attempt the following steps?

1. Create a new folder, like `test-folder` somewhere.
2. Open that folder as a project in Sublime.
3. Create a new file called `01_test.hs` in that folder and paste the following contents there:

```haskell
main :: IO ()
main = putStrLn "Hello world"
```

4. `Ctrl+Shift+P`, type "stylish".

Result for me:

![image](https://user-images.githubusercontent.com/1315874/34582763-27dac84a-f1a6-11e7-9319-04f6309f9f10.png)

SublimeHaskell 2.1.14, Sublime Text 3156 (dev build), fully updated Manjaro Linux.

**Comment by Pastafarianist** [comment]
I can try downgrading to the latest version from `stable` to see whether it works.

**Comment by bscottm** [comment]
@Pastafarianist: Dippy question: Did you ever save `01_test.hs`? Or did you just try to run a prettifier on an unsaved file?

SublimeHaskell will only enable the prettifier commands (stylish, hindent) on buffers that are obviously Haskell source, where "obviously" means "Haskell syntax is being used or the syntax file contains 'haskell' in the name."

I could loosen this restriction on the prettifiers, although it did seem like a really good idea at the time.

**Comment by Pastafarianist** [comment]
Yes, I have — I believe that can be seen in the screenshot as well.

**Comment by bscottm** [comment]
@Pastafarianist: Hmmmm... for a new project that doesn't have a `cabal` file. I was just able to reproduce this issue, after a bit of struggling.

**Comment by bscottm** [comment]
@Pastafarianist: Fixed this one, wasn't hard to identify. The `stylish` and `hindent` commands should not require a file to be part of a project. SBF in 2.1.15.

**Comment by bscottm** [comment]
@Pastafarianist: Fixed? Yes/No/Maybe?

**Comment by Pastafarianist** [comment]
@bscottm seems fixed in 2.1.16 🎉 
However, `prettify_on_save` doesn't work at all. I'll create a new issue for that.
