### ISSUE TITLE
Syntax Highlighting Support for Underscores in Numeric Literals

### ISSUE THREAD

**Issue by iamrecursion** [SublimeHaskell/SublimeHaskell#387]
The [Underscores in Numeric Literals](https://ghc.haskell.org/trac/ghc/ticket/14473) proposal has been accepted by the GHC committee and is in progress for implementation into GHC. It would be great if the grammar used by SublimeHaskell added support for these. 

This is very low priority, but I thought that I might as well put it on the radar.

**Comment by takenobu-hs** [comment]
@iamrecursion, thanks.

Although I can not confirm because I do not have Sublime,
I think that a patch for SublimeHaskell is the same as the patch for VScode's language-haskell (which adopts TextMate format).

https://github.com/JustusAdam/language-haskell/pull/49/files

**Comment by bscottm** [comment]
@iamrecursion, @takenobu-hs: So, we've embarked on becoming PL/1? PL/1 was an IBM language from the late 70's and the reason why Pascal was invented -- Pascal was simple whereas PL/1 had features upon features upon features that were awfully complex by the standards back then.

**Comment by bscottm** [comment]
@iamrecursion: @takenobu-hs: There is a need to completely overhaul the syntax highlighting and get away from the TextMate format. Adding underscores isn't hard to do.

**Comment by iamrecursion** [comment]
That’s the main reason I posted the issue.

**Comment by takenobu-hs** [comment]
@bscottm, Thank you very much.
Although I am not familiar with the whole system, Atom adopts CoffeeScript format and Pygments adopts Python format.

https://github.com/atom-haskell/language-haskell/pull/112/files
https://bitbucket.org/birkenfeld/pygments-main/pull-requests/745/fix-haskell-lexer-for-numeric-literals/diff

**Comment by bscottm** [comment]
@takenobu-hs: The revamped SublimeText3 syntax highlighting is still based on regular expressions, like TextMate. It has the capability to recurse, which is useful for things like comments within comments. It really sucks when dealing with layout-based formats, like Haskell.

The "improved" Haskell highlighting system is a complete overachievement in regular expressions, which makes the conversion much more challenging.

**Comment by bscottm** [comment]
@iamrecursion, @takenobu-hs: "Improved" syntax definitions converted to new ST3 YAML format. Added this to the number syntax.

**Comment by iamrecursion** [comment]
Brilliant! Thanks so much!

**Comment by takenobu-hs** [comment]
Great! Thank you for taking the time!

**Comment by bscottm** [comment]
@iamrecursion, @takenobu-hs: Relatively easy to do. Lots of work to be done on syntax highlighting...
