### ISSUE TITLE
broken error highlighting / line jump in current sublime haskell  for cabal/cabal-new-build

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#390]
This applies to both cabal-build and cabal-newbuild settings. 

![screen shot 2018-01-11 at 4 20 38 pm](https://user-images.githubusercontent.com/4290/34848055-6ec90e70-f6eb-11e7-915e-ff1870a0369f.png)
)

its not the end of the world, but its borderline show stopper in terms of basic support most folks expect i think :)

**Comment by cartazio** [comment]
expected:
being able to click on the error number line/column to jump to error, plus highlighting at the error location

actual: big ole regression :)

**Comment by bscottm** [comment]
@cartazio: One step forward, two steps back? Is `digger` something I can clone or check out?

**Comment by cartazio** [comment]
https://github.com/hopper-lang/digger should work :)

**Comment by cartazio** [comment]
I linked you the current baby repo for you to repro


Worth mentioning I’m a None backend kinda guy still :)

**Comment by bscottm** [comment]
@cartazio: Thanks. Gives me something to work with. This problem is independent of the backend, since the code parses the output from `cabal`. The backends do a reasonable job of normalizing the compiler's output. So it's back to hacking regular expressions. Again.

**Comment by cartazio** [comment]
What about parsers? Allegedly there’s some ok options in python land :)

**Comment by bscottm** [comment]
@cartazio: Turns out the bug was reversed parameters. And some regex tweaking for the 8.2.x error reporting. SBF 2.1.17.

**Comment by cartazio** [comment]
seems to work now :)

**Comment by cartazio** [comment]
closing i suppose 
thanks!

**Comment by bscottm** [comment]
@cartazio: >Whew!< Dippy error on my part.
