### ISSUE TITLE
HSDev not detected?

### ISSUE THREAD

**Issue by 1Mark** [SublimeHaskell/SublimeHaskell#391]
Hi, I'm new to both SublimeHaskell and hsdev etc (everything about Haskell).

What I've done 
`sudo apt-get install haskell-platform`
Tested Haskell's `ghci` it compiles fine.

Then did `cabal install hsdev` 
I opened ST3 and in the package manager installed SublimeHaskell. Then it said 
```
No usable backends (hsdev, ghc-mod) found on PATH or
in the standard Haskell cabal and stack installation
locations.

Please check or update your SublimeHaskell user settings,
or install hsdev or ghc-mod.
```
I realised this then installed to `$HOME/.cabal/bin` instead of in `.local`. 
`whereis hsdev` returned blank so I added `export PATH="$HOME/.cabal/bin:$PATH"` to my ~/.bashrc
I also added to `SublimeHaskell.sublime-settings`
```
{
	"add_to_PATH": ["$HOME/.cabal/bin"]
}

```

I will be honest and say I'm not sure if it's working or not - I used to use Java and build systems to compile inside sublime. 

But SublimeHaskell:Build and SublimeHaskell:Run in the bottom left keep saying no active projects so I assume something is wrong as well as nothing is really happening?
See bottom right of image
![image](https://user-images.githubusercontent.com/15360245/34900356-24c050ba-f7f7-11e7-9565-c361b998346f.png)

**Comment by bscottm** [comment]
@1Mark: `hsdev` requires a "project" to organize sources -- what you need to do is create a `.cabal` file and add `untitled.hs` to an `Executable` or `Library` section. Have a look at [How to write a Haskell program](https://wiki.haskell.org/How_to_write_a_Haskell_program).

Adding `$HOME/.cabal/bin` and `$HOME/.local/bin` shouldn't be necessary, since those are two of the standard places that _SublimeHaskell_ will add to its `PATH`. I haven't touched that part of the code in a long time, so it still should work.

**Comment by 1Mark** [comment]
Regarding 

> Adding $HOME/.cabal/bin and $HOME/.local/bin shouldn't be necessary, since those are two of the standard places that SublimeHaskell will add to its PATH. I haven't touched that part of the code in a long time, so it still should work.
You are correct.

Could you please see this gif and tell me what im doing wrong.
/home/mark/Downloads/Peek 2018-01-13 19-03.gif

**Comment by bscottm** [comment]
@1Mark: Haskell follows a module/directory path layout to source files. You probably want to rename `untitled.hs` to `Main.hs` or `Untitled.hs`. If you're building a library, modules, like `Data.List` would have a directory path layout `Data/List.hs`.

OTOH, if you just want to open this file in a GHCI interpreter, there's a _SublimeHaskell_ command for that. :-)

**Comment by 1Mark** [comment]
Btw I did try naming it main.hs and it not working although i cannot say i made m in main uppercase or not.

> OTOH, if you just want to open this file in a GHCI interpreter, there's a SublimeHaskell command for that. :-)
What's the command ?

**Comment by bscottm** [comment]
@1Mark: It really needs to be an uppercase "M". I know, I know, it's Haskell. :-)

&lt;Shift&gt;-&lt;Alt&gt;-P (Linux, Windows) or &lt;Shift&gt;-&lt;Command&gt;-P to open the command palette, type 'ghc' in the box that shows up.

**Comment by 1Mark** [comment]
Ok last thing apologies.

Imagine that I'm not developing in Haskell, should it still keep complaining (1 in 3 times) when opening sublime that `hsdev` is not detected

Since that's what's happening.

**Comment by bscottm** [comment]
@1Mark: No. It should not. If `hsdev` is installed, then _SublimeHaskell_ should consistently find `hsdev`.

**Comment by 1Mark** [comment]
@bscottm just to give more context I was writing some txt files and had no haskell files open. So obviously there was no file with the `cabal init`. So I have no idea why this is happening :(

**Comment by bscottm** [comment]
@1Mark: Anything in the ST console? What's your user configuration look like?

**Comment by 1Mark** [comment]
@bscottm will let you know when it happens again. But it's odd since it happens randomly when opening sublime - just opened it a few times and it hasn't happened.

**Comment by lou00011** [comment]
I believe I am having a related error. I have built a Haskell project using _cabal init_, but I am still having problems when comes to automated checking and linting through sublimeHaskell.

The precise error is:
`Uncategorized: Backend error encountered during 'Checking and Linting': other error`

How would I address this problem?

**Comment by bscottm** [comment]
@1Mark: Anything in the console?

**Comment by bscottm** [comment]
@mvoidex: What would cause `hsdev` to report an "other error"?

**Comment by 1Mark** [comment]
![image](https://user-images.githubusercontent.com/15360245/35176590-03c9eefe-fd72-11e7-9b17-3f31320823a7.png)

Spoke too soon. It didnt happen at all yesterday but just now it happened. 

I cant open the console though without dismissing the alert.

**Comment by bscottm** [comment]
@1Mark: Does it consistently happen right after an update? If so, not much I can do about it because I don't have much control over package reloading. The solution is to restart SublimeText, unfortunately.

**Comment by 1Mark** [comment]
I mean I don't think it's after any update since it only happens when I open sublime even if updates happen automatically, it just happened to me again now. So how likely are updates to happen.
![image](https://user-images.githubusercontent.com/15360245/35196734-ff12d706-fecd-11e7-92ba-6135ee4c354a.png)

**Comment by bscottm** [comment]
@1Mark: Each screen shot shows the _SublimeHaskell_ release notes, which is why I wondered if it's consistently after _PackageControl_ downloads the update.

I've released a few updates over the last three weeks or so. 2.1.21 was just pushed. I suspect you'll get that error message... :-)

**Comment by 1Mark** [comment]
Yeah thanks a bunch ;)
