### ISSUE TITLE
Uncategorized: Backend error encountered during 'Checking and Linting'

### ISSUE THREAD

**Issue by lou00011** [SublimeHaskell/SublimeHaskell#394]
I am getting this particular error. I have installed hsdev, sublimehaskell isn't complaining about hsdev and I am currently running main.hs file created through cabal init. I do have sublimelinter - hlint installed as well.

**Comment by bscottm** [comment]
@lou00011: This was new to 2.1.18 as the result of #391. This was an unreported error in `hsdev`, where check/lint would silently succeed even though the Haskell source had blatant errors.

The problem: You probably don't have a `.cabal` file that has your source file referenced in it. It's a problem that's unique to the `hsdev` backend -- `hsdev` expects to find an entire Haskell project (`.cabal` file and source code) when it scans the directory. Otherwise, it doesn't know how to compile your source code because the `.cabal` file give `hsdev` some clue on which versions of imported modules to use.

**Comment by bscottm** [comment]
@lou00011: So, you have a `.cabal` file and a project. I'd have to defer to @mvoidex to explain the "other error" message that `hsdev` produces -- would you mind posting a screen shot of the error?

Also, you might need to change the name of `main.hs` to `Main.hs`. But other than that, I don't have much more insight.

**Comment by bscottm** [comment]
@lou00011: You found a legitimate bug. Should be fixed in 2.1.21

**Comment by lou00011** [comment]
I think the issue is fixed for me. SublimeHaskell had no problem checking and linting the Main.hs. Thanks for the timely fix.

**Comment by lou00011** [comment]
Nevermind. It happened again. Are there specific requirements for what is contained inside Main.hs for checking and linting to work?

**Comment by bscottm** [comment]
@lou00011: Can you paste in an example here so I can test? You're using `hsdev`, and if you remove `module Main where` from the source, _SublimeHaskell_ check/lint no longer checks or lints?

I can see that might be a problem for `ghc` (which is what `hsdev` calls to compile code.)

But please give me a test case so I can diagnose. And fix. And release again. :-)

**Comment by lou00011** [comment]
So this was the Haskell test project I was playing around with. Hopefully you can replicate the behavior with it.
[haskellTest.zip](https://github.com/SublimeHaskell/SublimeHaskell/files/1652262/haskellTest.zip)

**Comment by bscottm** [comment]
@lou00011: Did a little investigating and this is a `hsdev` issue, I'm sorry to say. You (and I) would expect that `hsdev` would run the compiler on the source file and generate an error diagnostic that the syntax of the source is bad. A missing `module` statement is... very incorrect Haskell source. But that's obviously not what happens. `hsdev` reports a very cryptic message that points to a problem with scanning or parsing the source, presumably before it gets to the compiler.

**Comment by lou00011** [comment]
@bscottm thanks for all the thorough investigation. If this is a bug, I am now quite unsure who or where to turn to at this point.

**Comment by anacrolix** [comment]
How can I check what version of hsdev is being used? I'm getting:
```
Errors: 0, Warnings: 0, Hints: 0, Uncategorized 1

Uncategorized: 1

  <no file/command line/OPTIONS_GHC>: line 1, column 1:
    Uncategorized: Backend error encountered during 'Checking and Linting': ghc error
```

**Comment by happysf128** [comment]
@anacrolix I got the same error

**Comment by happysf128** [comment]
@anacrolix and it solved by the same method that @bscottm provide in this issue: [https://github.com/SublimeHaskell/SublimeHaskell/issues/402](url). `SublimeHaskell: Reinspect All`
