### ISSUE TITLE
prettifier doesn't execute after a successful build-on-save

### ISSUE THREAD

**Issue by bscottm** [SublimeHaskell/SublimeHaskell#396]
If `enable_auto_build` is set, _SublimeHaskell_ should execute the prettifier if the build successfully completes, just like it does for check/lint. (@Pastafarianist: Correct?)

**Comment by Pastafarianist** [comment]
I don't think this is a good idea, since it would override a different setting (`prettify_on_save`), which supposedly provides control over exactly that option.

**Comment by bscottm** [comment]
@Pastafarianist: Just being consistent with check/lint. If auto build is set (via `enable_auto_build`), then run the prettifier if `prettify_on_save` is set if the build is successful.
