### ISSUE TITLE
Which branch should I use with hsdev-3.x?

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#397]
I see a [`hsdev-3`](https://github.com/SublimeHaskell/SublimeHaskell/tree/hsdev-3) branch. Should I use this one or the `master` one with [hsdev-3.x](https://hackage.haskell.org/package/hsdev) on Hackage?

**Comment by moodmosaic** [comment]
(Feel free to close this once you provide an answer.)

**Comment by mvoidex** [comment]
Branch still not merged
If you want to test if it works, use this branch

**Comment by moodmosaic** [comment]
Thank you!
