### ISSUE TITLE
Given that hsdev-3 branch isn't merged yet, is the hsdev lower bound correct?

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#400]
https://github.com/SublimeHaskell/SublimeHaskell/blob/0d945ad69dde815a56b8a4e6065ccc03aad6244d/hsdev/backend.py#L42

My guessing is that hsdev 3.* is out, but SublimeHaskell isn't ready for it yet. Thus, this lower bound is confusing.

Also, using hsdev 3.* with `master` and `hsdev-3` branches results into https://github.com/SublimeHaskell/SublimeHaskell/issues/399...

**Comment by bscottm** [comment]
@moodmosaic: Yes. The test is ">= min_version and < max_version".

**Comment by bscottm** [comment]
@moodmosaic: I'm pushing 2.1.23 out later this evening, which will yell at you if you're using the incorrect version of `hsdev`. I got this. :-)

**Comment by moodmosaic** [comment]
Sounds good!
