### ISSUE TITLE
No active project found

### ISSUE THREAD

**Issue by happysf128** [SublimeHaskell/SublimeHaskell#402]
I have install Haskell Platform, cabal and hsdev by following the instruction. I can build my test.hs file by build with Haskell. But when I change to SublimeHaskell, when I build, there is a hint on the bottom  shows "No active projects found". I have no idea why this happened, and no idea how to fix it. Can anyone please help me? Thanks:)

**Comment by bscottm** [comment]
@happysf128: Do you have a `cabal` set up? `hsdev` works on projects, not individual files. If you create a project (`cabal` file) that references your `test.hs` (which should be `Test.hs` or `Main.hs`), that should fix your problem.

**Comment by happysf128** [comment]
@bscottm Thanks. You absolutely right, I did not have `cabal` set up. Well, actually I just want to have sublime for a single `Main.hs` file. But it is no harm to try to set up a project. I followed instruction on cabal website, and run those code to set up my project:
`$ cabal init`
`$ cabal configure`
`$ cabal build`
`$ cabal install`
After all that, sublime still shows "No active projects found".
Any suggestions about what did I do wrong, or did I miss anything? Or any recommendation about how to get sublime haskell working for just one file? Thanks:)

**Comment by bscottm** [comment]
@happysf128: Open the command palette (`Alt-Shift-P` or `Cmd-Shift-P` on Mac) and ask _SublimeHaskell_ to rescan the directory using `SublimeHaskell: Reinspect all`.

I'll try to recreate this on my machine. Seems to be a frequently enough occurring issue to figure out a better way.

**Comment by happysf128** [comment]
Thanks bscottm.  SublimeHaskell: Reinspect all . works. I am not sure why I cannot use all those buttons to write this comment. After I run your code, I build it with SublimeHaskell, then it works.
