### ISSUE TITLE
Any way to install this on arch?

### ISSUE THREAD

**Issue by Visgean** [SublimeHaskell/SublimeHaskell#403]
Currently there seems to be some problems with installation on arch, after failing miserably I installed stack and tried to use hsdev through that but I still could not figure how to make it all work. 

Anyway I started some older version (not 0.3) using ``stack exec hsdev start`` but sublime still prompts me with:

```
Incompatible hsdev, detected version 0.0.0.0
Version should be ≥ 0.2.0.0 and < 0.3.0.0
```

My ``package.yml``:
```
dependencies:
- base >= 4.7 && < 5
- array
- split
- containers
- hsdev < 0.3.0.0
```

my ``stack.yml``:

```
extra-deps: []
- hsdev-0.2.5.1
- haddock-api-2.18.1
- hdocs-0.5.2.1
- haddock-library-1.4.4
```

Is there somebody with a good config files / procedure how to get this working on arch using stack?
I was also considering using some experimental version of SublimeHaskell and hsdev, would that be feasible?
I am very much new to haskell so I dont have a huge experience with managing the toolchain around it. 
Thank you for any advice.

**Comment by mvoidex** [comment]
You can try using latest hsdev with [hsdev-3](https://github.com/SublimeHaskell/SublimeHaskell/tree/hsdev-3) SublimeHaskell branch.

Latest hsdev can be built from trunk with stack

**Comment by bscottm** [comment]
@Visgean: See issue #395.
