### ISSUE TITLE
[Windows] Invalid characters in repl_open argument 'external_id'

### ISSUE THREAD

**Issue by dacto** [SublimeHaskell/SublimeHaskell#404]
https://github.com/SublimeHaskell/SublimeHaskell/blob/344673b42815495475076898b864f053524238a4/repl.py#L217

Attempting to run `SublimeHaskell: Cabal/Stack-wrapped REPL` on a stack project ends up causing SublimeREPL to throw an `OSError(22, 'Invalid argument')` due the `external_id` string having invalid Windows filename characters (in this case `:`).

#### repl_open
```
self.window.run_command("repl_open", repl_args(cmd=['stack', 'repl', 'app:exe:app'],
                                               cwd="C:\Users\userxyz\Documents\repositories\app",
                                               loaded="C:\Users\userxyz\Documents\repositories\app",
                                               external_id="Haskell stack repl app:exe:app"))
```
#### Stacktrace
```
Traceback (most recent call last):
  File "C:\Users\userxyz\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 495, in open
    rv = ReplView(view, r, syntax, repl_restart_args)
  File "C:\Users\userxyz\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 186, in __init__
    self._history = PersistentHistory(self.external_id)
  File "C:\Users\userxyz\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\sublimerepl.py", line 140, in __init__
    self._db.create("external_id", "command", "ts", mode="open")
  File "C:\Users\userxyz\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repllibs\PyDbLite.py", line 200, in create
    self.commit()
  File "C:\Users\userxyz\AppData\Roaming\Sublime Text 3\Packages\SublimeREPL\repllibs\PyDbLite.py", line 258, in commit
    out = open(self.name,'wb')
OSError: [Errno 22] Invalid argument: 'C:\\Users\\userxyz\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\.SublimeREPLHistory\\Haskell stack repl app:exe:app.db'
error: OSError(22, 'Invalid argument')
```

#### A few workarounds
1. Disable SublimeREPL's history by setting `"persistent_history_enabled": false`.
2. Locally change `repl.py` to use a static string consisting of only valid filename characters.
3. Locally change `repl.py` to replace all invalid filename characters.

These workarounds are mostly undesirable since REPL history is useful.

#### Remarks
Alternatively, this could be considered a SublimeREPL bug since it uses `{external_id}.db` as the filename for repl history databases.

**Comment by bscottm** [comment]
@dacto: And here I thought that the REPL external ID was just a window title... I'll craft a fix.

**Comment by bscottm** [comment]
@dacto: Sorry it's taking longer than expected. It turns out that _SublimeREPL_, the `external_id` is the challenge -- how to have an aesthetically pleasing tab title that's also a valid file name.

**Comment by dacto** [comment]
@bscottm: Understandable; I also do not have an elegant solution at the ready.

**Comment by bscottm** [comment]
@dacto: Best I can do is translate known illegal characters into "_" or "-". In the 2.1.25 release.

**Comment by dacto** [comment]
@bscottm that works.
But thinking about it more, it might be best in the long run to file an issue with SublimeREPL since it uses `external_id` for both title and database file without sanitizing it. The string for the title should be unrestricted while the string for a filename should take care of illegal characters.

**Comment by bscottm** [comment]
@dacto: That'd be you or me? Alternatively, they could map their existing UUIDs to `external_id`, use the UUID for the database name. It's a level of inscrutability, to be sure, but it does avoid the illegal file name issue.

But that doesn't help you today, which is why I pushed the release and translated file name characters. I only have to remove the translation to revert to the previous name. :-)

**Comment by bscottm** [comment]
@dacto: Unbroken?
