### ISSUE TITLE
Prettify on save is broken again in 2.1.24

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#407]
Upon hitting `Ctrl+S` for a Haskell file, both in and outside of a project, `do_prettify` doesn't get called at all (as determined by adding `print("do_prettify")` at line 15 of `indenters.py`).

Manually calling `SublimeHaskell: Stylish` via `Ctrl+Shift+P` works as expected.

Could you add regression tests please? This is the third time `prettify_on_save` gets broken, I think.

**Comment by bscottm** [comment]
@Pastafarianist: There are no specific unit tests to test functionality, so there's nowhere to test for regressions. Something I plan to do after the syntax highlighting upgrade.

Did you restart after the Package Control update? :-)
Is there a traceback in the ST console?

**Comment by Pastafarianist** [comment]
I did restart; there is no traceback; yep, still on `None`.

**Comment by bscottm** [comment]
@Pastafarianist: And did you just happen to upgrade to ST Build 3157?

**Comment by Pastafarianist** [comment]
Yes... Sorry, forgot to mention.

**Comment by bscottm** [comment]
@Pastafarianist: "Ready, Fire, Aim!" is a frequently used saying in the US Navy to these describe useful information that arrives after an event. Probably common in many other navies and military organizations. Build 3157 changed the event listener API once again. :-)

The persistent view metadata stores the last used syntax, which happens to be "Haskell-SublimeHaskell.tmLanguage", the old version. ST3 doesn't automagically upgrade to the newer "sublime-syntax" file if the '.tmLanguage' is still available. _SublimeHaskell_ didn't look for the old syntax file's name when determining whether a view is Haskell source.

Fix is on its way.

**Comment by bscottm** [comment]
@Pastafarianist: Unbroken?

**Comment by Pastafarianist** [comment]
@bscottm seems so. Thanks!
