### ISSUE TITLE
Obtaining a working development machine is nearly impossible

### ISSUE THREAD

**Issue by gdennie** [SublimeHaskell/SublimeHaskell#410]
VirtualBox and Docker offer free virtual machines that can be use to host a Linux system preconfigured with a ready to use Sublime-Haskell IDE. Obtaining such a thing by a near novice is nearly impossible due to the various version conflicts and configuration adjustments required that span Linux, Sublime Text 3, Stack, GHC, etc. With the sparsity of documentation and index to any relevant documentation and clarity of it, there is real challenge to creating Haskell code beyond toy expression in GHCI.

Consequently, it must be possible for someone with experience to publish a VirtualBox and/or Docker image of a ready to use development environment for Haskell with Sublime-Text-3 that produces production code.

Good grief!!

Thanks in advance.

**Comment by bscottm** [comment]
@gdennie: I understand your frustration with getting a captive environment running. Unfortunately, that isn't really in the scope of _SublimeHaskell_ bugs -- is there a bug that you need me to fix?

**Comment by gdennie** [comment]
Thanks for a quick response. Fortunately, it seems I may have resolved all the issues. The issue seems to have been that the Linux Mint distribution still serves the 0.9v of the Haskell Platform which does not properly implement or configure for 'stack upgrade' resulting in a rather high first step for newbies who are not being handheld. Thanks again.

**Comment by bscottm** [comment]
@gdennie: Glad you got this all figured out. Haskell is a pretty high bar to jump over to start with, combine that with Docker and I can see how even experienced developers might have problems.
