### ISSUE TITLE
Autofix and Warning popup problem

### ISSUE THREAD

**Issue by woopsla** [SublimeHaskell/SublimeHaskell#414]
I've successfully installed hsdev-0.2.5.1 on my Mac, and tested it using both cabal and stack.

Everything seems to be working fine, but when I hover over either autofix or warning icons in the gutter, no popup show up.  When I click the icons, nothing happens.  Is it a sublime text problem? I am using SublimeText build 3143. I can see corresponding warning and hints on the console window.

Or is it related to this error?

<hsdev stderr> 2018-03-05 14:24:04 +0900	ERROR	:127.0.0.1:50258/update/task/directory/task/package-db/scan> Error reading cache: IO exception while reading cache from ...

**Comment by bscottm** [comment]
@woopsla: The "IO exception" issue is an annoying, but harmless, message. I'll see if I can recreate because this normally works for me (I'm on Mac as well.)

**Comment by bscottm** [comment]
Found the problem. My bad. Should show up on Package Control as 2.1.28.

**Comment by woopsla** [comment]
I removed SublimeHaskell and installed it again using Package Control. Now it works fine. Thank you very much.I really appreciate that.

**Comment by bscottm** [comment]
@woopsla: You shouldn't have had to remove SublimeHaskell completely -- there's an upgrade command in Package Control that'll upgrade the plugin when a new version is pushed to PackageControl.io.
