### ISSUE TITLE
Additional options for lint

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#415]
They look like this in the settings:

```
"lint_opts": [],
...
```

---

But how exactly would I specify which `.hlint.yaml` file to pick up? I tried doing something like:

```
"lint_opts": [".hlint.yaml"]
```

and

```
"lint_opts": ["hint=.hlint.yaml"]
```

but none seem to work.

---

From the command line, it would look like this:

```
stack exec -- hlint . --hint=.hlint.yaml
```

**Comment by moodmosaic** [comment]
Any thoughts? 😕

**Comment by bscottm** [comment]
@moodmosaic: A distance learning course of mine just started up 2 weeks ago, very heavy reading (von Clausewitz is very slow reading; "Strategy and War" with the US Navy War College) and smacking my head against a wall with ST3 syntax highlighting.

Lemme take a look.

**Comment by moodmosaic** [comment]
@bscottm, alright, cool, no rush 👍 🥇 💯

**Comment by bscottm** [comment]
@moodmosaic: I'll hack in support for this with the fix to the color scheme format change. Sometime this week, S&W coursework permitting.

**Comment by bscottm** [comment]
@moodmosaic: Quick look at `hsdev` code: No, `hsdev` does not accept any `HLint` options. `ghc` options, yes. `HLint` options, no. Suggest issue on the `hsdev` project.

**Comment by moodmosaic** [comment]
Well, hmm..., then why we offer those options in SH if `hsdev` doesn't support them?

**Comment by moodmosaic** [comment]
I mean, what am I supposed to put inside `"lint_opts": []` anyway? (Putting `hlint` aside.)

**Comment by bscottm** [comment]
@moodmosaic: `hsdev 0.3.x` supposedly will accept `HLint` options via the `lint_opts` setting. I've yet to see that `hsdev 0.3.x` actually does anything with them. `hsdev 0.2.x` ignores `HLint` options completely (oddly, though, it does accept GHC options.)

Maybe I'm misinterpreting your question... in addition to wondering whether `hsdev 0.3.x` does anything useful with `HLint` options, is your question also wondering if variables are expanded in the option list?

**Comment by moodmosaic** [comment]
I don't know. I've pushed myself hard (and even [promoted](https://stackoverflow.com/a/48800504/467754)) the use of SH... It's just that, after all those issues I reported, to me it looks like the project needs a bit of cleanup.

I love Sublime Text, I *really* like the idea of Sublime Haskell, it's just that the add-in itself probably needs some cleanup.

Do I need to see this garbage when `hdocs` fires up?
```
<hsdev stderr> �[96m2018-02-22 12:47:36 +0200�[m�[m �[m�[91mERROR�[m�[m �[m�[95m�[m�[m:�[m�[92mupdate/cabal/task/package-db-stack�[m�[m> �[m�[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> �[m�[m
<hsdev stderr> �[96m2018-02-22 12:47:36 +0200�[m�[m �[m�[91mERROR�[m�[m �[m�[95m�[m�[m:�[m�[92mupdate/cabal/task�[m�[m> �[m�[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> �[m�[m
<hsdev stderr> �[96m2018-02-22 12:47:36 +0200�[m�[m �[m�[91mERROR�[m�[m �[m�[95m�[m�[m:�[m�[92mupdate/cabal�[m�[m> �[m�[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> �[m�[m
<hsdev stderr> �[96m2018-02-22 12:47:36 +0200�[m�[m �[m�[91mERROR�[m�[m �[m�[95m�[m�[m:�[m�[92mupdate�[m�[m> �[m�[mtool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db�[m�[m
font face "Times" could not be found, defaulting to "Consolas"
```

I know more and more people who sadly switch from Sublime Text to Atom or Code just because they can't get SH to work reliably 😢

**Comment by bscottm** [comment]
@moodmosaic: Ummm.... that's `hsdev 0.3` and... wait for it... @mvoidex added ANSI colors to the output.  All of the stuff you're seeing are ANSI color escape codes. I've asked @mvoidex to turn it off.

What ticks me off a bit is that `hdev 0.3.x` development happend on the `master` branch for `hsdev` instead of on a separate branch. I develop SH on a private clone and I merge when things are releasable.

Totally agree with you about the development and release process.

**Comment by moodmosaic** [comment]
@bscottm, I'll try `hsdev 0.3` over the weekend. Would it be also possible to disable these as well?
```
<hsdev stderr> ...
```
Or at least to be able to set the logging level (verbose, error, warning) through some option?

**Comment by moodmosaic** [comment]
@bscottm, see https://github.com/mvoidex/hsdev/issues/81#issuecomment-376077742. Is there a way to specify `--no-color` somewhere?

**Comment by moodmosaic** [comment]
I just saw https://github.com/SublimeHaskell/SublimeHaskell/pull/386/commits/1e8d2e04d27d45509a7e7de6751bbe2314eff4e5, so I'll pull the latest and retry.

**Comment by moodmosaic** [comment]
Tested and appears to work fine 🎉
