### ISSUE TITLE
Autocomplete (and more?) broken

### ISSUE THREAD

**Issue by matchwood** [SublimeHaskell/SublimeHaskell#417]
Firstly, thanks for all the work you've put into this!

Sublime Text 3 (3143)
SublimeHaskell 2.1.29

I use Sublime Haskell (without a backend) for syntax highlighting and autocompletions.

Starting today, Sublime Haskell is not showing any autocompletions. The following appears in the console.

```
Sublime Haskell: worker: job on_activated failed, see console window traceback
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Packages/SublimeHaskell/internals/utils.py", line 63, in worker_run
    worker_fn(*args, **kwargs)
  File "/home/user/.config/sublime-text-3/Packages/SublimeHaskell/zzplugin.py", line 388, in activated_worker
    EventCommon.assoc_to_project(view, self.backend_mgr, filename)
  File "/home/user/.config/sublime-text-3/Packages/SublimeHaskell/event_common.py", line 22, in assoc_to_project
    project_dir, project_name = Common.locate_cabal_project(filename)
  File "/home/user/.config/sublime-text-3/Packages/SublimeHaskell/sublime_haskell_common.py", line 97, in locate_cabal_project
    directory_of_file = os.path.dirname(filename)
  File "./python3.3/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind'
```

I have reverted to 2.1.27, which seems to be working ok for my use cases.

**Comment by bscottm** [comment]
@matchwood: 2 steps forward, 1 step back. Ugh. Will fix, release as 2.1.30.

**Comment by matchwood** [comment]
Haha thanks again. Runtime type errors ... shame you can't write the plugin code in Haskell eh?

**Comment by bscottm** [comment]
@matchwood: 2.1.30 pushed to PackageControl. Apologies for the inconvenience.

**Comment by matchwood** [comment]
I've tried with the new code. The console errors are gone, but the autocompletion is still entirely absent. I'm wondering if the changes you made to address #416 ended up overriding the 'dumb' autocomplete I've been using. I understand that if you are using a backend then you should end up with 'smart' autocompletes (from imported modules etc), but all the backends are too slow for my large codebase so  I was really just relying on the autocomplete giving me words that were in the file (I think this may be ST default behaviour?).

**Comment by bscottm** [comment]
What do your user settings look like? There is one, which I can't remember off the top of my head, but its default is false (not on my laptop at the moment.)

**Comment by bscottm** [comment]
Set `add_word_completions`to true in your user settings, if you haven't already done so.

**Comment by matchwood** [comment]
Ah yes, that did it, many thanks. It must be that the old code just didn't respect that value or something, because it was working in previous releases with `add_word_completions` set to false.
