### ISSUE TITLE
This, and hsdev and hdocs, are still the best!

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#444]
Really! Specially hsdev is *sooo* damn fast compared to the competition. Works so well out of the box. :100: 

---

@mvoidex and contributors, keep up the good work :+1: :1st_place_medal: :rocket: :roller_coaster:

**Comment by moodmosaic** [comment]
:heart:

**Comment by mvoidex** [comment]
Thanks :)
