### ISSUE TITLE
Can I disable 'Uncategorized' errors?

### ISSUE THREAD

**Issue by moodmosaic** [SublimeHaskell/SublimeHaskell#447]
Is there a way to disable/hide them so the pop up won't show up?

![image](https://user-images.githubusercontent.com/287532/91842114-b6b55800-ec53-11ea-99e4-32bd10369d13.png)

**Comment by moodmosaic** [comment]
Posted also in https://github.com/mvoidex/hsdev/issues/104, just in case it can be done from there.

**Comment by mvoidex** [comment]
It can't be hidden. This error means `hsdev` was not able to check and lint (unknown ghc error inside), so it's likely to be hsdevs issue

**Comment by moodmosaic** [comment]
I managed to 'hide' the error by commenting it out manually in the hsdev source. Not a proper fix but hey works on my local :eyes:
