### ISSUE TITLE
Specifying cabal-dev sandbox

### ISSUE THREAD

**Issue by fatlazycat** [SublimeHaskell/SublimeHaskell#48]
Hi, leaving the setting cabal_dev_sandbox as "" doesn't use the cabal-dev default of using 'cabal-dev' under the current working directory.

Setting cabal_dev_sandbox appears only to work in the sublime haskell user settings file. Not when in the project file settings.

Hence I can't have a sandbox per project defined. Am I missing something ? 

Thanks

**Comment by mvoidex** [comment]
Cabal-dev sandboxes are no more supported
