### ISSUE TITLE
Fixing the syntax highlighter

### ISSUE THREAD

**Issue by nh2** [SublimeHaskell/SublimeHaskell#63]
With https://github.com/SublimeHaskell/SublimeHaskell/commit/98d1f3d83f2ceb2cf48a6819a24abec32597f687 I just added a way we can fix the built-in Haskell syntax highlighting lexer, and the first fixed issue is https://github.com/SublimeHaskell/SublimeHaskell/commit/561fc63a5188449c303c0105142203d509cb004e.

We should collect what other things are wrong with the default lexer, and fix them.

The first thing that comes to my mind:
- If an import with import list doesn't have the bracket on the same line, imported functions are not highlighted:

```
import Data.List
    (sort, nub) -- <- not coloured!
```

Any other things that are wrong with the syntax highlighting?

**Comment by moodmosaic** [comment]
Great work. Are these changes used by default now when using SublimeHaskell? Or do I have to override the built-in Haskell syntax through some setting?

**Comment by mvoidex** [comment]
By default. There are still issue with syntax (it's hard to make correct syntax with regexes), but it should be better than submiletext default one for Haskell.
I, personally, also disabled default 'haskell' plugin in sluser prefs: `"ignored_packages": ["Haskell"]`

**Comment by moodmosaic** [comment]
>`"ignored_packages": ["Haskell"]`
👍

Though, shouldn't these patterns be in white?

![untitled](https://cloud.githubusercontent.com/assets/287532/22968477/36a64ca0-f373-11e6-8d04-8f90e3ebcf8e.png)

**Comment by mvoidex** [comment]
I'm not sure :) Maybe
Syntax was written when SublimeHaskell haven't overwritten default `ctrl-R`, so the idea was to see function name in goto-list. But type signature may be omitted and therefore function with not typesig won't be there.

**Comment by moodmosaic** [comment]
I think they got it right in Atom, if you look at the screenshot below you'll see what I mean.

![capture](https://cloud.githubusercontent.com/assets/287532/22969865/ac29662e-f378-11e6-8b41-bb72fd3ace4c.PNG)

In Sublime, `endTag` on line `49` should be white, no?

**Comment by mvoidex** [comment]
I think you're right.
This decision were made so that even if you have no typesig, function name will appear in `ctrl-r` list, so that you can go to it. You can't make it white and also say to sublime that it's function entity (or maybe i just don't know how to do it). But i agree, that such coloring is incorrect.
