### ISSUE TITLE
SublimeHaskell ignores settings inside "Settings -- User"

### ISSUE THREAD

**Issue by k-bx** [SublimeHaskell/SublimeHaskell#70]
I was long trying to figure out why do I get:

```
SublimeHaskell: ghc-mod was not found!
```

After digging inside plugin's code, it turned out, that SublimeHaskell only loads settings from `SublimeHaskell.sublime-settings`. I'm not sure if this is intended (or I understood sources right), but it doesn't seem to be explicitly and obviously.

So, if this is done by intent, we should extend error-message to explicitly mention that setting add_to_PATH need to be added into `SublimeHaskell.sublime-settings` file, and that it should be a list of paths (I'd suggest renaming setting to something like `extend_PATH_list`).

If this is not by intent, SublimeHaskell should be upgraded to be able to read Default and User-settings also.

Thanks!

**Comment by bscottm** [comment]
@k-bx: User settings seem to work in the current plugin. Closing -- feel free to re-open if this continues to be an issue.
