### ISSUE TITLE
SublimeHaskell shadows kill line keybinding

### ISSUE THREAD

**Issue by roldugin** [SublimeHaskell/SublimeHaskell#81]
SublimeHaskell shadows "ctrl+k" keybinding which is a common way to delete until the end of line on unixes.

The commands that start with "ctrl+k" are "Show type", "Insert type" and "Show symbol info".

Actually, if you press "ctrl+k" and then do something else like move the cursor it will perform the kill but this is not very intuitive.

A workaround is to obviously remove these commands from the Default keybindings, and add different ones, but I thought I would report this so a fix is considered. Cheers :)

**Comment by bscottm** [comment]
Closing. Assuming fixed.
